CC=cl
LIBTOOL=lib
CFLAGS=/nologo /W4 /O2 /TC /Iinclude /Isrc
!IFNDEF LDFLAGS
LDFLAGS=
!ENDIF
!IFNDEF NSS_DIST
NSS_DIST=
!ENDIF
NSS_CFLAGS=$(CFLAGS) /I$(NSS_DIST)\include\nspr /I$(NSS_DIST)\public\nss
BUILD=build\vc6
LIB=$(BUILD)\papinho_secure_transport.lib
OBJS=$(BUILD)\pst_version.obj $(BUILD)\pst_result.obj $(BUILD)\pst_diagnostic.obj $(BUILD)\pst_log.obj $(BUILD)\pst_validation.obj $(BUILD)\pst_identity.obj $(BUILD)\pst_backend.obj $(BUILD)\pst_runtime.obj
all: dirs $(LIB) $(BUILD)\test_foundation.exe $(BUILD)\test_identity.exe $(BUILD)\test_backend_spi.exe $(BUILD)\test_tls_policy.exe $(BUILD)\test_diagnostic.exe $(BUILD)\test_diagnostic_transport.exe $(BUILD)\test_diagnostic_creation.exe $(BUILD)\test_public_diagnostic.exe $(BUILD)\test_public_header.exe $(BUILD)\test_logging.exe $(BUILD)\test_lifecycle_ownership.exe
dirs:
	@if not exist build mkdir build
	@if not exist $(BUILD) mkdir $(BUILD)
$(BUILD)\pst_version.obj: src\pst_version.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_result.obj: src\pst_result.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_diagnostic.obj: src\pst_diagnostic.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_log.obj: src\pst_log.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_validation.obj: src\pst_validation.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_identity.obj: src\pst_identity.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_backend.obj: src\pst_backend.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_runtime.obj: src\pst_runtime.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(LIB): $(OBJS)
	$(LIBTOOL) /nologo /out:$@ $(OBJS)
$(BUILD)\test_foundation.obj: tests\test_foundation.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_foundation.exe: $(BUILD)\test_foundation.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_foundation.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_identity.obj: tests\test_identity.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_identity.exe: $(BUILD)\test_identity.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_identity.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_backend_spi.obj: tests\test_backend_spi.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_backend_spi.exe: $(BUILD)\test_backend_spi.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_backend_spi.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_tls_policy.obj: tests\test_tls_policy.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_tls_policy.exe: $(BUILD)\test_tls_policy.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_tls_policy.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_diagnostic.obj: tests\test_diagnostic.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_diagnostic.exe: $(BUILD)\test_diagnostic.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_diagnostic.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_diagnostic_transport.obj: tests\test_diagnostic_transport.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_diagnostic_transport.exe: $(BUILD)\test_diagnostic_transport.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_diagnostic_transport.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_diagnostic_creation.obj: tests\test_diagnostic_creation.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_diagnostic_creation.exe: $(BUILD)\test_diagnostic_creation.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_diagnostic_creation.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_public_diagnostic.obj: tests\test_public_diagnostic.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_public_diagnostic.exe: $(BUILD)\test_public_diagnostic.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_public_diagnostic.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_public_header.obj: tests\test_public_header.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_public_header.exe: $(BUILD)\test_public_header.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_public_header.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_logging.obj: tests\test_logging.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_logging.exe: $(BUILD)\test_logging.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_logging.obj $(LIB) $(LDFLAGS)
$(BUILD)\test_lifecycle_ownership.obj: tests\test_lifecycle_ownership.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_lifecycle_ownership.exe: $(BUILD)\test_lifecycle_ownership.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_lifecycle_ownership.obj $(LIB) $(LDFLAGS)
$(BUILD)\pst_backend_nss.obj: src\backends\nss\pst_backend_nss.c
	@if "$(NSS_DIST)"=="" echo NSS_DIST is required & exit 2
	$(CC) $(NSS_CFLAGS) /Fo$@ /c $**
$(BUILD)\test_backend_nss.obj: tests\test_backend_nss.c
	@if "$(NSS_DIST)"=="" echo NSS_DIST is required & exit 2
	$(CC) $(NSS_CFLAGS) /Fo$@ /c $**
$(BUILD)\test_backend_nss.exe: $(BUILD)\test_backend_nss.obj $(BUILD)\pst_backend_nss.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_backend_nss.obj $(BUILD)\pst_backend_nss.obj $(LIB) wsock32.lib $(LDFLAGS)
$(BUILD)\test_backend_nss_integration.obj: tests\test_backend_nss_integration.c
	@if "$(NSS_DIST)"=="" echo NSS_DIST is required & exit 2
	$(CC) $(NSS_CFLAGS) /Fo$@ /c $**
$(BUILD)\test_backend_nss_integration.exe: $(BUILD)\test_backend_nss_integration.obj $(BUILD)\pst_backend_nss.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_backend_nss_integration.obj $(BUILD)\pst_backend_nss.obj $(LIB) wsock32.lib $(LDFLAGS)
$(BUILD)\test_tls_runtime_integration.obj: tests\test_tls_runtime_integration.c
	@if "$(NSS_DIST)"=="" echo NSS_DIST is required & exit 2
	$(CC) $(NSS_CFLAGS) /Fo$@ /c $**
$(BUILD)\test_tls_runtime_integration.exe: $(BUILD)\test_tls_runtime_integration.obj $(BUILD)\pst_backend_nss.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_tls_runtime_integration.obj $(BUILD)\pst_backend_nss.obj $(LIB) wsock32.lib $(LDFLAGS)
$(BUILD)\test_stress_stability.obj: tests\test_stress_stability.c
	@if "$(NSS_DIST)"=="" echo NSS_DIST is required & exit 2
	$(CC) $(NSS_CFLAGS) /Fo$@ /c $**
$(BUILD)\test_stress_stability.exe: $(BUILD)\test_stress_stability.obj $(BUILD)\pst_backend_nss.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_stress_stability.obj $(BUILD)\pst_backend_nss.obj $(LIB) wsock32.lib $(LDFLAGS)
stress-integration: dirs $(LIB) $(BUILD)\test_stress_stability.exe
$(BUILD)\test_connection_failures.obj: tests\test_connection_failures.c
	@if "$(NSS_DIST)"=="" echo NSS_DIST is required & exit 2
	$(CC) $(NSS_CFLAGS) /Fo$@ /c $**
$(BUILD)\test_connection_failures.exe: $(BUILD)\test_connection_failures.obj $(BUILD)\pst_backend_nss.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_connection_failures.obj $(BUILD)\pst_backend_nss.obj $(LIB) wsock32.lib $(LDFLAGS)
$(BUILD)\test_nt4_lifecycle_integration.obj: tests\test_nt4_lifecycle_integration.c
	@if "$(NSS_DIST)"=="" echo NSS_DIST is required & exit 2
	$(CC) $(NSS_CFLAGS) /Fo$@ /c $**
$(BUILD)\test_nt4_lifecycle_integration.exe: $(BUILD)\test_nt4_lifecycle_integration.obj $(BUILD)\pst_backend_nss.obj $(LIB)
	$(CC) /nologo /Fe$@ $(BUILD)\test_nt4_lifecycle_integration.obj $(BUILD)\pst_backend_nss.obj $(LIB) wsock32.lib $(LDFLAGS)
lifecycle-integration: dirs $(LIB) $(BUILD)\test_nt4_lifecycle_integration.exe
runtime-integration: dirs $(LIB) $(BUILD)\test_tls_runtime_integration.exe
failure-integration: dirs $(LIB) $(BUILD)\test_connection_failures.exe
test: all
	$(BUILD)\test_foundation.exe
	$(BUILD)\test_identity.exe
	$(BUILD)\test_backend_spi.exe
	$(BUILD)\test_tls_policy.exe
	$(BUILD)\test_diagnostic.exe
	$(BUILD)\test_diagnostic_transport.exe
	$(BUILD)\test_diagnostic_creation.exe
	$(BUILD)\test_public_diagnostic.exe
	$(BUILD)\test_public_header.exe
	$(BUILD)\test_logging.exe
	$(BUILD)\test_lifecycle_ownership.exe
test-nss-unit: dirs $(LIB) $(BUILD)\test_backend_nss.exe
	$(BUILD)\test_backend_nss.exe
nss-integration: dirs $(LIB) $(BUILD)\test_backend_nss_integration.exe
test-nss-integration: nss-integration
	@if "$(NSS_TEST_HOST)"=="" echo NSS_TEST_HOST is required & exit 2
	@if "$(NSS_TEST_PORT)"=="" echo NSS_TEST_PORT is required & exit 2
	@if "$(NSS_TEST_NAME)"=="" echo NSS_TEST_NAME is required & exit 2
	$(BUILD)\test_backend_nss_integration.exe $(NSS_TEST_HOST) $(NSS_TEST_PORT) $(NSS_TEST_NAME)
clean:
	@if exist $(BUILD) rmdir /s /q $(BUILD)
