# SPDX-License-Identifier: MPL-2.0
CC=cl
LIBTOOL=lib
BUILD=build\win32-x64-msvc-19.51-schannel
LDFLAGS=/link
CFLAGS=/nologo /W4 /O2 /TC /MD /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /Iinclude /Isrc
CORE=$(BUILD)\pst_version.obj $(BUILD)\pst_result.obj $(BUILD)\pst_diagnostic.obj $(BUILD)\pst_log.obj $(BUILD)\pst_validation.obj $(BUILD)\pst_identity.obj $(BUILD)\pst_backend.obj $(BUILD)\pst_runtime.obj $(BUILD)\pst_transport_win32.obj $(BUILD)\pst_builtin_manifest.obj $(BUILD)\pst_backend_schannel.obj
PSTLIB=$(BUILD)\papinho_secure_transport.lib
all: dirs $(PSTLIB) $(BUILD)\test_public_header.exe $(BUILD)\test_public_abi.exe $(BUILD)\test_provider_spi_abi.exe $(BUILD)\test_public_win32_header.obj $(BUILD)\test_public_builtin_bootstrap.exe $(BUILD)\test_backend_schannel.exe $(BUILD)\test_schannel_runtime_integration.exe $(BUILD)\test_schannel_runtime_isolation.exe $(BUILD)\test_schannel_buffers.exe
dirs:
	@if not exist build mkdir build
	@if not exist $(BUILD) mkdir $(BUILD)
$(BUILD)\pst_version.obj: src\pst_version.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_result.obj: src\pst_result.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_diagnostic.obj: src\pst_diagnostic.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_log.obj: src\pst_log.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_validation.obj: src\pst_validation.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_identity.obj: src\pst_identity.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_backend.obj: src\pst_backend.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_runtime.obj: src\pst_runtime.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_transport_win32.obj: src\platform\win32\pst_transport_win32.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\pst_builtin_manifest.obj: src\platform\win32\pst_builtin_manifest.c
	$(CC) $(CFLAGS) /DPST_BUILTIN_SCHANNEL /Fo$@ /c $**
$(BUILD)\pst_backend_schannel.obj: src\backends\schannel\pst_backend_schannel.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(PSTLIB): $(CORE)
	$(LIBTOOL) /nologo /out:$@ $(CORE)
$(BUILD)\test_public_header.obj: tests\test_public_header.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_public_header.exe: $(BUILD)\test_public_header.obj $(PSTLIB)
	$(CC) /nologo /Fe$@ $** $(LDFLAGS)
$(BUILD)\test_public_abi.obj: tests\test_public_abi.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_provider_spi_abi.obj: tests\test_provider_spi_abi.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_provider_spi_abi.exe: $(BUILD)\test_provider_spi_abi.obj $(PSTLIB)
	$(CC) /nologo /Fe$@ $** $(LDFLAGS)
$(BUILD)\test_public_win32_header.obj: tests\test_public_win32_header.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_public_abi.exe: $(BUILD)\test_public_abi.obj $(PSTLIB)
	$(CC) /nologo /Fe$@ $** $(LDFLAGS)
$(BUILD)\test_backend_schannel.obj: tests\test_backend_schannel.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_backend_schannel.exe: $(BUILD)\test_backend_schannel.obj $(PSTLIB)
	$(CC) /nologo /Fe$@ $** $(LDFLAGS) ws2_32.lib secur32.lib crypt32.lib ncrypt.lib
$(BUILD)\test_schannel_runtime_integration.obj: tests\test_schannel_runtime_integration.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_schannel_runtime_integration.exe: $(BUILD)\test_schannel_runtime_integration.obj $(PSTLIB)
	$(CC) /nologo /Fe$@ $** $(LDFLAGS) ws2_32.lib secur32.lib crypt32.lib ncrypt.lib
$(BUILD)\test_schannel_runtime_isolation.obj: tests\test_schannel_runtime_isolation.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_schannel_runtime_isolation.exe: $(BUILD)\test_schannel_runtime_isolation.obj $(PSTLIB)
	$(CC) /nologo /Fe$@ $** $(LDFLAGS) ws2_32.lib secur32.lib crypt32.lib ncrypt.lib
$(BUILD)\test_schannel_buffers.obj: tests\test_schannel_buffers.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_schannel_buffers.exe: $(BUILD)\test_schannel_buffers.obj $(PSTLIB)
	$(CC) /nologo /Fe$@ $** $(LDFLAGS) ws2_32.lib secur32.lib crypt32.lib ncrypt.lib
test: all
	$(BUILD)\test_public_header.exe
	$(BUILD)\test_public_abi.exe
	$(BUILD)\test_provider_spi_abi.exe
	$(BUILD)\test_backend_schannel.exe
	$(BUILD)\test_schannel_buffers.exe
clean:
	@if exist $(BUILD) rmdir /s /q $(BUILD)
$(BUILD)\test_public_builtin_bootstrap.obj: tests\test_public_builtin_bootstrap.c
	$(CC) $(CFLAGS) /Fo$@ /c $**
$(BUILD)\test_public_builtin_bootstrap.exe: $(BUILD)\test_public_builtin_bootstrap.obj $(PSTLIB)
	$(CC) /nologo /Fe$@ $** $(LDFLAGS) ws2_32.lib secur32.lib crypt32.lib ncrypt.lib
