/* SPDX-License-Identifier: MPL-2.0 */
#include "papinho_secure_transport.h"
#include "papinho_secure_transport_win32.h"
#include "backends/openssl/pst_backend_openssl.h"
#include "pst_transport_internal.h"
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#include <winsock2.h>
#include <openssl/crypto.h>
#include <openssl/err.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static unsigned char *load_file(const char *path,pst_size *size){FILE*f;long n;unsigned char*p;*size=0;f=fopen(path,"rb");if(!f)return NULL;if(fseek(f,0,SEEK_END)||((n=ftell(f))<0)||fseek(f,0,SEEK_SET)){fclose(f);return NULL;}p=(unsigned char*)malloc((size_t)n);if(!p){fclose(f);return NULL;}if(n&&fread(p,1,(size_t)n,f)!=(size_t)n){free(p);fclose(f);return NULL;}fclose(f);*size=(pst_size)n;return p;}
static int connect4(const char *address,unsigned short port,SOCKET *out){SOCKET s;struct sockaddr_in a;memset(&a,0,sizeof(a));a.sin_family=AF_INET;a.sin_port=htons(port);a.sin_addr.s_addr=inet_addr(address);s=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(s==INVALID_SOCKET)return 0;if(connect(s,(struct sockaddr*)&a,sizeof(a))==SOCKET_ERROR){closesocket(s);return 0;}*out=s;return 1;}
static void fill_payload(unsigned char *buffer,pst_size size){static const unsigned char pattern[]="pst-phase5-public-runtime";pst_size i;for(i=0;i<size;i++)buffer[i]=pattern[i%(sizeof(pattern)-1)];}
static PST_RESULT parse_result(const char *text){if(!strcmp(text,"OK"))return PST_RESULT_OK;if(!strcmp(text,"PROTOCOL"))return PST_RESULT_PROTOCOL_FAILURE;if(!strcmp(text,"AUTH"))return PST_RESULT_AUTH_FAILURE;if(!strcmp(text,"TRUNCATED"))return PST_RESULT_TRUNCATED;return PST_RESULT_BACKEND_FAILURE;}
static int wait_ready(const PST_BACKEND_DESCRIPTOR *d,void *connection,pst_u32 *waits){pst_u32 interest;PST_BACKEND_WAIT_RESULT result;if(d->vtable->get_interest(connection,&interest)!=PST_RESULT_OK||interest==0UL)return 0;memset(&result,0,sizeof(result));(*waits)++;return d->vtable->wait(connection,interest,2000UL,&result)==PST_RESULT_OK&&!result.timed_out&&result.ready_interest!=0UL;}
int main(int argc,char **argv){const PST_BACKEND_DESCRIPTOR*d=NULL;void*backend=NULL,*runtime=NULL,*connection=NULL;WSADATA wd;SOCKET socket_value=INVALID_SOCKET,owned_socket=INVALID_SOCKET;pst_transport*transport=NULL;pst_trust*trust=NULL;pst_config*config=NULL;PST_TRUST_SOURCE trust_source;PST_IDENTITY_CONFIG identity;PST_TLS_POLICY policy;PST_NATIVE_TRANSPORT*native;PST_BACKEND_IO_RESULT io;pst_u8*trust_der=NULL,*payload=NULL,*received=NULL;pst_size trust_size=0,payload_size,sent,total;pst_u32 accepted,operation,steps,waits=0,want_read=0,want_write=0,tls_version=0,cipher=0;PST_RESULT result,error,expected;int minimum,maximum,exchanges,index,ok=0;const char*close_mode;
if(argc!=10){fprintf(stderr,"usage: address port min-tls max-tls exchanges close-mode trust.der expected payload-size\n");return 2;}minimum=atoi(argv[3]);maximum=atoi(argv[4]);exchanges=atoi(argv[5]);close_mode=argv[6];expected=parse_result(argv[8]);payload_size=(pst_size)strtoul(argv[9],NULL,10);if((minimum!=12&&minimum!=13)||(maximum!=12&&maximum!=13)||maximum<minimum||exchanges<0||!payload_size)return 2;if(!SetEnvironmentVariableA("OPENSSL_CONF","pst-ossl-c-missing.cnf")||!SetEnvironmentVariableA("OPENSSL_MODULES","pst-ossl-c-missing-modules"))return 3;trust_der=load_file(argv[7],&trust_size);payload=(pst_u8*)malloc(payload_size);received=(pst_u8*)malloc(payload_size);if(!trust_der||!payload||!received)return 3;fill_payload(payload,payload_size);if(WSAStartup(MAKEWORD(2,2),&wd)!=0)return 3;memset(&trust_source,0,sizeof(trust_source));trust_source.struct_size=sizeof(trust_source);trust_source.api_version=PST_API_VERSION;trust_source.kind=PST_TRUST_SOURCE_CUSTOM_CA_DER;trust_source.data=trust_der;trust_source.data_size=trust_size;if(pst_trust_create(&trust_source,&trust)!=PST_RESULT_OK)goto done;if(pst_config_create(&config)!=PST_RESULT_OK)goto done;memset(&identity,0,sizeof(identity));identity.struct_size=sizeof(identity);identity.api_version=PST_API_VERSION;identity.trust=trust;identity.expected_hostname="localhost";identity.expected_hostname_size=9;identity.require_peer_authentication=1;if(pst_config_set_identity(config,&identity)!=PST_RESULT_OK)goto done;memset(&policy,0,sizeof(policy));policy.struct_size=sizeof(policy);policy.api_version=PST_API_VERSION;policy.minimum_version=minimum==12?PST_TLS_VERSION_1_2:PST_TLS_VERSION_1_3;policy.maximum_version=maximum==12?PST_TLS_VERSION_1_2:PST_TLS_VERSION_1_3;policy.early_data=PST_FEATURE_DISABLED;if(pst_config_set_tls_policy(config,&policy)!=PST_RESULT_OK||pst_config_freeze(config)!=PST_RESULT_OK)goto done;d=pst_backend_openssl_descriptor();if(d->vtable->initialize(&backend)!=PST_RESULT_OK||d->vtable->runtime_create(backend,&runtime)!=PST_RESULT_OK||d->vtable->connection_create(runtime,&connection)!=PST_RESULT_OK||d->vtable->connection_configure_identity(connection,config)!=PST_RESULT_OK)goto done;if(!connect4(argv[1],(unsigned short)atoi(argv[2]),&socket_value))goto done;owned_socket=socket_value;if(pst_win32_socket_transport_create((pst_size)socket_value,&transport)!=PST_RESULT_OK)goto done;native=(PST_NATIVE_TRANSPORT*)transport->native;accepted=0;if(d->vtable->attach_transport(connection,native,PST_OWNERSHIP_TRANSFERRED,&accepted)!=PST_RESULT_OK||!accepted)goto done;transport->destroy(transport,1);transport=NULL;socket_value=INVALID_SOCKET;printf("BACKEND=openssl OPENSSL=%lu.%lu.%lu REQUESTED_TLS_MIN=0x%04x REQUESTED_TLS_MAX=0x%04x\n",OPENSSL_version_major(),OPENSSL_version_minor(),OPENSSL_version_patch(),minimum==12?0x0303:0x0304,maximum==12?0x0303:0x0304);
for(steps=0;steps<200UL;steps++){result=d->vtable->handshake_step(connection,&operation,&error);if(result!=PST_RESULT_OK)goto done;if(operation==PST_OPERATION_NEED_READ)want_read++;else if(operation==PST_OPERATION_NEED_WRITE)want_write++;if(operation==PST_OPERATION_FAILED){printf("HANDSHAKE=FAIL RESULT=%ld STEPS=%lu WANT_READ=%lu WANT_WRITE=%lu WAITS=%lu\n",(long)error,(unsigned long)(steps+1),(unsigned long)want_read,(unsigned long)want_write,(unsigned long)waits);if(expected!=PST_RESULT_OK&&error==expected&&ERR_peek_error()==0UL){printf("EXPECTED_FAILURE=1 ERROR_QUEUE_ISOLATED=1 PASS=1\n");ok=1;}goto done;}if(operation==PST_OPERATION_COMPLETE)break;if(!wait_ready(d,connection,&waits))goto done;}if(steps==200UL||expected!=PST_RESULT_OK)goto done;if(pst_backend_openssl_connection_info(connection,&tls_version,&cipher)!=PST_RESULT_OK)goto done;printf("HANDSHAKE=PASS STEPS=%lu WANT_READ=%lu WANT_WRITE=%lu WAITS=%lu NEGOTIATED_TLS=0x%04lx CIPHER=0x%04lx\n",(unsigned long)(steps+1),(unsigned long)want_read,(unsigned long)want_write,(unsigned long)waits,(unsigned long)(tls_version==PST_TLS_VERSION_1_2?0x0303UL:0x0304UL),(unsigned long)cipher);
for(index=0;index<exchanges;index++){sent=0;while(sent<payload_size){result=d->vtable->write(connection,payload+sent,payload_size-sent,&io);if(result!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED||io.operation==PST_OPERATION_CLOSED)goto done;if(io.operation==PST_OPERATION_NEED_READ)want_read++;else if(io.operation==PST_OPERATION_NEED_WRITE)want_write++;sent+=io.bytes_transferred;if(sent<payload_size&&io.operation!=PST_OPERATION_COMPLETE&&!wait_ready(d,connection,&waits))goto done;}total=0;while(total<payload_size){result=d->vtable->read(connection,received+total,payload_size-total,&io);if(result!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED||io.operation==PST_OPERATION_CLOSED)goto done;if(io.operation==PST_OPERATION_NEED_READ)want_read++;else if(io.operation==PST_OPERATION_NEED_WRITE)want_write++;total+=io.bytes_transferred;if(total<payload_size&&io.operation!=PST_OPERATION_COMPLETE&&!wait_ready(d,connection,&waits))goto done;}if(total!=payload_size||memcmp(payload,received,payload_size))goto done;printf("EXCHANGE=%d WRITE=%lu READ=%lu CONTENT_MATCH=1\n",index+1,(unsigned long)sent,(unsigned long)total);}
if(!strcmp(close_mode,"wait-fatal")){PST_BACKEND_WAIT_RESULT wr;pst_internal_diagnostic diag;closesocket(owned_socket);owned_socket=INVALID_SOCKET;memset(&wr,0,sizeof(wr));result=d->vtable->wait(connection,PST_BACKEND_INTEREST_READ,10UL,&wr);memset(&diag,0,sizeof(diag));d->vtable->diagnostic_copy(connection,&diag);if(result!=PST_RESULT_TRANSPORT_FAILURE||!diag.valid||diag.result!=PST_RESULT_TRANSPORT_FAILURE||diag.phase!=PST_DIAGNOSTIC_PHASE_WAIT||d->vtable->handshake_step(connection,&operation,&error)!=PST_RESULT_INVALID_ARGUMENT||d->vtable->read(connection,received,1,&io)!=PST_RESULT_INVALID_STATE||d->vtable->write(connection,payload,1,&io)!=PST_RESULT_INVALID_STATE||d->vtable->shutdown_step(connection,&operation,&error)!=PST_RESULT_INVALID_ARGUMENT)goto done;printf("WAIT_FATAL RESULT=TRANSPORT_FAILURE DIAG_VALID=1 DIAG_PHASE=WAIT NO_RESURRECTION=1\n");}else if(!strcmp(close_mode,"none")){printf("SHUTDOWN=SKIPPED_INDEPENDENT_ENGINE_FIXTURE\n");}else if(!strcmp(close_mode,"client")){for(steps=0;steps<40UL;steps++){result=d->vtable->shutdown_step(connection,&operation,&error);if(result!=PST_RESULT_OK||operation==PST_OPERATION_FAILED)goto done;if(operation==PST_OPERATION_NEED_READ)want_read++;else if(operation==PST_OPERATION_NEED_WRITE)want_write++;if(operation==PST_OPERATION_COMPLETE)break;if(!wait_ready(d,connection,&waits))goto done;}if(steps==40UL)goto done;printf("SHUTDOWN=COMPLETE STEPS=%lu\n",(unsigned long)(steps+1));}else if(!strcmp(close_mode,"peer-clean")||!strcmp(close_mode,"data-then-close")||!strcmp(close_mode,"peer-abrupt")||!strcmp(close_mode,"peer-reset")){for(steps=0;steps<40UL;steps++){result=d->vtable->read(connection,received,1,&io);if(result!=PST_RESULT_OK)goto done;if(io.operation==PST_OPERATION_CLOSED||io.operation==PST_OPERATION_FAILED)break;if(!wait_ready(d,connection,&waits))goto done;}printf("PEER_TERMINAL OP=%lu CLOSE_KIND=%lu ERROR=%ld\n",(unsigned long)io.operation,(unsigned long)io.close_kind,(long)io.error);if(!strcmp(close_mode,"peer-abrupt")){if(io.operation!=PST_OPERATION_FAILED||io.close_kind!=PST_CLOSE_TRUNCATED||io.error!=PST_RESULT_TRUNCATED)goto done;printf("FINAL_STATE=FAILED CLOSE_KIND=TRUNCATED ERROR=TRUNCATED\n");}else if(!strcmp(close_mode,"peer-reset")){if(io.operation!=PST_OPERATION_FAILED||io.close_kind!=PST_CLOSE_TRUNCATED||io.error!=PST_RESULT_TRUNCATED)goto done;printf("FINAL_STATE=FAILED CLOSE_KIND=TRUNCATED ERROR=TRUNCATED RESET=1\n");}else{if(io.operation!=PST_OPERATION_CLOSED||io.close_kind!=PST_CLOSE_CLEAN)goto done;printf("FINAL_STATE=CLOSED CLOSE_KIND=CLEAN\n");}}else goto done;printf("SUMMARY TLS=0x%04lx EXCHANGES=%d PAYLOAD=%lu WANT_READ=%lu WANT_WRITE=%lu WAITS=%lu CONTENT_MATCH=1 PASS=1\n",(unsigned long)(tls_version==PST_TLS_VERSION_1_2?0x0303UL:0x0304UL),exchanges,(unsigned long)payload_size,(unsigned long)want_read,(unsigned long)want_write,(unsigned long)waits);ok=1;
done:if(connection&&d)d->vtable->connection_destroy(connection);if(runtime)d->vtable->runtime_destroy(runtime);if(backend)d->vtable->shutdown(backend);if(transport)pst_transport_release(transport);if(socket_value!=INVALID_SOCKET)closesocket(socket_value);if(config)pst_config_release(config);if(trust)pst_trust_release(trust);free(trust_der);free(payload);free(received);WSACleanup();if(!ok)fprintf(stderr,"OPENSSL_RUNTIME_INTEGRATION=FAIL\n");return ok?0:20;}