/* SPDX-License-Identifier: MPL-2.0 */
#include "papinho_secure_transport.h"
#include "pst_identity_internal.h"
#include <stdio.h>
#include <string.h>
#define CHECK(x,n) if(!(x)){printf("test_tls_policy: FAIL %d\n",n);return n;}
static void init(PST_CONNECTION_CONFIG*c){memset(c,0,sizeof(*c));c->struct_size=sizeof(*c);c->api_version=PST_API_VERSION;c->role=PST_CONNECTION_ROLE_CLIENT;c->provider_selection.struct_size=sizeof(c->provider_selection);c->provider_selection.api_version=PST_API_VERSION;c->provider_selection.mode=PST_BACKEND_SELECTION_AUTOMATIC;c->local_identity.struct_size=sizeof(c->local_identity);c->local_identity.api_version=PST_API_VERSION;c->peer_authentication.struct_size=sizeof(c->peer_authentication);c->peer_authentication.api_version=PST_API_VERSION;c->peer_authentication.certificate_mode=PST_PEER_CERTIFICATE_DISABLED;c->tls.struct_size=sizeof(c->tls);c->tls.api_version=PST_API_VERSION;c->tls.minimum_version=PST_TLS_VERSION_1_2;c->tls.maximum_version=PST_TLS_VERSION_1_3;c->alpn.struct_size=sizeof(c->alpn);c->alpn.api_version=PST_API_VERSION;c->alpn.mode=PST_FEATURE_DISABLED;}
int main(void){PST_CONNECTION_CONFIG c;PST_ALPN_PROTOCOL protocols[2];pst_connection_config_snapshot*s;const PST_CONNECTION_CONFIG*f;pst_u8 a[3]={'o','n','e'},b[3]={'t','w','o'};const pst_u8*wire;pst_size n;
 init(&c);CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_OK,1);CHECK(pst_connection_config_tls_capabilities(s)==(PST_CAP_TLS_1_2|PST_CAP_TLS_1_3),2);pst_connection_config_snapshot_release(s);
 c.tls.minimum_version=PST_TLS_VERSION_1_3;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_OK&&pst_connection_config_tls_capabilities(s)==PST_CAP_TLS_1_3,3);pst_connection_config_snapshot_release(s);
 c.tls.maximum_version=PST_TLS_VERSION_1_2;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_INVALID_ARGUMENT,4);init(&c);protocols[0].data=a;protocols[0].size=3;protocols[1].data=b;protocols[1].size=3;c.alpn.mode=PST_FEATURE_REQUIRED;c.alpn.protocols=protocols;c.alpn.protocol_count=2;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_OK,5);a[0]='x';f=pst_connection_config_snapshot_public(s);wire=pst_connection_config_alpn_wire(f,&n);CHECK(n==8&&wire[0]==3&&wire[1]=='o'&&wire[4]==3&&wire[5]=='t',6);pst_connection_config_snapshot_release(s);
 init(&c);protocols[0].data=a;protocols[0].size=3;protocols[1]=protocols[0];c.alpn.mode=PST_FEATURE_REQUIRED;c.alpn.protocols=protocols;c.alpn.protocol_count=2;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_INVALID_ARGUMENT,7);
 init(&c);c.alpn.mode=PST_FEATURE_REQUIRED;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_POLICY_VIOLATION,8);init(&c);c.tls.resumption=PST_FEATURE_DISABLED;c.tls.early_data=PST_FEATURE_OPTIONAL;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_POLICY_VIOLATION,9);init(&c);c.role=PST_CONNECTION_ROLE_INVALID;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_INVALID_ARGUMENT,10);
 init(&c);CHECK(c.server_name_indication_mode==PST_SNI_MODE_COMPAT,11);c.struct_size=PST_CONNECTION_CONFIG_V2_0_SIZE;c.server_name_indication_mode=99UL;c.server_name_indication="ignored";c.server_name_indication_size=7;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_OK,12);f=pst_connection_config_snapshot_public(s);CHECK(pst_connection_config_server_name_indication_mode(f)==PST_SNI_MODE_COMPAT&&pst_connection_config_server_name_indication(f)==NULL,13);pst_connection_config_snapshot_release(s);
 init(&c);c.server_name_indication_mode=PST_SNI_MODE_EXPLICIT;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_INVALID_ARGUMENT,14);c.server_name_indication="route.test";c.server_name_indication_size=10;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_OK&&(pst_connection_config_required_capabilities(s)&PST_CAP_SNI_CONTROL)!=0UL,15);f=pst_connection_config_snapshot_public(s);CHECK(!strcmp(pst_connection_config_server_name_indication(f),"route.test"),16);pst_connection_config_snapshot_release(s);
 init(&c);c.server_name_indication_mode=PST_SNI_MODE_DISABLED;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_OK&&(pst_connection_config_required_capabilities(s)&PST_CAP_SNI_CONTROL)==0UL,17);pst_connection_config_snapshot_release(s);init(&c);c.server_name_indication_mode=99UL;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_INVALID_ARGUMENT,18);init(&c);c.role=PST_CONNECTION_ROLE_SERVER;c.server_name_indication_mode=PST_SNI_MODE_DISABLED;CHECK(pst_connection_config_snapshot_create(&c,&s)==PST_RESULT_POLICY_VIOLATION,19);
 printf("TLS_POLICY=PASS ALPN_TRANSACTIONAL_COPY=PASS DUPLICATES_REJECTED=PASS ROLE_VALIDATION=PASS SNI_TRI_STATE=PASS SNI_COMPAT_ZERO=PASS API20_PREFIX=PASS\n");printf("test_tls_policy: PASS\n");return 0;}
