#include "papinho_secure_transport.h"
#include "papinho_secure_transport_win32.h"
#include "backends/nss/pst_backend_nss.h"
#if defined(_MSC_VER) && _MSC_VER == 1200
# pragma warning(push)
# pragma warning(disable:4115 4514)
#endif
#include <windows.h>
#include <winsock.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if defined(_MSC_VER) && _MSC_VER == 1200
# pragma warning(pop)
# pragma warning(disable:4514)
#endif
#define STEP_LIMIT 200
#define RECORD_SIZE 64
typedef struct log_counts { pst_u32 total,level[6]; } log_counts;
typedef struct maxima { int handshake,wait,read,write,shutdown; } maxima;
typedef BOOL (WINAPI *pst_get_process_handle_count_fn)(HANDLE,DWORD*);
static DWORD process_handles(void){HMODULE k;pst_get_process_handle_count_fn fn;DWORD n;n=0;k=GetModuleHandleA("kernel32.dll");if(!k)return 0;fn=(pst_get_process_handle_count_fn)GetProcAddress(k,"GetProcessHandleCount");if(fn)fn(GetCurrentProcess(),&n);return n;}static void PST_CALL sink(void *p,const PST_LOG_EVENT *e){log_counts *c=(log_counts*)p;if(c&&e&&e->level<=5){++c->total;++c->level[e->level];}}
static unsigned char *load(const char *p,pst_size *n){FILE *f;long z;unsigned char *b;*n=0;f=fopen(p,"rb");if(!f)return NULL;if(fseek(f,0,SEEK_END)||(z=ftell(f))<=0||fseek(f,0,SEEK_SET)){fclose(f);return NULL;}b=(unsigned char*)malloc((size_t)z);if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);*n=(pst_size)z;return b;}
static int connect4(const char *host,unsigned short port,SOCKET *out){struct sockaddr_in a;SOCKET s;memset(&a,0,sizeof(a));a.sin_family=AF_INET;a.sin_port=htons(port);a.sin_addr.s_addr=inet_addr(host);s=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(s==INVALID_SOCKET)return 0;if(connect(s,(struct sockaddr*)&a,sizeof(a))){closesocket(s);return 0;}*out=s;return 1;}
static int wait_one(pst_connection *c,int *count){PST_WAIT_RESULT w;++*count;return *count<STEP_LIMIT&&pst_connection_wait(c,250,&w)==PST_RESULT_OK;}
static void payload(unsigned char *p,int sequence){int i;memset(p,'A'+(sequence%26),RECORD_SIZE);sprintf((char*)p,"PST7H-%08d-",sequence);for(i=(int)strlen((char*)p);i<RECORD_SIZE;i++)p[i]=(unsigned char)('a'+((sequence+i)%26));}
static int transfer(pst_connection *c,const unsigned char *send,pst_size size,unsigned char *recv,maxima *m)
{PST_IO_RESULT io;PST_RESULT r;pst_size n;int steps,waits;n=0;steps=waits=0;while(n<size&&steps<STEP_LIMIT){++steps;memset(&io,0,sizeof(io));r=pst_connection_write(c,send+n,size-n,&io);n+=io.bytes_transferred;if(r!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED)return 0;if(n<size&&!wait_one(c,&waits))return 0;}if(steps>m->write)m->write=steps;if(waits>m->wait)m->wait=waits;if(n!=size)return 0;n=0;steps=waits=0;while(n<size&&steps<STEP_LIMIT){++steps;memset(&io,0,sizeof(io));r=pst_connection_read(c,recv+n,size-n,&io);n+=io.bytes_transferred;if(r!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED||io.operation==PST_OPERATION_CLOSED)return 0;if(n<size&&!wait_one(c,&waits))return 0;}if(steps>m->read)m->read=steps;if(waits>m->wait)m->wait=waits;return n==size&&!memcmp(send,recv,size);}
static int one_connection(pst_runtime *rt,pst_config *cfg,const char *host,unsigned short port,pst_u32 tls,int messages,maxima *m,pst_size *sent,pst_size *read)
{WSADATA wd;SOCKET s; pst_transport *tr; pst_connection *c; pst_peer_info *peer;PST_PEER_INFO_SUMMARY ps;PST_RESULT r,e;pst_u32 accepted,op;unsigned char tx[RECORD_SIZE],rx[RECORD_SIZE];int i,steps,waits,ok;
s=INVALID_SOCKET;tr=NULL;c=NULL;peer=NULL;ok=0;if(WSAStartup(MAKEWORD(2,0),&wd)||!connect4(host,port,&s))goto done;if(pst_win32_socket_transport_create((pst_size)s,&tr)!=PST_RESULT_OK)goto done;if(pst_connection_create(rt,cfg,&c)!=PST_RESULT_OK)goto done;accepted=0;if(pst_connection_attach(c,tr,PST_OWNERSHIP_TRANSFERRED,&accepted)!=PST_RESULT_OK||!accepted)goto done;tr=NULL;s=INVALID_SOCKET;steps=waits=0;for(steps=1;steps<=STEP_LIMIT;steps++){r=pst_connection_handshake(c,&op,&e);if(r!=PST_RESULT_OK||op==PST_OPERATION_FAILED)goto done;if(op==PST_OPERATION_COMPLETE)break;if(!wait_one(c,&waits))goto done;}if(steps>STEP_LIMIT)goto done;if(steps>m->handshake)m->handshake=steps;if(waits>m->wait)m->wait=waits;if(pst_connection_get_peer_info(c,&peer)!=PST_RESULT_OK)goto done;memset(&ps,0,sizeof(ps));ps.struct_size=sizeof(ps);ps.api_version=PST_API_VERSION;if(pst_peer_info_get_summary(peer,&ps)!=PST_RESULT_OK||ps.tls_version!=tls||ps.cipher_suite==0||ps.peer_authenticated!=PST_KNOWN_TRUE)goto done;
for(i=0;i<messages;i++){payload(tx,i);memset(rx,0,sizeof(rx));if(!transfer(c,tx,RECORD_SIZE,rx,m))goto done;*sent+=RECORD_SIZE;*read+=RECORD_SIZE;}
steps=waits=0;for(steps=1;steps<=STEP_LIMIT;steps++){r=pst_connection_shutdown(c,&op,&e);if(r!=PST_RESULT_OK||op==PST_OPERATION_FAILED)goto done;if(op==PST_OPERATION_COMPLETE)break;if(!wait_one(c,&waits))goto done;}if(steps>STEP_LIMIT)goto done;if(steps>m->shutdown)m->shutdown=steps;if(waits>m->wait)m->wait=waits;ok=1;
done:pst_peer_info_release(peer);pst_connection_release(c);if(tr)pst_transport_release(tr);if(s!=INVALID_SOCKET)closesocket(s);WSACleanup();return ok;}
static int prepare_connection(pst_runtime *rt,pst_config *cfg,const char *host,unsigned short port,pst_connection **out)
{WSADATA wd;SOCKET s;pst_transport *tr;pst_u32 accepted;s=INVALID_SOCKET;tr=NULL;*out=NULL;if(WSAStartup(MAKEWORD(2,0),&wd)||!connect4(host,port,&s))return 0;if(pst_win32_socket_transport_create((pst_size)s,&tr)!=PST_RESULT_OK)goto fail;if(pst_connection_create(rt,cfg,out)!=PST_RESULT_OK)goto fail;accepted=0;if(pst_connection_attach(*out,tr,PST_OWNERSHIP_TRANSFERRED,&accepted)!=PST_RESULT_OK||!accepted)goto fail;return 1;
fail:pst_connection_release(*out);*out=NULL;if(tr)pst_transport_release(tr);else if(s!=INVALID_SOCKET)closesocket(s);WSACleanup();return 0;}
static int expected_failure(pst_runtime *rt,pst_config *cfg,const char *host,unsigned short port,PST_RESULT expected,pst_u32 expected_operation,maxima *m)
{pst_connection *c;PST_RESULT r,e;PST_DIAGNOSTIC_INFO d;PST_IO_RESULT io;PST_WAIT_RESULT w;pst_u32 op;int steps,waits,ok;c=NULL;ok=0;op=PST_OPERATION_FAILED;e=PST_RESULT_BACKEND_FAILURE;if(!prepare_connection(rt,cfg,host,port,&c))return 0;steps=waits=0;for(steps=1;steps<=STEP_LIMIT;steps++){r=pst_connection_handshake(c,&op,&e);if(r!=PST_RESULT_OK||op==PST_OPERATION_FAILED)break;if(op==PST_OPERATION_COMPLETE)break;if(!wait_one(c,&waits))break;}if(steps>m->handshake)m->handshake=steps;if(waits>m->wait)m->wait=waits;memset(&d,0,sizeof(d));d.struct_size=sizeof(d);d.api_version=PST_API_VERSION;if(op==PST_OPERATION_FAILED&&e==expected&&pst_connection_copy_diagnostic(c,&d)==PST_RESULT_OK&&d.valid&&d.normalized_result==expected&&d.operation==expected_operation&&!strcmp(d.backend_id,"retrozilla-nss")&&pst_connection_handshake(c,&op,&e)==PST_RESULT_INVALID_STATE&&pst_connection_read(c,NULL,0,&io)==PST_RESULT_INVALID_STATE&&pst_connection_wait(c,1,&w)==PST_RESULT_INVALID_STATE)ok=1;pst_connection_release(c);WSACleanup();return ok;}
static int close_failure(pst_runtime *rt,pst_config *cfg,const char *host,unsigned short port,int expect_clean,maxima *m)
{pst_connection *c;PST_RESULT r,e;PST_DIAGNOSTIC_INFO d;PST_IO_RESULT io;pst_u32 op;unsigned char byte;int steps,waits,ok;c=NULL;ok=0;op=PST_OPERATION_FAILED;e=PST_RESULT_BACKEND_FAILURE;if(!prepare_connection(rt,cfg,host,port,&c))return 0;steps=waits=0;for(steps=1;steps<=STEP_LIMIT;steps++){r=pst_connection_handshake(c,&op,&e);if(r!=PST_RESULT_OK||op==PST_OPERATION_FAILED)goto done;if(op==PST_OPERATION_COMPLETE)break;if(!wait_one(c,&waits))goto done;}for(steps=1;steps<=STEP_LIMIT;steps++){memset(&io,0,sizeof(io));r=pst_connection_read(c,&byte,1,&io);if(expect_clean&&r==PST_RESULT_OK&&io.operation==PST_OPERATION_CLOSED&&io.close_kind==PST_CLOSE_CLEAN){ok=1;break;}if(!expect_clean&&io.operation==PST_OPERATION_FAILED&&io.error==PST_RESULT_TRUNCATED&&io.close_kind==PST_CLOSE_TRUNCATED){memset(&d,0,sizeof(d));d.struct_size=sizeof(d);d.api_version=PST_API_VERSION;ok=pst_connection_copy_diagnostic(c,&d)==PST_RESULT_OK&&d.valid&&d.normalized_result==PST_RESULT_TRUNCATED&&d.operation==PST_DIAGNOSTIC_OPERATION_READ;break;}if(r!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED)break;if(!wait_one(c,&waits))break;}if(steps>m->read)m->read=steps;if(waits>m->wait)m->wait=waits;
done:pst_connection_release(c);WSACleanup();return ok;}int main(int argc,char **argv)
{unsigned char *ca,*cd,*kd;pst_size ca_n,cd_n,kd_n,total_send,total_read;PST_TRUST_SOURCE ts;PST_CREDENTIAL_SOURCE cs;PST_IDENTITY_CONFIG id;PST_TLS_POLICY policy;PST_ALPN_PROTOCOL proto;PST_RUNTIME_OPTIONS ro;PST_LOG_CONFIG lc;pst_trust *trust;pst_credentials *cred;pst_config *cfg,*wrong_cfg,*tls12_cfg;pst_runtime *rt;log_counts logs;maxima max;DWORD start,batch,handles_start,handles_end;int count,messages,level,tls,i,passed;const char *mode;
if(argc!=13){fprintf(stderr,"usage: mode host port hostname ca.der client.der key.pk8 12|13 connections messages log-level alpn\n");return 2;}mode=argv[1];tls=atoi(argv[8]);count=atoi(argv[9]);messages=atoi(argv[10]);level=atoi(argv[11]);if(count<1||messages<1||level<0||level>5)return 2;
ca=load(argv[5],&ca_n);cd=load(argv[6],&cd_n);kd=load(argv[7],&kd_n);if(!ca||!cd||!kd)return 3;trust=NULL;cred=NULL;cfg=NULL;wrong_cfg=NULL;tls12_cfg=NULL;rt=NULL;memset(&logs,0,sizeof(logs));memset(&max,0,sizeof(max));
memset(&ts,0,sizeof(ts));ts.struct_size=sizeof(ts);ts.api_version=PST_API_VERSION;ts.kind=PST_TRUST_SOURCE_CUSTOM_CA_DER;ts.data=ca;ts.data_size=ca_n;if(pst_trust_create(&ts,&trust)!=PST_RESULT_OK)return 4;
memset(&cs,0,sizeof(cs));cs.struct_size=sizeof(cs);cs.api_version=PST_API_VERSION;cs.kind=PST_CREDENTIAL_SOURCE_CERT_DER_PKCS8_DER;cs.certificate_der=cd;cs.certificate_der_size=cd_n;cs.private_key_der=kd;cs.private_key_der_size=kd_n;if(pst_credentials_create(&cs,&cred)!=PST_RESULT_OK)return 5;memset(kd,0,kd_n);
if(pst_config_create(&cfg)!=PST_RESULT_OK)return 6;memset(&id,0,sizeof(id));id.struct_size=sizeof(id);id.api_version=PST_API_VERSION;id.credentials=cred;id.trust=trust;id.expected_hostname=argv[4];id.expected_hostname_size=strlen(argv[4]);id.require_peer_authentication=1;id.require_client_authentication=1;if(pst_config_set_identity(cfg,&id)!=PST_RESULT_OK)return 7;
memset(&policy,0,sizeof(policy));policy.struct_size=sizeof(policy);policy.api_version=PST_API_VERSION;policy.minimum_version=(pst_u32)tls;policy.maximum_version=(pst_u32)tls;policy.early_data=PST_FEATURE_DISABLED;policy.require_graceful_shutdown=PST_REQUIREMENT_REQUIRED;proto.data=(const pst_u8*)argv[12];proto.size=strlen(argv[12]);policy.alpn_protocols=&proto;policy.alpn_protocol_count=1;policy.alpn_requirement=PST_FEATURE_REQUIRED;if(pst_config_set_tls_policy(cfg,&policy)!=PST_RESULT_OK||pst_config_freeze(cfg)!=PST_RESULT_OK)return 8;
if(!strcmp(mode,"chain")){if(pst_config_create(&tls12_cfg)!=PST_RESULT_OK)return 8;policy.minimum_version=12;policy.maximum_version=12;if(pst_config_set_identity(tls12_cfg,&id)!=PST_RESULT_OK||pst_config_set_tls_policy(tls12_cfg,&policy)!=PST_RESULT_OK||pst_config_freeze(tls12_cfg)!=PST_RESULT_OK)return 8;policy.minimum_version=(pst_u32)tls;policy.maximum_version=(pst_u32)tls;}
if(!strcmp(mode,"mixed")){if(pst_config_create(&wrong_cfg)!=PST_RESULT_OK)return 8;id.expected_hostname="wrong.invalid";id.expected_hostname_size=13;if(pst_config_set_identity(wrong_cfg,&id)!=PST_RESULT_OK||pst_config_set_tls_policy(wrong_cfg,&policy)!=PST_RESULT_OK||pst_config_freeze(wrong_cfg)!=PST_RESULT_OK)return 8;}if(pst_win32_register_retrozilla_nss()!=PST_RESULT_OK)return 9;memset(&ro,0,sizeof(ro));ro.struct_size=sizeof(ro);ro.api_version=PST_API_VERSION;ro.selection=PST_BACKEND_SELECTION_EXACT;ro.exact_backend_id="retrozilla-nss";if(pst_log_config_init(&lc)!=PST_RESULT_OK)return 10;lc.level=(pst_u32)level;lc.callback=sink;lc.user_context=&logs;if(pst_runtime_create_with_logging(&ro,&lc,&rt,NULL)!=PST_RESULT_OK)return 11;
start=GetTickCount();batch=start;handles_start=process_handles();passed=0;total_send=total_read=0;for(i=1;i<=count;i++){int cycle_ok;if(!strcmp(mode,"chain")){int slot;slot=((i-1)%4)+1;if(slot==1)cycle_ok=one_connection(rt,tls12_cfg,argv[2],(unsigned short)atoi(argv[3]),0x0303UL,1,&max,&total_send,&total_read);else if(slot==3)cycle_ok=close_failure(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),0,&max);else cycle_ok=one_connection(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),0x0304UL,1,&max,&total_send,&total_read);}else if(!strcmp(mode,"mixed")){int slot;slot=((i-1)%8)+1;if(slot==3)cycle_ok=expected_failure(rt,wrong_cfg,argv[2],(unsigned short)atoi(argv[3]),PST_RESULT_HOSTNAME_MISMATCH,PST_DIAGNOSTIC_OPERATION_AUTHENTICATION,&max);else if(slot==5)cycle_ok=close_failure(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),0,&max);else if(slot==7)cycle_ok=expected_failure(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),PST_RESULT_POLICY_VIOLATION,PST_DIAGNOSTIC_OPERATION_CONFIGURATION,&max);else cycle_ok=one_connection(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),0x0304UL,1,&max,&total_send,&total_read);}else if(!strcmp(mode,"policy"))cycle_ok=expected_failure(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),PST_RESULT_POLICY_VIOLATION,PST_DIAGNOSTIC_OPERATION_CONFIGURATION,&max);else if(!strcmp(mode,"clean"))cycle_ok=close_failure(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),1,&max);else if(!strcmp(mode,"abrupt"))cycle_ok=close_failure(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),0,&max);else cycle_ok=one_connection(rt,cfg,argv[2],(unsigned short)atoi(argv[3]),tls==12?0x0303UL:0x0304UL,messages,&max,&total_send,&total_read);if(!cycle_ok){printf("MODE=%s ITERATION=%d STAGE=CONNECTION PASS=0\n",mode,i);break;}++passed;if(i%25==0){printf("BATCH_END=%d ELAPSED_MS=%lu HANDLES=%lu\n",i,(unsigned long)(GetTickCount()-batch),(unsigned long)process_handles());batch=GetTickCount();}}
pst_runtime_release(rt);handles_end=process_handles();pst_config_release(tls12_cfg);pst_config_release(wrong_cfg);pst_config_release(cfg);pst_credentials_release(cred);pst_trust_release(trust);free(ca);free(cd);free(kd);
printf("MODE=%s CONNECTIONS=%d PASS_COUNT=%d MESSAGES=%d BYTES_SENT=%lu BYTES_READ=%lu CONTENT_MATCH=%d LOG_EVENTS=%lu LOG_ERROR=%lu LOG_WARN=%lu LOG_INFO=%lu LOG_DEBUG=%lu LOG_TRACE=%lu MAX_HANDSHAKE_STEPS=%d MAX_READ_STEPS=%d MAX_WRITE_STEPS=%d MAX_WAIT_STEPS=%d MAX_SHUTDOWN_STEPS=%d HANDLES_START=%lu HANDLES_END=%lu TOTAL_ELAPSED_MS=%lu PASS=%d\n",mode,count,passed,count*messages,(unsigned long)total_send,(unsigned long)total_read,passed==count,(unsigned long)logs.total,(unsigned long)logs.level[1],(unsigned long)logs.level[2],(unsigned long)logs.level[3],(unsigned long)logs.level[4],(unsigned long)logs.level[5],max.handshake,max.read,max.write,max.wait,max.shutdown,(unsigned long)handles_start,(unsigned long)handles_end,(unsigned long)(GetTickCount()-start),passed==count);
return passed==count?0:20;}
