#include "pst_backend.h"
#include "pst_internal.h"
#include "pst_identity_internal.h"
#include "pst_transport_internal.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define CHECK(x) if(!(x)){printf("test_multi_backend: FAIL line %d\n",__LINE__);return 1;}
#define BASE (PST_BACKEND_CAP_NONBLOCKING|PST_BACKEND_CAP_BACKEND_WAIT)
#define CA (BASE|PST_BACKEND_CAP_TLS_1_2|PST_BACKEND_CAP_CUSTOM_TRUST|PST_BACKEND_CAP_HOSTNAME_VERIFY)
#define CB (BASE|PST_BACKEND_CAP_TLS_1_2|PST_BACKEND_CAP_TLS_1_3|PST_BACKEND_CAP_ALPN|PST_BACKEND_CAP_CUSTOM_TRUST|PST_BACKEND_CAP_HOSTNAME_VERIFY|PST_BACKEND_CAP_PEER_INFO)
#define CC (BASE|PST_BACKEND_CAP_TLS_1_3|PST_BACKEND_CAP_ALPN|PST_BACKEND_CAP_SYSTEM_TRUST|PST_BACKEND_CAP_HOSTNAME_VERIFY|PST_BACKEND_CAP_PEER_INFO)
#define CO (BASE|PST_BACKEND_CAP_TLS_1_2)
typedef struct provider{const char*id;pst_u32 caps;int pattern,singleton,active;PST_RESULT init_result,runtime_result,connection_result,handshake_result;pst_u32 close_kind;int init,shutdown,rt_create,rt_destroy,cn_create,cn_destroy,accepted,provider_close,caller_close,wrapper_destroy,waits,writes;}provider;
typedef struct state{pst_internal_diagnostic diagnostic;provider*p;int active_counted,owns,hs,sd;}state;
typedef struct transport{pst_transport base;provider*p;}transport;
typedef struct sink{const char*id;int events,wrong;}sink;
static provider a,b,c,n,o,x1,x2,x3;
static void setp(provider*p,const char*id,pst_u32 caps,int pattern){memset(p,0,sizeof(*p));p->id=id;p->caps=caps;p->pattern=pattern;p->init_result=p->runtime_result=p->connection_result=p->handshake_result=PST_RESULT_OK;}
static void reset(void){pst_backend_registry_reset();setp(&a,"mock-a",CA,1);setp(&b,"mock-b",CB,2);setp(&c,"mock-c",CC,0);setp(&n,"mock-nodiag",CA,1);setp(&o,"mock-old",CO,1);setp(&x1,"mock-x1",CA,1);setp(&x2,"mock-x2",CA,1);setp(&x3,"mock-x3",CA,1);}
static void cap(state*s,PST_RESULT r,pst_u32 phase){pst_diagnostic_capture(&s->diagnostic,r,phase,s->p->id,PST_DIAGNOSTIC_DOMAIN_NONE,0,0,0);}
static PST_RESULT initp(provider*p,void**out){state*s;++p->init;if(!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;s=(state*)calloc(1,sizeof(*s));if(!s)return PST_RESULT_OUT_OF_MEMORY;s->p=p;pst_diagnostic_initialize(&s->diagnostic);*out=s;if(p->singleton&&p->active){cap(s,PST_RESULT_UNAVAILABLE,PST_DIAGNOSTIC_PHASE_BACKEND_INITIALIZE);return PST_RESULT_UNAVAILABLE;}if(p->init_result!=PST_RESULT_OK){cap(s,p->init_result,PST_DIAGNOSTIC_PHASE_BACKEND_INITIALIZE);return p->init_result;}++p->active;s->active_counted=1;return PST_RESULT_OK;}
static PST_RESULT ia(void**v){return initp(&a,v);}static PST_RESULT ib(void**v){return initp(&b,v);}static PST_RESULT ic(void**v){return initp(&c,v);}static PST_RESULT in(void**v){return initp(&n,v);}static PST_RESULT io(void**v){return initp(&o,v);}static PST_RESULT ix1(void**v){return initp(&x1,v);}static PST_RESULT ix2(void**v){return initp(&x2,v);}static PST_RESULT ix3(void**v){return initp(&x3,v);}
static void fini(void*v){state*s=(state*)v;if(s){++s->p->shutdown;if(s->active_counted)--s->p->active;free(s);}}
static PST_RESULT rtc(void*v,void**out){state*s=(state*)v,*r;if(!s||!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;++s->p->rt_create;if(s->p->runtime_result!=PST_RESULT_OK){cap(s,s->p->runtime_result,PST_DIAGNOSTIC_PHASE_RUNTIME_CREATE);return s->p->runtime_result;}r=(state*)calloc(1,sizeof(*r));if(!r)return PST_RESULT_OUT_OF_MEMORY;r->p=s->p;pst_diagnostic_initialize(&r->diagnostic);*out=r;return PST_RESULT_OK;}
static void rtd(void*v){state*s=(state*)v;if(s){++s->p->rt_destroy;free(s);}}
static PST_RESULT query(void*v,pst_u32*q){state*s=(state*)v;if(!s||!q)return PST_RESULT_INVALID_ARGUMENT;*q=s->p->caps;return PST_RESULT_OK;}
static PST_RESULT valid(void*v,pst_u32 q){state*s=(state*)v;return s&&!(q&~s->p->caps)?PST_RESULT_OK:PST_RESULT_UNSUPPORTED;}
static PST_RESULT cnc(void*v,void**out){state*s=(state*)v,*z;if(!s||!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;++s->p->cn_create;if(s->p->connection_result!=PST_RESULT_OK){cap(s,s->p->connection_result,PST_DIAGNOSTIC_PHASE_CONNECTION_CREATE);return s->p->connection_result;}z=(state*)calloc(1,sizeof(*z));if(!z)return PST_RESULT_OUT_OF_MEMORY;z->p=s->p;pst_diagnostic_initialize(&z->diagnostic);*out=z;return PST_RESULT_OK;}
static void cnd(void*v){state*s=(state*)v;if(s){++s->p->cn_destroy;if(s->owns)++s->p->provider_close;free(s);}}
static PST_RESULT cfg(void*v,const pst_config*q){return v&&q?PST_RESULT_OK:PST_RESULT_INVALID_ARGUMENT;}
static PST_RESULT att(void*v,void*t,pst_u32 own,pst_u32*yes){state*s=(state*)v;if(!s||!t||!yes||own!=PST_BACKEND_OWNERSHIP_TRANSFERRED)return PST_RESULT_INVALID_ARGUMENT;*yes=1;s->owns=1;++s->p->accepted;return PST_RESULT_OK;}
static PST_RESULT hs(void*v,pst_u32*op,PST_RESULT*e){state*s=(state*)v;if(!s||!op||!e)return PST_RESULT_INVALID_ARGUMENT;if(s->p->handshake_result!=PST_RESULT_OK){cap(s,s->p->handshake_result,s->p->handshake_result==PST_RESULT_AUTH_FAILURE?PST_DIAGNOSTIC_PHASE_PEER_AUTHENTICATE:PST_DIAGNOSTIC_PHASE_HANDSHAKE);*op=PST_BACKEND_OPERATION_FAILED;*e=s->p->handshake_result;return PST_RESULT_OK;}if(s->p->pattern==1&&s->hs++==0){*op=PST_BACKEND_OPERATION_NEED_READ;*e=PST_RESULT_OK;return PST_RESULT_OK;}if(s->p->pattern==2){if(s->hs++==0){*op=PST_BACKEND_OPERATION_NEED_WRITE;*e=PST_RESULT_OK;return PST_RESULT_OK;}if(s->hs==2){*op=PST_BACKEND_OPERATION_NEED_READ_WRITE;*e=PST_RESULT_OK;return PST_RESULT_OK;}}*op=PST_BACKEND_OPERATION_COMPLETE;*e=PST_RESULT_OK;return PST_RESULT_OK;}
static PST_RESULT interest(void*v,pst_u32*i){state*s=(state*)v;if(!s||!i)return PST_RESULT_INVALID_ARGUMENT;*i=s->p->pattern==2?(s->hs==1?PST_BACKEND_INTEREST_WRITE:PST_BACKEND_INTEREST_READ|PST_BACKEND_INTEREST_WRITE):PST_BACKEND_INTEREST_READ;return PST_RESULT_OK;}
static PST_RESULT waitp(void*v,pst_u32 i,pst_u32 ms,PST_BACKEND_WAIT_RESULT*w){state*s=(state*)v;(void)ms;if(!s||!w)return PST_RESULT_INVALID_ARGUMENT;++s->p->waits;w->ready_interest=i;w->timed_out=0;return PST_RESULT_OK;}
static PST_RESULT readp(void*v,void*buf,pst_size z,PST_BACKEND_IO_RESULT*r){state*s=(state*)v;(void)buf;if(!s||!r)return PST_RESULT_INVALID_ARGUMENT;memset(r,0,sizeof(*r));if(s->p->close_kind==PST_BACKEND_CLOSE_CLEAN){r->operation=PST_BACKEND_OPERATION_CLOSED;r->close_kind=PST_BACKEND_CLOSE_CLEAN;}else if(s->p->close_kind==PST_BACKEND_CLOSE_TRUNCATED){cap(s,PST_RESULT_TRUNCATED,PST_DIAGNOSTIC_PHASE_READ);r->operation=PST_BACKEND_OPERATION_FAILED;r->close_kind=PST_BACKEND_CLOSE_TRUNCATED;r->error=PST_RESULT_TRUNCATED;}else{r->operation=PST_BACKEND_OPERATION_COMPLETE;r->bytes_transferred=z?1:0;}return PST_RESULT_OK;}
static PST_RESULT writep(void*v,const void*buf,pst_size z,PST_BACKEND_IO_RESULT*r){state*s=(state*)v;(void)buf;if(!s||!r)return PST_RESULT_INVALID_ARGUMENT;++s->p->writes;memset(r,0,sizeof(*r));r->bytes_transferred=z;r->operation=PST_BACKEND_OPERATION_COMPLETE;return PST_RESULT_OK;}
static PST_RESULT shut(void*v,pst_u32*op,PST_RESULT*e){state*s=(state*)v;if(!s||!op||!e)return PST_RESULT_INVALID_ARGUMENT;if(s->p->pattern==2){if(s->sd++==0){*op=PST_BACKEND_OPERATION_NEED_WRITE;*e=PST_RESULT_OK;return PST_RESULT_OK;}if(s->sd==2){*op=PST_BACKEND_OPERATION_NEED_READ;*e=PST_RESULT_OK;return PST_RESULT_OK;}}*op=PST_BACKEND_OPERATION_COMPLETE;*e=PST_RESULT_OK;return PST_RESULT_OK;}
static PST_RESULT peer(void*v,void**out){state*s=(state*)v;PST_PEER_INFO_SUMMARY q;pst_u8 der;if(!s||!out)return PST_RESULT_INVALID_ARGUMENT;memset(&q,0,sizeof(q));q.struct_size=sizeof(q);q.api_version=PST_API_VERSION;q.tls_version=s->p==&c?0x0304UL:0x0303UL;q.cipher_suite=s->p==&c?0x1302UL:0xc030UL;q.certificate_present=q.peer_authenticated=PST_KNOWN_TRUE;q.leaf_der_size=1;der=(pst_u8)s->p->id[5];return pst_peer_info_create_snapshot(&q,&der,(pst_peer_info**)out);}
static void peerd(void*v){pst_peer_info_release((pst_peer_info*)v);}
static PST_RESULT alpn(void*v,pst_u8*buf,pst_size capz,pst_size*z){state*s=(state*)v;if(!s||!z)return PST_RESULT_INVALID_ARGUMENT;*z=1;if(capz<1)return PST_RESULT_TRUNCATED;if(!buf)return PST_RESULT_INVALID_ARGUMENT;buf[0]=(pst_u8)s->p->id[5];return PST_RESULT_OK;}
static void diag(const void*v,pst_internal_diagnostic*out){const state*s=(const state*)v;if(!out)return;if(s)pst_diagnostic_copy(out,&s->diagnostic);else pst_diagnostic_initialize(out);}
static void td(pst_transport*v,int consumed){transport*t=(transport*)v;++t->p->wrapper_destroy;if(!consumed)++t->p->caller_close;free(t);}
static transport*newt(provider*p){transport*t=(transport*)calloc(1,sizeof(*t));if(t){t->p=p;t->base.backend_id=p->id;t->base.native=t;t->base.destroy=td;}return t;}
static void PST_CALL logger(void*v,const PST_LOG_EVENT*e){sink*s=(sink*)v;if(s&&e){++s->events;if(strcmp(s->id,e->backend_id))++s->wrong;}}
#define VT(init,dc) {sizeof(PST_BACKEND_VTABLE),PST_BACKEND_SPI_VERSION,init,fini,rtc,rtd,query,valid,cnc,cnd,att,hs,interest,waitp,readp,writep,shut,peer,peerd,cfg,alpn,dc}
static const PST_BACKEND_VTABLE va=VT(ia,diag),vb=VT(ib,diag),vc=VT(ic,diag),vn=VT(in,NULL),vx1=VT(ix1,diag),vx2=VT(ix2,diag),vx3=VT(ix3,diag);
static const PST_BACKEND_VTABLE vo={offsetof(PST_BACKEND_VTABLE,connection_configure_identity),PST_BACKEND_SPI_VERSION,io,fini,rtc,rtd,query,valid,cnc,cnd,att,hs,interest,waitp,readp,writep,shut,peer,peerd,NULL,NULL,NULL};
#define DESC(var,ident,title,caps,vt) static const PST_BACKEND_DESCRIPTOR var={sizeof(PST_BACKEND_DESCRIPTOR),PST_BACKEND_SPI_VERSION,ident,title,caps,vt}
DESC(da,"mock-a","mock A",CA,&va);DESC(db,"mock-b","mock B",CB,&vb);DESC(dc,"mock-c","mock C",CC,&vc);DESC(dn,"mock-nodiag","mock no diag",CA,&vn);DESC(dold,"mock-old","mock old",CO,&vo);DESC(dx1,"mock-x1","mock X1",CA,&vx1);DESC(dx2,"mock-x2","mock X2",CA,&vx2);DESC(dx3,"mock-x3","mock X3",CA,&vx3);
typedef struct future_desc{PST_BACKEND_DESCRIPTOR d;pst_u32 tail;}future_desc;
static const future_desc df={{sizeof(future_desc),PST_BACKEND_SPI_VERSION,"mock-future","future",CA,&va},0};
static void opts(PST_RUNTIME_OPTIONS*q,pst_u32 mode,const char*id,const char*const*list,pst_size count,pst_u32 caps){memset(q,0,sizeof(*q));q->struct_size=sizeof(*q);q->api_version=PST_API_VERSION;q->selection=mode;q->exact_backend_id=id;q->preferred_backend_ids=list;q->preferred_backend_count=count;q->required_capabilities=caps;}
static const char*rid(pst_runtime*r){PST_RUNTIME_INFO i;memset(&i,0,sizeof(i));i.struct_size=sizeof(i);i.api_version=PST_API_VERSION;return pst_runtime_get_info(r,&i)==PST_RESULT_OK?i.backend_id:NULL;}
static PST_RESULT mkrt(const char*id,pst_runtime**r){PST_RUNTIME_OPTIONS q;opts(&q,PST_BACKEND_SELECTION_EXACT,id,NULL,0,0);return pst_runtime_create(&q,r);}
static pst_config*mkcfg(pst_u32 ver){pst_config*q=NULL;PST_TLS_POLICY p;if(pst_config_create(&q)!=PST_RESULT_OK)return NULL;if(ver){memset(&p,0,sizeof(p));p.struct_size=sizeof(p);p.api_version=PST_API_VERSION;p.minimum_version=p.maximum_version=ver;p.early_data=PST_FEATURE_DISABLED;if(pst_config_set_tls_policy(q,&p)!=PST_RESULT_OK)return NULL;}return pst_config_freeze(q)==PST_RESULT_OK?q:NULL;}
static int establish(pst_runtime*r,pst_config*cfg,provider*p,pst_connection**cn){transport*t;pst_u32 yes=0,op;PST_RESULT e;int k;*cn=NULL;if(pst_connection_create(r,cfg,cn)!=PST_RESULT_OK)return 0;t=newt(p);if(!t)return 0;if(pst_connection_attach(*cn,&t->base,PST_OWNERSHIP_TRANSFERRED,&yes)!=PST_RESULT_OK||!yes)return 0;for(k=0;k<5;k++){PST_WAIT_RESULT w;if(pst_connection_handshake(*cn,&op,&e)!=PST_RESULT_OK||op==PST_OPERATION_FAILED)return 0;if(op==PST_OPERATION_COMPLETE)return 1;if(pst_connection_wait(*cn,1,&w)!=PST_RESULT_OK)return 0;}return 0;}
static int selection(void){PST_RUNTIME_OPTIONS q;const char*list[3];pst_runtime*r=NULL;pst_internal_operation_context ctx;pst_internal_diagnostic d;PST_BACKEND_DESCRIPTOR bad,longd;PST_BACKEND_VTABLE shortv;char longid[160];int ai;
 reset();CHECK(!pst_backend_count());CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK&&pst_backend_register(&dc)==PST_RESULT_OK);CHECK(pst_backend_register(&da)==PST_RESULT_INVALID_STATE);
 opts(&q,PST_BACKEND_SELECTION_EXACT,"mock-a",NULL,0,0);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-a"));pst_runtime_release(r);opts(&q,PST_BACKEND_SELECTION_EXACT,"missing",NULL,0,0);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_UNSUPPORTED&&!r);ai=a.init;opts(&q,PST_BACKEND_SELECTION_EXACT,"mock-a",NULL,0,PST_CAP_TLS_1_3);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_UNSUPPORTED&&!r&&a.init==ai+1&&!b.init);
 list[0]="mock-a";list[1]="mock-b";list[2]="mock-c";opts(&q,PST_BACKEND_SELECTION_ORDERED,NULL,list,3,PST_CAP_TLS_1_3|PST_CAP_ALPN);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-b"));pst_runtime_release(r);list[0]="mock-c";list[1]="mock-b";opts(&q,PST_BACKEND_SELECTION_ORDERED,NULL,list,2,PST_CAP_TLS_1_3|PST_CAP_ALPN);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-c"));pst_runtime_release(r);
 a.init_result=PST_RESULT_AUTH_FAILURE;b.init_result=PST_RESULT_PROTOCOL_FAILURE;list[0]="mock-a";list[1]="mock-b";opts(&q,PST_BACKEND_SELECTION_ORDERED,NULL,list,2,0);CHECK(pst_runtime_create_internal(&q,&r,&ctx)==PST_RESULT_UNSUPPORTED&&!r);pst_internal_operation_context_diagnostic_copy(&ctx,&d);CHECK(d.valid&&d.result==PST_RESULT_PROTOCOL_FAILURE&&!strcmp(d.backend_id,"mock-b")&&a.shutdown&&b.shutdown);
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK&&pst_backend_register(&dc)==PST_RESULT_OK);opts(&q,PST_BACKEND_SELECTION_AUTOMATIC,NULL,NULL,0,PST_CAP_TLS_1_3|PST_CAP_ALPN);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-b"));pst_runtime_release(r);reset();CHECK(pst_backend_register(&dc)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK&&pst_backend_register(&da)==PST_RESULT_OK);opts(&q,PST_BACKEND_SELECTION_AUTOMATIC,NULL,NULL,0,PST_CAP_TLS_1_3|PST_CAP_ALPN);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-c"));pst_runtime_release(r);
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK&&pst_backend_register(&dc)==PST_RESULT_OK&&pst_backend_register(&dn)==PST_RESULT_OK&&pst_backend_register(&dold)==PST_RESULT_OK&&pst_backend_register(&dx1)==PST_RESULT_OK&&pst_backend_register(&dx2)==PST_RESULT_OK&&pst_backend_register(&dx3)==PST_RESULT_OK);CHECK(pst_backend_count()==8&&pst_backend_register(&df.d)==PST_RESULT_RESOURCE_FAILURE);
 reset();CHECK(pst_backend_register(&df.d)==PST_RESULT_OK);bad=da;bad.struct_size=sizeof(bad)-1;CHECK(pst_backend_validate(&bad)==PST_RESULT_INVALID_ARGUMENT);bad=da;bad.id="";CHECK(pst_backend_validate(&bad)==PST_RESULT_INVALID_ARGUMENT);bad.id="BAD ID";CHECK(pst_backend_validate(&bad)==PST_RESULT_INVALID_ARGUMENT);memset(longid,'a',sizeof(longid));longid[sizeof(longid)-1]=0;longd=da;longd.id=longid;CHECK(pst_backend_validate(&longd)==PST_RESULT_OK);shortv=vo;shortv.struct_size=offsetof(PST_BACKEND_VTABLE,connection_configure_identity)-1;bad=da;bad.vtable=&shortv;CHECK(pst_backend_validate(&bad)==PST_RESULT_INVALID_ARGUMENT);return 0;}
static int failures(void){PST_RUNTIME_OPTIONS q;const char*list[2];pst_runtime*r=NULL;PST_DIAGNOSTIC_INFO d;pst_config*cfg;pst_connection*cn=NULL;int ai;
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK);a.init_result=PST_RESULT_AUTH_FAILURE;list[0]="mock-a";list[1]="mock-b";opts(&q,PST_BACKEND_SELECTION_ORDERED,NULL,list,2,0);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-b")&&a.shutdown==1);memset(&d,0,sizeof(d));d.struct_size=sizeof(d);d.api_version=PST_API_VERSION;CHECK(pst_runtime_copy_diagnostic(r,&d)==PST_RESULT_OK&&!d.valid);pst_runtime_release(r);
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK);a.runtime_result=PST_RESULT_BACKEND_FAILURE;list[0]="mock-a";list[1]="mock-b";opts(&q,PST_BACKEND_SELECTION_ORDERED,NULL,list,2,0);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-b")&&a.shutdown==1&&a.rt_create==1);pst_runtime_release(r);
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK);CHECK(mkrt("mock-b",&r)==PST_RESULT_OK);b.connection_result=PST_RESULT_RESOURCE_FAILURE;ai=a.init;cfg=mkcfg(12);CHECK(cfg&&pst_connection_create(r,cfg,&cn)==PST_RESULT_RESOURCE_FAILURE&&!cn&&a.init==ai&&!strcmp(rid(r),"mock-b"));pst_config_release(cfg);pst_runtime_release(r);reset();CHECK(pst_backend_register(&dn)==PST_RESULT_OK&&mkrt("mock-nodiag",&r)==PST_RESULT_OK);memset(&d,0,sizeof(d));d.struct_size=sizeof(d);d.api_version=PST_API_VERSION;CHECK(pst_runtime_copy_diagnostic(r,&d)==PST_RESULT_OK&&!d.valid);pst_runtime_release(r);return 0;}
static int isolation(void){pst_runtime*ra=NULL,*rb=NULL,*ra2=NULL,*rc=NULL;PST_RUNTIME_OPTIONS q;PST_LOG_CONFIG la,lb;sink sa,sb;pst_config*cfg;pst_connection*ca=NULL,*cb=NULL;PST_IO_RESULT wr;char z='z';
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK&&pst_backend_register(&dc)==PST_RESULT_OK);CHECK(mkrt("mock-a",&ra)==PST_RESULT_OK&&mkrt("mock-b",&rb)==PST_RESULT_OK&&mkrt("mock-c",&rc)==PST_RESULT_OK);pst_runtime_release(ra);CHECK(!b.rt_destroy&&!c.rt_destroy&&!strcmp(rid(rb),"mock-b"));pst_runtime_release(rb);pst_runtime_release(rc);
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK);CHECK(mkrt("mock-a",&ra)==PST_RESULT_OK&&mkrt("mock-a",&ra2)==PST_RESULT_OK&&a.active==2);pst_runtime_release(ra);CHECK(a.active==1&&!strcmp(rid(ra2),"mock-a"));pst_runtime_release(ra2);
 reset();a.singleton=1;CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK);CHECK(mkrt("mock-a",&ra)==PST_RESULT_OK&&mkrt("mock-b",&rb)==PST_RESULT_OK&&mkrt("mock-a",&ra2)==PST_RESULT_UNSUPPORTED&&!ra2);pst_runtime_release(ra);CHECK(mkrt("mock-a",&ra2)==PST_RESULT_OK&&!strcmp(rid(rb),"mock-b"));pst_runtime_release(ra2);pst_runtime_release(rb);
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK);memset(&sa,0,sizeof(sa));memset(&sb,0,sizeof(sb));sa.id="mock-a";sb.id="mock-b";pst_log_config_init(&la);pst_log_config_init(&lb);la.level=lb.level=PST_LOG_LEVEL_TRACE;la.callback=lb.callback=logger;la.user_context=&sa;lb.user_context=&sb;opts(&q,PST_BACKEND_SELECTION_EXACT,"mock-a",NULL,0,0);CHECK(pst_runtime_create_with_logging(&q,&la,&ra,NULL)==PST_RESULT_OK);opts(&q,PST_BACKEND_SELECTION_EXACT,"mock-b",NULL,0,0);CHECK(pst_runtime_create_with_logging(&q,&lb,&rb,NULL)==PST_RESULT_OK);cfg=mkcfg(12);CHECK(cfg&&establish(ra,cfg,&a,&ca)&&establish(rb,cfg,&b,&cb));pst_connection_release(ca);pst_runtime_release(ra);CHECK(!sa.wrong&&!sb.wrong&&pst_connection_write(cb,&z,1,&wr)==PST_RESULT_OK&&wr.bytes_transferred==1);pst_connection_release(cb);pst_runtime_release(rb);pst_config_release(cfg);CHECK(a.provider_close==1&&b.provider_close==1&&sa.events&&sb.events);return 0;}
static int diagnostic_isolation(void){pst_runtime*ra=NULL,*rb=NULL;pst_config*cfg;pst_connection*ca=NULL,*cb=NULL;transport*ta,*tb;pst_u32 yes,op;PST_RESULT e;PST_DIAGNOSTIC_INFO daz,dbz,saved;reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK&&mkrt("mock-a",&ra)==PST_RESULT_OK&&mkrt("mock-b",&rb)==PST_RESULT_OK);cfg=mkcfg(12);CHECK(cfg&&pst_connection_create(ra,cfg,&ca)==PST_RESULT_OK&&pst_connection_create(rb,cfg,&cb)==PST_RESULT_OK);ta=newt(&a);tb=newt(&b);yes=0;CHECK(ta&&pst_connection_attach(ca,&ta->base,PST_OWNERSHIP_TRANSFERRED,&yes)==PST_RESULT_OK&&yes);yes=0;CHECK(tb&&pst_connection_attach(cb,&tb->base,PST_OWNERSHIP_TRANSFERRED,&yes)==PST_RESULT_OK&&yes);a.handshake_result=PST_RESULT_AUTH_FAILURE;b.handshake_result=PST_RESULT_PROTOCOL_FAILURE;CHECK(pst_connection_handshake(ca,&op,&e)==PST_RESULT_OK&&op==PST_OPERATION_FAILED&&e==PST_RESULT_AUTH_FAILURE);CHECK(pst_connection_handshake(cb,&op,&e)==PST_RESULT_OK&&op==PST_OPERATION_FAILED&&e==PST_RESULT_PROTOCOL_FAILURE);pst_diagnostic_info_init(&daz);pst_diagnostic_info_init(&dbz);CHECK(pst_connection_copy_diagnostic(ca,&daz)==PST_RESULT_OK&&daz.valid&&daz.normalized_result==PST_RESULT_AUTH_FAILURE&&!strcmp(daz.backend_id,"mock-a"));CHECK(pst_connection_copy_diagnostic(cb,&dbz)==PST_RESULT_OK&&dbz.valid&&dbz.normalized_result==PST_RESULT_PROTOCOL_FAILURE&&!strcmp(dbz.backend_id,"mock-b"));saved=dbz;pst_connection_release(ca);pst_runtime_release(ra);pst_diagnostic_info_init(&dbz);CHECK(pst_connection_copy_diagnostic(cb,&dbz)==PST_RESULT_OK&&dbz.normalized_result==saved.normalized_result&&!strcmp(dbz.backend_id,saved.backend_id));pst_connection_release(cb);pst_runtime_release(rb);pst_config_release(cfg);return 0;}
static int operations(void){pst_runtime*ra=NULL,*rb=NULL,*rc=NULL,*ro=NULL;pst_config*cfg,*cfgc;pst_connection*ca=NULL,*cb=NULL,*cc=NULL,*co=NULL;PST_WAIT_RESULT w;PST_IO_RESULT ioresult;PST_RESULT e;pst_u32 op,yes;pst_peer_info*pi;PST_PEER_INFO_SUMMARY sum;pst_size z;transport*t;char byte=0;
 reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK&&pst_backend_register(&db)==PST_RESULT_OK&&pst_backend_register(&dc)==PST_RESULT_OK&&pst_backend_register(&dold)==PST_RESULT_OK);CHECK(mkrt("mock-a",&ra)==PST_RESULT_OK&&mkrt("mock-b",&rb)==PST_RESULT_OK);cfg=mkcfg(12);CHECK(cfg&&establish(ra,cfg,&a,&ca)&&establish(rb,cfg,&b,&cb)&&a.waits==1&&b.waits==2);CHECK(pst_connection_shutdown(ca,&op,&e)==PST_RESULT_OK&&op==PST_OPERATION_COMPLETE);CHECK(pst_connection_shutdown(cb,&op,&e)==PST_RESULT_OK&&op==PST_OPERATION_NEED_WRITE&&pst_connection_wait(cb,1,&w)==PST_RESULT_OK&&pst_connection_shutdown(cb,&op,&e)==PST_RESULT_OK&&op==PST_OPERATION_NEED_READ&&pst_connection_wait(cb,1,&w)==PST_RESULT_OK&&pst_connection_shutdown(cb,&op,&e)==PST_RESULT_OK&&op==PST_OPERATION_COMPLETE);pst_connection_release(ca);pst_connection_release(cb);pst_runtime_release(ra);pst_runtime_release(rb);
 CHECK(mkrt("mock-a",&ra)==PST_RESULT_OK&&pst_connection_create(ra,cfg,&ca)==PST_RESULT_OK);t=newt(&b);yes=9;CHECK(t&&pst_connection_attach(ca,&t->base,PST_OWNERSHIP_TRANSFERRED,&yes)==PST_RESULT_UNSUPPORTED&&!yes);pst_transport_release(&t->base);pst_connection_release(ca);pst_runtime_release(ra);CHECK(b.caller_close==1);
 a.close_kind=PST_BACKEND_CLOSE_CLEAN;b.close_kind=PST_BACKEND_CLOSE_TRUNCATED;CHECK(mkrt("mock-a",&ra)==PST_RESULT_OK&&mkrt("mock-b",&rb)==PST_RESULT_OK&&establish(ra,cfg,&a,&ca)&&establish(rb,cfg,&b,&cb));CHECK(pst_connection_read(ca,&byte,1,&ioresult)==PST_RESULT_OK&&ioresult.operation==PST_OPERATION_CLOSED&&ioresult.close_kind==PST_CLOSE_CLEAN);CHECK(pst_connection_read(cb,&byte,1,&ioresult)==PST_RESULT_OK&&ioresult.operation==PST_OPERATION_FAILED&&ioresult.error==PST_RESULT_TRUNCATED&&ioresult.close_kind==PST_CLOSE_TRUNCATED);pst_connection_release(ca);pst_connection_release(cb);pst_runtime_release(ra);pst_runtime_release(rb);
 b.close_kind=0;CHECK(mkrt("mock-b",&rb)==PST_RESULT_OK&&establish(rb,cfg,&b,&cb));CHECK(pst_connection_get_peer_info(cb,&pi)==PST_RESULT_OK);memset(&sum,0,sizeof(sum));sum.struct_size=sizeof(sum);sum.api_version=PST_API_VERSION;CHECK(pst_peer_info_get_summary(pi,&sum)==PST_RESULT_OK&&sum.tls_version==0x0303UL&&sum.cipher_suite==0xc030UL);pst_peer_info_release(pi);pst_connection_release(cb);pst_runtime_release(rb);cfgc=mkcfg(13);CHECK(cfgc&&mkrt("mock-c",&rc)==PST_RESULT_OK&&establish(rc,cfgc,&c,&cc));CHECK(pst_connection_get_peer_info(cc,&pi)==PST_RESULT_OK);memset(&sum,0,sizeof(sum));sum.struct_size=sizeof(sum);sum.api_version=PST_API_VERSION;CHECK(pst_peer_info_get_summary(pi,&sum)==PST_RESULT_OK&&sum.tls_version==0x0304UL&&sum.cipher_suite==0x1302UL);pst_peer_info_release(pi);pst_connection_release(cc);pst_runtime_release(rc);pst_config_release(cfgc);
 CHECK(mkrt("mock-old",&ro)==PST_RESULT_OK&&pst_connection_create(ro,cfg,&co)==PST_RESULT_OK);t=newt(&o);yes=0;CHECK(t&&pst_connection_attach(co,&t->base,PST_OWNERSHIP_TRANSFERRED,&yes)==PST_RESULT_OK&&yes);CHECK(pst_connection_handshake(co,&op,&e)==PST_RESULT_OK);if(op!=PST_OPERATION_COMPLETE)CHECK(pst_connection_wait(co,1,&w)==PST_RESULT_OK&&pst_connection_handshake(co,&op,&e)==PST_RESULT_OK&&op==PST_OPERATION_COMPLETE);pi=(pst_peer_info*)1;CHECK(pst_connection_get_peer_info(co,&pi)==PST_RESULT_UNSUPPORTED&&!pi);z=99;CHECK(pst_connection_get_negotiated_alpn(co,NULL,0,&z)==PST_RESULT_UNSUPPORTED&&!z);pst_connection_release(co);pst_runtime_release(ro);pst_config_release(cfg);return 0;}
static int availability(void){PST_RUNTIME_OPTIONS q;pst_runtime*r=NULL;reset();CHECK(pst_backend_register(&da)==PST_RESULT_OK);opts(&q,PST_BACKEND_SELECTION_EXACT,"mock-b",NULL,0,0);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_UNSUPPORTED&&!r);opts(&q,PST_BACKEND_SELECTION_AUTOMATIC,NULL,NULL,0,0);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-a"));pst_runtime_release(r);reset();CHECK(pst_backend_register(&dc)==PST_RESULT_OK);opts(&q,PST_BACKEND_SELECTION_AUTOMATIC,NULL,NULL,0,PST_CAP_TLS_1_3);CHECK(pst_runtime_create(&q,&r)==PST_RESULT_OK&&!strcmp(rid(r),"mock-c"));pst_runtime_release(r);return 0;}
int main(void){CHECK(selection()==0);CHECK(failures()==0);CHECK(isolation()==0);CHECK(diagnostic_isolation()==0);CHECK(operations()==0);CHECK(availability()==0);pst_backend_registry_reset();printf("MULTI_BACKEND=A_B_C EXACT=PASS ORDERED=PASS AUTOMATIC=REGISTRATION_ORDER SIMULTANEOUS=PASS SINGLETON_LOCAL=PASS ISOLATION=PASS OPTIONAL_HOOKS=PASS\n");printf("test_multi_backend: PASS\n");return 0;}

