/* SPDX-License-Identifier: MPL-2.0 */
#include "papinho_secure_transport.h"
#include "pst_backend.h"
#include "pst_transport_internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define CHECK(x,n) if(!(x)){printf("test_backend_spi: FAIL %d\n",n);return n;}
typedef struct state { int accepted,destroyed,step; } state;
static state counters;
static PST_RESULT init(void **o){*o=&counters;return PST_RESULT_OK;}static void fini(void*v){(void)v;}static PST_RESULT rt(void*v,void**o){*o=v;return PST_RESULT_OK;}static void rt_free(void*v){(void)v;}static PST_RESULT caps(void*v,pst_u32*c){(void)v;*c=PST_CAP_ROLE_CLIENT|PST_CAP_TLS_1_2|PST_CAP_NONBLOCKING|PST_CAP_BACKEND_WAIT;return PST_RESULT_OK;}static PST_RESULT valid(void*v,pst_u32 c){(void)v;return c&~(PST_CAP_ROLE_CLIENT|PST_CAP_TLS_1_2|PST_CAP_NONBLOCKING|PST_CAP_BACKEND_WAIT)?PST_RESULT_UNSUPPORTED:PST_RESULT_OK;}
static PST_RESULT create(void*v,const PST_BACKEND_CONNECTION_OPTIONS*o,void**out){state*s;if(!v||!o||!out||o->role!=PST_CONNECTION_ROLE_CLIENT)return PST_RESULT_INVALID_ARGUMENT;s=(state*)calloc(1,sizeof(*s));if(!s)return PST_RESULT_OUT_OF_MEMORY;*out=s;return PST_RESULT_OK;}static void destroy(void*v){state*s=(state*)v;if(s){counters.destroyed++;free(s);}}
static PST_RESULT attach(void*v,void*t,pst_u32 own,pst_u32*a){state*s=(state*)v;(void)t;if(!s||!a)return PST_RESULT_INVALID_ARGUMENT;*a=0;if(own!=PST_OWNERSHIP_TRANSFERRED)return PST_RESULT_UNSUPPORTED;*a=1;s->accepted=1;counters.accepted++;return PST_RESULT_OK;}
static PST_RESULT step(void*v,pst_u32*o,PST_RESULT*e){state*s=(state*)v;if(!s||!o||!e)return PST_RESULT_INVALID_ARGUMENT;s->step++;*o=s->step==1?PST_OPERATION_NEED_READ:PST_OPERATION_COMPLETE;*e=PST_RESULT_OK;return PST_RESULT_OK;}static PST_RESULT interest(void*v,pst_u32*i){if(!v||!i)return PST_RESULT_INVALID_ARGUMENT;*i=PST_INTEREST_READ;return PST_RESULT_OK;}static PST_RESULT wait_fn(void*v,pst_u32 i,pst_u32 t,PST_BACKEND_WAIT_RESULT*r){(void)t;if(!v||!r)return PST_RESULT_INVALID_ARGUMENT;r->ready_interest=i;r->timed_out=0;return PST_RESULT_OK;}static PST_RESULT io(void*v,void*b,pst_size n,PST_BACKEND_IO_RESULT*r){(void)b;(void)n;if(!v||!r)return PST_RESULT_INVALID_ARGUMENT;memset(r,0,sizeof(*r));r->operation=PST_OPERATION_COMPLETE;return PST_RESULT_OK;}static PST_RESULT write_fn(void*v,const void*b,pst_size n,PST_BACKEND_IO_RESULT*r){return io(v,(void*)b,n,r);}
static const PST_BACKEND_VTABLE vt={sizeof(PST_BACKEND_VTABLE),PST_BACKEND_SPI_VERSION,init,fini,rt,rt_free,caps,valid,create,destroy,attach,step,interest,wait_fn,io,write_fn,step,NULL,NULL,NULL,NULL};
static const PST_BACKEND_DESCRIPTOR descriptor={sizeof(PST_BACKEND_DESCRIPTOR),PST_BACKEND_SPI_VERSION,"spi3-mock","SPI 3 mock",PST_CAP_ROLE_CLIENT|PST_CAP_TLS_1_2|PST_CAP_NONBLOCKING|PST_CAP_BACKEND_WAIT,&vt,NULL};
static void transport_destroy(pst_transport*t,int close_native){if(close_native)counters.destroyed++;(void)t;}
static void config(PST_CONNECTION_CONFIG*c){memset(c,0,sizeof(*c));c->struct_size=sizeof(*c);c->api_version=PST_API_VERSION;c->role=PST_CONNECTION_ROLE_CLIENT;c->provider_selection.struct_size=sizeof(c->provider_selection);c->provider_selection.api_version=PST_API_VERSION;c->provider_selection.mode=PST_BACKEND_SELECTION_EXACT;c->provider_selection.exact_provider_id="spi3-mock";c->local_identity.struct_size=sizeof(c->local_identity);c->local_identity.api_version=PST_API_VERSION;c->peer_authentication.struct_size=sizeof(c->peer_authentication);c->peer_authentication.api_version=PST_API_VERSION;c->tls.struct_size=sizeof(c->tls);c->tls.api_version=PST_API_VERSION;c->tls.minimum_version=c->tls.maximum_version=PST_TLS_VERSION_1_2;c->alpn.struct_size=sizeof(c->alpn);c->alpn.api_version=PST_API_VERSION;}
int main(void){PST_RUNTIME_OPTIONS ro;PST_CONNECTION_CONFIG cc;PST_BACKEND_DESCRIPTOR bad;PST_WAIT_RESULT wr;pst_runtime*r;pst_connection*c;pst_transport t;pst_u32 accepted,op;PST_RESULT error;char native=0;
 bad=descriptor;bad.spi_version=0x00020000UL;CHECK(pst_backend_validate(&bad)==PST_RESULT_INCOMPATIBLE_API,1);pst_backend_registry_reset();CHECK(pst_backend_register(&descriptor)==PST_RESULT_OK,2);memset(&ro,0,sizeof(ro));ro.struct_size=sizeof(ro);ro.api_version=PST_API_VERSION;CHECK(pst_runtime_create(&ro,&r)==PST_RESULT_OK,3);config(&cc);CHECK(pst_connection_create(r,&cc,&c)==PST_RESULT_OK,4);memset(&t,0,sizeof(t));t.backend_id="spi3-mock";t.native=&native;t.destroy=transport_destroy;accepted=0;CHECK(pst_connection_attach(c,&t,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_OK&&accepted,5);CHECK(pst_connection_handshake(c,&op,&error)==PST_RESULT_OK&&op==PST_OPERATION_NEED_READ,6);CHECK(pst_connection_wait(c,10,&wr)==PST_RESULT_OK&&wr.ready_interest==PST_INTEREST_READ,7);CHECK(pst_connection_handshake(c,&op,&error)==PST_RESULT_OK&&op==PST_OPERATION_COMPLETE,8);pst_connection_release(c);pst_runtime_release(r);CHECK(counters.accepted==1&&counters.destroyed==2,9);pst_backend_registry_reset();printf("SPI3=PASS OWNERSHIP_ACCEPTED=PASS READINESS=PASS PROVIDER_PINNING=PASS\n");printf("test_backend_spi: PASS\n");return 0;}
