#include "papinho_secure_transport.h"
#include "papinho_secure_transport_win32.h"
#include "backends/openssl/pst_backend_openssl.h"
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#include <winsock2.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct integration_log_sink { pst_u32 total,error,warn,trace; } integration_log_sink;
static void PST_CALL integration_log(void *context,const PST_LOG_EVENT *event){integration_log_sink*s=(integration_log_sink*)context;s->total++;if(event->level==PST_LOG_LEVEL_ERROR)s->error++;if(event->level==PST_LOG_LEVEL_WARN)s->warn++;if(event->level==PST_LOG_LEVEL_TRACE)s->trace++;}

static unsigned char *load_file(const char *path,pst_size *size){FILE*f;long n;unsigned char*p;*size=0;if(!path||!strcmp(path,"-"))return NULL;f=fopen(path,"rb");if(!f)return NULL;if(fseek(f,0,SEEK_END)||((n=ftell(f))<0)||fseek(f,0,SEEK_SET)){fclose(f);return NULL;}p=(unsigned char*)malloc((size_t)n);if(!p){fclose(f);return NULL;}if(n&&fread(p,1,(size_t)n,f)!=(size_t)n){free(p);fclose(f);return NULL;}fclose(f);*size=(pst_size)n;return p;}
static int connect4(const char *address,unsigned short port,SOCKET *out){SOCKET s;struct sockaddr_in a;memset(&a,0,sizeof(a));a.sin_family=AF_INET;a.sin_port=htons(port);a.sin_addr.s_addr=inet_addr(address);s=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(s==INVALID_SOCKET)return 0;if(connect(s,(struct sockaddr*)&a,sizeof(a))==SOCKET_ERROR){closesocket(s);return 0;}*out=s;return 1;}
static int wait_step(pst_connection*c){PST_WAIT_RESULT w;PST_RESULT r;memset(&w,0,sizeof(w));r=pst_connection_wait(c,1000,&w);return r==PST_RESULT_OK&&!w.timed_out&&w.ready_interest!=0;}
static PST_RESULT expected_result(const char*s){if(!strcmp(s,"OK"))return PST_RESULT_OK;if(!strcmp(s,"AUTH"))return PST_RESULT_AUTH_FAILURE;if(!strcmp(s,"HOSTNAME"))return PST_RESULT_HOSTNAME_MISMATCH;if(!strcmp(s,"POLICY"))return PST_RESULT_POLICY_VIOLATION;return PST_RESULT_BACKEND_FAILURE;}
static int split_alpn(char*text,PST_ALPN_PROTOCOL*items,pst_size*count){char*p,*comma;p=text;*count=0;if(!strcmp(text,"-"))return 1;while(*p&&*count<4){comma=strchr(p,',');if(comma)*comma='\0';items[*count].data=(const pst_u8*)p;items[*count].size=strlen(p);if(!items[*count].size||items[*count].size>255)return 0;(*count)++;if(!comma)return 1;p=comma+1;}return *p=='\0';}
int main(int argc,char**argv){const char payload[]="pst-phase5-public-runtime";WSADATA wd;SOCKET socket_value=INVALID_SOCKET;pst_credentials*credentials=NULL;pst_trust*trust=NULL;pst_config*config=NULL;pst_runtime*runtime=NULL;pst_connection*connection=NULL;pst_transport*transport=NULL;pst_peer_info*peer=NULL;PST_CREDENTIAL_SOURCE credential_source;PST_TRUST_SOURCE trust_source;PST_IDENTITY_CONFIG identity;PST_TLS_POLICY policy;PST_RUNTIME_OPTIONS options;PST_RUNTIME_INFO info;PST_LOG_CONFIG logging;integration_log_sink log_sink;PST_DIAGNOSTIC_INFO diagnostic;PST_IO_RESULT io;PST_PEER_INFO_SUMMARY summary;PST_ALPN_PROTOCOL alpn[4];pst_u8 alpn_value[256];pst_u8*trust_der=NULL,*cert_der=NULL,*key_der=NULL,*leaf_der=NULL;pst_size trust_size=0,cert_size=0,key_size=0,leaf_size=0,alpn_count=0,alpn_size=0,required_size=0;pst_u32 accepted,operation;PST_RESULT error,result,want;char alpn_text[1024];char buffer[sizeof(payload)];int version,exchanges,i,steps,ok=0;const char*close_mode;int custom,alpn_required,log_level=-1,no_resurrection;
    if(argc!=14&&argc!=15){fprintf(stderr,"usage: address port hostname tls exchanges close trust-kind trust-der alpn-mode alpn-list cert-der key-der expected [log-level]\n");return 2;}version=atoi(argv[4]);exchanges=atoi(argv[5]);close_mode=argv[6];custom=!strcmp(argv[7],"custom");alpn_required=!strcmp(argv[9],"required");want=expected_result(argv[13]);if(argc==15)log_level=atoi(argv[14]);memset(&log_sink,0,sizeof(log_sink));if((version!=12&&version!=13)||exchanges<0||strlen(argv[10])>=sizeof(alpn_text))return 2;strcpy(alpn_text,argv[10]);if(!split_alpn(alpn_text,alpn,&alpn_count))return 2;
    if(custom){trust_der=load_file(argv[8],&trust_size);if(!trust_der)return 3;}if(strcmp(argv[11],"-")||strcmp(argv[12],"-")){cert_der=load_file(argv[11],&cert_size);key_der=load_file(argv[12],&key_size);if(!cert_der||!key_der)return 3;}
    if(WSAStartup(MAKEWORD(2,2),&wd)!=0)return 3;memset(&trust_source,0,sizeof(trust_source));trust_source.struct_size=sizeof(trust_source);trust_source.api_version=PST_API_VERSION;trust_source.kind=custom?PST_TRUST_SOURCE_CUSTOM_CA_DER:PST_TRUST_SOURCE_SYSTEM;trust_source.data=trust_der;trust_source.data_size=trust_size;if(pst_trust_create(&trust_source,&trust)!=PST_RESULT_OK)goto done;
    if(cert_der){memset(&credential_source,0,sizeof(credential_source));credential_source.struct_size=sizeof(credential_source);credential_source.api_version=PST_API_VERSION;credential_source.kind=PST_CREDENTIAL_SOURCE_CERT_DER_PKCS8_DER;credential_source.certificate_der=cert_der;credential_source.certificate_der_size=cert_size;credential_source.private_key_der=key_der;credential_source.private_key_der_size=key_size;if(pst_credentials_create(&credential_source,&credentials)!=PST_RESULT_OK)goto done;}
    if(pst_config_create(&config)!=PST_RESULT_OK)goto done;memset(&identity,0,sizeof(identity));identity.struct_size=sizeof(identity);identity.api_version=PST_API_VERSION;identity.credentials=credentials;identity.trust=trust;identity.expected_hostname=argv[3];identity.expected_hostname_size=strlen(argv[3]);identity.require_peer_authentication=1;identity.require_client_authentication=credentials?1:0;if(pst_config_set_identity(config,&identity)!=PST_RESULT_OK)goto done;memset(&policy,0,sizeof(policy));policy.struct_size=sizeof(policy);policy.api_version=PST_API_VERSION;policy.minimum_version=(pst_u32)version;policy.maximum_version=(pst_u32)version;policy.alpn_protocols=alpn_count?alpn:NULL;policy.alpn_protocol_count=alpn_count;policy.alpn_requirement=alpn_count?(alpn_required?PST_FEATURE_REQUIRED:PST_FEATURE_OPTIONAL):PST_FEATURE_DISABLED;policy.early_data=PST_FEATURE_DISABLED;if(pst_config_set_tls_policy(config,&policy)!=PST_RESULT_OK||pst_config_freeze(config)!=PST_RESULT_OK)goto done;
    if(pst_backend_openssl_register()!=PST_RESULT_OK)goto done;memset(&options,0,sizeof(options));options.struct_size=sizeof(options);options.api_version=PST_API_VERSION;options.selection=PST_BACKEND_SELECTION_EXACT;options.exact_backend_id="openssl";options.required_capabilities=(version==13?PST_CAP_TLS_1_3:PST_CAP_TLS_1_2)|(custom?PST_CAP_CUSTOM_TRUST:PST_CAP_SYSTEM_TRUST)|(alpn_count?PST_CAP_ALPN:0)|(credentials?PST_CAP_CLIENT_AUTH:0);if(log_level>=0){if(pst_log_config_init(&logging)!=PST_RESULT_OK)goto done;logging.level=(pst_u32)log_level;logging.callback=integration_log;logging.user_context=&log_sink;if(pst_runtime_create_with_logging(&options,&logging,&runtime,NULL)!=PST_RESULT_OK)goto done;}else if(pst_runtime_create(&options,&runtime)!=PST_RESULT_OK)goto done;memset(&info,0,sizeof(info));info.struct_size=sizeof(info);info.api_version=PST_API_VERSION;if(pst_runtime_get_info(runtime,&info)!=PST_RESULT_OK)goto done;printf("BACKEND=%s CAPABILITIES=0x%08lx TRUST=%s ALPN=%s CLIENT_CERT=%d\n",info.backend_id,(unsigned long)info.capabilities,custom?"CUSTOM":"SYSTEM",argv[10],credentials?1:0);
    if(!connect4(argv[1],(unsigned short)atoi(argv[2]),&socket_value))goto done;if(pst_win32_socket_transport_create((pst_size)socket_value,&transport)!=PST_RESULT_OK)goto done;{PST_DIAGNOSTIC_INFO d;memset(&d,0,sizeof(d));d.struct_size=sizeof(d);d.api_version=PST_API_VERSION;result=pst_connection_create_ex(runtime,config,&connection,&d);if(result!=PST_RESULT_OK){printf("CONNECTION_CREATE RESULT=%ld DIAG_VALID=%lu DIAG_RESULT=%ld OPERATION=%lu BACKEND=%s\n",(long)result,(unsigned long)d.valid,(long)d.normalized_result,(unsigned long)d.operation,d.backend_id);if(want!=PST_RESULT_OK&&result==want&&d.valid&&d.normalized_result==want&&!strcmp(d.backend_id,"openssl")){printf("EXPECTED_LOCAL_FAILURE RESULT=%ld PASS=1\n",(long)result);ok=1;}goto done;}}accepted=0;if(pst_connection_attach(connection,transport,PST_OWNERSHIP_TRANSFERRED,&accepted)!=PST_RESULT_OK||!accepted)goto done;transport=NULL;socket_value=INVALID_SOCKET;
    for(steps=0;steps<200;steps++){result=pst_connection_handshake(connection,&operation,&error);printf("HANDSHAKE_STEP=%d RESULT=%ld OP=%lu ERROR=%ld\n",steps+1,(long)result,(unsigned long)operation,(long)error);if(result!=PST_RESULT_OK)goto done;if(operation==PST_OPERATION_FAILED){memset(&diagnostic,0,sizeof(diagnostic));diagnostic.struct_size=sizeof(diagnostic);diagnostic.api_version=PST_API_VERSION;result=pst_connection_copy_diagnostic(connection,&diagnostic);no_resurrection=pst_connection_handshake(connection,&operation,&error)==PST_RESULT_INVALID_STATE&&pst_connection_read(connection,buffer,1,&io)==PST_RESULT_INVALID_STATE&&pst_connection_write(connection,payload,1,&io)==PST_RESULT_INVALID_STATE;if(error==want&&want!=PST_RESULT_OK&&result==PST_RESULT_OK&&diagnostic.valid&&diagnostic.normalized_result==want&&!strcmp(diagnostic.backend_id,"openssl")&&no_resurrection){printf("EXPECTED_FAILURE RESULT=%ld DIAG_RESULT=%ld DIAG_BACKEND=%s NO_RESURRECTION=1 PASS=1\n",(long)error,(long)diagnostic.normalized_result,diagnostic.backend_id);ok=1;}printf("LOG_LEVEL=%d LOG_EVENTS=%lu LOG_ERROR=%lu LOG_WARN=%lu LOG_TRACE=%lu\n",log_level,(unsigned long)log_sink.total,(unsigned long)log_sink.error,(unsigned long)log_sink.warn,(unsigned long)log_sink.trace);goto done;}if(operation==PST_OPERATION_COMPLETE)break;if(!wait_step(connection))goto done;}if(steps==200||want!=PST_RESULT_OK)goto done;
    for(i=0;i<exchanges;i++){pst_size sent=0,received=0;while(sent<sizeof(payload)-1){memset(&io,0,sizeof(io));result=pst_connection_write(connection,payload+sent,sizeof(payload)-1-sent,&io);if(result!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED)goto done;sent+=io.bytes_transferred;if(sent<sizeof(payload)-1&&io.operation!=PST_OPERATION_COMPLETE&&!wait_step(connection))goto done;}while(received<sizeof(payload)-1){memset(&io,0,sizeof(io));result=pst_connection_read(connection,buffer+received,sizeof(payload)-1-received,&io);if(result!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED||io.operation==PST_OPERATION_CLOSED)goto done;received+=io.bytes_transferred;if(received<sizeof(payload)-1&&io.operation!=PST_OPERATION_COMPLETE&&!wait_step(connection))goto done;}if(received!=sizeof(payload)-1||memcmp(buffer,payload,sizeof(payload)-1))goto done;printf("EXCHANGE=%d WRITE=%lu READ=%lu CONTENT_MATCH=1\n",i+1,(unsigned long)sent,(unsigned long)received);}
    if(alpn_count){result=pst_connection_get_negotiated_alpn(connection,alpn_value,sizeof(alpn_value),&alpn_size);if(result==PST_RESULT_OK)printf("ALPN_NEGOTIATED=%.*s SIZE=%lu\n",(int)alpn_size,alpn_value,(unsigned long)alpn_size);else if(result==PST_RESULT_UNAVAILABLE)printf("ALPN_NEGOTIATED=NONE\n");else goto done;}
    if(pst_connection_get_peer_info(connection,&peer)!=PST_RESULT_OK)goto done;
    if(!strcmp(close_mode,"bounded")){for(steps=0;steps<20;steps++){result=pst_connection_shutdown(connection,&operation,&error);printf("SHUTDOWN_STEP=%d RESULT=%ld OP=%lu ERROR=%ld\n",steps+1,(long)result,(unsigned long)operation,(long)error);if(result!=PST_RESULT_OK)goto done;if(operation==PST_OPERATION_COMPLETE||operation==PST_OPERATION_FAILED)break;if(!wait_step(connection))goto done;}if(steps==20)goto done;printf("SHUTDOWN=BOUNDED TERMINAL_OP=%lu ERROR=%ld\n",(unsigned long)operation,(long)error);}else if(!strcmp(close_mode,"client")){for(steps=0;steps<20;steps++){result=pst_connection_shutdown(connection,&operation,&error);printf("SHUTDOWN_STEP=%d RESULT=%ld OP=%lu ERROR=%ld\n",steps+1,(long)result,(unsigned long)operation,(long)error);if(result!=PST_RESULT_OK||operation==PST_OPERATION_FAILED)goto done;if(operation==PST_OPERATION_COMPLETE)break;if(!wait_step(connection))goto done;}if(steps==20)goto done;printf("SHUTDOWN=COMPLETE\n");}else{for(steps=0;steps<20;steps++){memset(&io,0,sizeof(io));result=pst_connection_read(connection,buffer,1,&io);if(result!=PST_RESULT_OK)goto done;if(io.operation==PST_OPERATION_CLOSED||io.operation==PST_OPERATION_FAILED)break;if(!wait_step(connection))goto done;}if(!strcmp(close_mode,"peer-clean")){if(io.operation!=PST_OPERATION_CLOSED||io.close_kind!=PST_CLOSE_CLEAN)goto done;}else if(!strcmp(close_mode,"peer-abrupt")){if(io.operation!=PST_OPERATION_FAILED||io.close_kind!=PST_CLOSE_TRUNCATED||io.error!=PST_RESULT_TRUNCATED)goto done;}else goto done;printf("PEER_CLOSE_MODE=%s OP=%lu CLOSE_KIND=%lu ERROR=%ld PASS=1\n",close_mode,(unsigned long)io.operation,(unsigned long)io.close_kind,(long)io.error);}
    pst_connection_release(connection);connection=NULL;memset(&summary,0,sizeof(summary));summary.struct_size=sizeof(summary);summary.api_version=PST_API_VERSION;if(pst_peer_info_get_summary(peer,&summary)!=PST_RESULT_OK||summary.certificate_present!=PST_KNOWN_TRUE||summary.chain_validated!=PST_KNOWN_TRUE||summary.hostname_validated!=PST_KNOWN_TRUE||summary.peer_authenticated!=PST_KNOWN_TRUE||summary.tls_version!=(pst_u32)version||summary.cipher_suite==0||summary.certificate_sha256_size!=32||summary.leaf_der_size==0)goto done;leaf_der=(pst_u8*)malloc(summary.leaf_der_size);if(!leaf_der)goto done;if(pst_peer_info_copy_leaf_der(peer,leaf_der,summary.leaf_der_size,&required_size)!=PST_RESULT_OK||required_size!=summary.leaf_der_size)goto done;leaf_size=summary.leaf_der_size;printf("PEER_INFO TLS=0x%04x CIPHER=0x%04lx CERT=1 CHAIN=1 HOSTNAME=1 AUTH=1 SHA256=32 LEAF_DER=%lu SNAPSHOT_AFTER_DESTROY=1\n",version==13?0x0304:0x0303,(unsigned long)summary.cipher_suite,(unsigned long)leaf_size);if(log_level>=0)printf("LOG_LEVEL=%d LOG_EVENTS=%lu LOG_ERROR=%lu LOG_WARN=%lu LOG_TRACE=%lu\n",log_level,(unsigned long)log_sink.total,(unsigned long)log_sink.error,(unsigned long)log_sink.warn,(unsigned long)log_sink.trace);ok=1;if(i)printf("OPENSSL_IDENTITY_MATRIX WRITE=25 READ=25 CONTENT_MATCH=1 PASS=1\n");else printf("OPENSSL_IDENTITY_MATRIX APPLICATION_BYTES_SENT=0 APPLICATION_BYTES_READ=0 PASS=1\n");done:if(connection)pst_connection_release(connection);if(peer)pst_peer_info_release(peer);if(transport)pst_transport_release(transport);if(socket_value!=INVALID_SOCKET)closesocket(socket_value);if(runtime)pst_runtime_release(runtime);if(config)pst_config_release(config);if(credentials)pst_credentials_release(credentials);if(trust)pst_trust_release(trust);free(trust_der);free(cert_der);free(key_der);free(leaf_der);pst_backend_registry_reset();WSACleanup();if(!ok)fprintf(stderr,"OPENSSL_RUNTIME_INTEGRATION=FAIL EXPECTED=%ld\n",(long)want);return ok?0:20;}