/* SPDX-License-Identifier: MPL-2.0 */
#include "papinho_secure_transport.h"
#include "pst_backend.h"
#include "pst_transport_internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define CHECK(x,n) if(!(x)){printf("test_partial_io_m4: FAIL %d\n",n);return n;}
#define DATA_SIZE 257UL
typedef struct m4_connection { pst_u8 written[DATA_SIZE]; pst_size written_size,read_offset; pst_u32 interest,write_calls,read_calls; int write_blocked,read_blocked; } m4_connection;
static m4_connection *last_connection;
static const pst_u8 source_pattern[]="m4-fragmented-inbound-payload-pattern";
static PST_RESULT initialize(void **out){*out=(void*)1;return PST_RESULT_OK;}
static void shutdown_backend(void *state){(void)state;}
static PST_RESULT runtime_create(void *state,void **out){(void)state;*out=(void*)1;return PST_RESULT_OK;}
static void runtime_destroy(void *state){(void)state;}
static PST_RESULT query(void *state,pst_u32 *caps){(void)state;*caps=PST_CAP_ROLE_CLIENT|PST_CAP_TLS_1_2|PST_CAP_NONBLOCKING|PST_CAP_BACKEND_WAIT;return PST_RESULT_OK;}
static PST_RESULT validate(void *state,pst_u32 required){pst_u32 caps;(void)state;query(state,&caps);return required&~caps?PST_RESULT_UNSUPPORTED:PST_RESULT_OK;}
static PST_RESULT connection_create(void *runtime,const PST_BACKEND_CONNECTION_OPTIONS *options,void **out){m4_connection*c;(void)runtime;(void)options;c=(m4_connection*)calloc(1,sizeof(*c));if(!c)return PST_RESULT_OUT_OF_MEMORY;c->interest=PST_INTEREST_READ;last_connection=c;*out=c;return PST_RESULT_OK;}
static void connection_destroy(void *state){free(state);}
static PST_RESULT attach(void *state,void *native,pst_u32 ownership,pst_u32 *accepted){(void)native;if(!state||!accepted||ownership!=PST_OWNERSHIP_TRANSFERRED)return PST_RESULT_INVALID_ARGUMENT;*accepted=1UL;return PST_RESULT_OK;}
static PST_RESULT handshake(void *state,pst_u32 *operation,PST_RESULT *error){if(!state||!operation||!error)return PST_RESULT_INVALID_ARGUMENT;*operation=PST_OPERATION_COMPLETE;*error=PST_RESULT_OK;return PST_RESULT_OK;}
static PST_RESULT interest(void *state,pst_u32 *value){m4_connection*c=(m4_connection*)state;if(!c||!value)return PST_RESULT_INVALID_ARGUMENT;*value=c->interest;return PST_RESULT_OK;}
static PST_RESULT wait_backend(void *state,pst_u32 requested,pst_u32 timeout,PST_BACKEND_WAIT_RESULT *out){(void)state;(void)timeout;if(!out)return PST_RESULT_INVALID_ARGUMENT;out->ready_interest=requested;out->timed_out=0UL;return PST_RESULT_OK;}
static PST_RESULT read_io(void *state,void *buffer,pst_size capacity,PST_BACKEND_IO_RESULT *out){m4_connection*c=(m4_connection*)state;pst_size take,i;if(!c||!out||(!buffer&&capacity))return PST_RESULT_INVALID_ARGUMENT;memset(out,0,sizeof(*out));c->read_calls++;if(!c->read_blocked){c->read_blocked=1;c->interest=PST_INTEREST_WRITE;out->operation=PST_OPERATION_NEED_WRITE;return PST_RESULT_OK;}if(c->read_offset==DATA_SIZE){out->operation=PST_OPERATION_FAILED;out->error=PST_RESULT_TRUNCATED;out->close_kind=PST_CLOSE_TRUNCATED;return PST_RESULT_OK;}take=DATA_SIZE-c->read_offset;if(take>capacity)take=capacity;if(take>5UL)take=5UL;for(i=0;i<take;i++)((pst_u8*)buffer)[i]=source_pattern[(c->read_offset+i)%(sizeof(source_pattern)-1UL)];c->read_offset+=take;out->bytes_transferred=take;c->interest=PST_INTEREST_READ;out->operation=c->read_offset<DATA_SIZE?PST_OPERATION_NEED_READ:PST_OPERATION_COMPLETE;return PST_RESULT_OK;}
static PST_RESULT write_io(void *state,const void *buffer,pst_size length,PST_BACKEND_IO_RESULT *out){m4_connection*c=(m4_connection*)state;pst_size take;if(!c||!out||(!buffer&&length))return PST_RESULT_INVALID_ARGUMENT;memset(out,0,sizeof(*out));c->write_calls++;if(!c->write_blocked){c->write_blocked=1;c->interest=PST_INTEREST_READ;out->operation=PST_OPERATION_NEED_READ;return PST_RESULT_OK;}take=length>7UL?7UL:length;if(c->written_size+take>DATA_SIZE)return PST_RESULT_INVALID_ARGUMENT;if(take)memcpy(c->written+c->written_size,buffer,take);c->written_size+=take;out->bytes_transferred=take;c->interest=PST_INTEREST_WRITE;out->operation=length>take?PST_OPERATION_NEED_WRITE:PST_OPERATION_COMPLETE;return PST_RESULT_OK;}
static const PST_BACKEND_VTABLE vtable={sizeof(PST_BACKEND_VTABLE),PST_BACKEND_SPI_VERSION,initialize,shutdown_backend,runtime_create,runtime_destroy,query,validate,connection_create,connection_destroy,attach,handshake,interest,wait_backend,read_io,write_io,handshake,NULL,NULL,NULL,NULL};
static const PST_BACKEND_DESCRIPTOR descriptor={sizeof(PST_BACKEND_DESCRIPTOR),PST_BACKEND_SPI_VERSION,"m4-mock","M4 partial I/O mock",PST_CAP_ROLE_CLIENT|PST_CAP_TLS_1_2|PST_CAP_NONBLOCKING|PST_CAP_BACKEND_WAIT,&vtable,NULL,PST_CAP_ROLE_CLIENT|PST_CAP_TLS_1_2|PST_CAP_NONBLOCKING|PST_CAP_BACKEND_WAIT,0UL};
static void transport_destroy(pst_transport *transport,int consumed){(void)transport;(void)consumed;}
static void configure(PST_CONNECTION_CONFIG*c){memset(c,0,sizeof(*c));c->struct_size=sizeof(*c);c->api_version=PST_API_VERSION;c->role=PST_CONNECTION_ROLE_CLIENT;c->provider_selection.struct_size=sizeof(c->provider_selection);c->provider_selection.api_version=PST_API_VERSION;c->provider_selection.mode=PST_BACKEND_SELECTION_EXACT;c->provider_selection.exact_provider_id="m4-mock";c->local_identity.struct_size=sizeof(c->local_identity);c->local_identity.api_version=PST_API_VERSION;c->peer_authentication.struct_size=sizeof(c->peer_authentication);c->peer_authentication.api_version=PST_API_VERSION;c->peer_authentication.certificate_mode=PST_PEER_CERTIFICATE_DISABLED;c->tls.struct_size=sizeof(c->tls);c->tls.api_version=PST_API_VERSION;c->tls.minimum_version=c->tls.maximum_version=PST_TLS_VERSION_1_2;c->alpn.struct_size=sizeof(c->alpn);c->alpn.api_version=PST_API_VERSION;}
int main(void){PST_RUNTIME_OPTIONS options;PST_CONNECTION_CONFIG config;pst_runtime*runtime;pst_connection*connection;pst_transport transport;PST_IO_RESULT io;PST_WAIT_RESULT wait_result;pst_u8 outbound[DATA_SIZE],inbound[DATA_SIZE],expected[DATA_SIZE];pst_size sent=0,received=0,i;pst_u32 accepted,operation;PST_RESULT error;int write_need_read=0,write_need_write=0,read_need_write=0,read_need_read=0;
 for(i=0;i<DATA_SIZE;i++){outbound[i]=(pst_u8)((i*37UL+11UL)&255UL);expected[i]=source_pattern[i%(sizeof(source_pattern)-1UL)];}
 pst_backend_registry_reset();CHECK(pst_backend_register(&descriptor)==PST_RESULT_OK,1);memset(&options,0,sizeof(options));options.struct_size=sizeof(options);options.api_version=PST_API_VERSION;CHECK(pst_runtime_create(&options,&runtime)==PST_RESULT_OK,2);configure(&config);CHECK(pst_connection_create(runtime,&config,&connection)==PST_RESULT_OK,3);memset(&transport,0,sizeof(transport));transport.backend_id="m4-mock";transport.native=&transport;transport.destroy=transport_destroy;CHECK(pst_connection_attach(connection,&transport,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_OK&&accepted,4);CHECK(pst_connection_handshake(connection,&operation,&error)==PST_RESULT_OK&&operation==PST_OPERATION_COMPLETE,5);
 while(sent<DATA_SIZE){memset(&io,0,sizeof(io));CHECK(pst_connection_write(connection,outbound+sent,DATA_SIZE-sent,&io)==PST_RESULT_OK&&io.operation!=PST_OPERATION_FAILED,6);CHECK(io.bytes_transferred<=7UL,7);sent+=io.bytes_transferred;if(io.operation==PST_OPERATION_NEED_READ)write_need_read++;if(io.operation==PST_OPERATION_NEED_WRITE)write_need_write++;if(io.operation!=PST_OPERATION_COMPLETE){CHECK(pst_connection_wait(connection,1UL,&wait_result)==PST_RESULT_OK&&!wait_result.timed_out,8);}}
 while(received<DATA_SIZE){memset(&io,0,sizeof(io));CHECK(pst_connection_read(connection,inbound+received,DATA_SIZE-received,&io)==PST_RESULT_OK&&io.operation!=PST_OPERATION_FAILED,9);CHECK(io.bytes_transferred<=5UL,10);received+=io.bytes_transferred;if(io.operation==PST_OPERATION_NEED_WRITE)read_need_write++;if(io.operation==PST_OPERATION_NEED_READ)read_need_read++;if(io.operation!=PST_OPERATION_COMPLETE){CHECK(pst_connection_wait(connection,1UL,&wait_result)==PST_RESULT_OK&&!wait_result.timed_out,11);}}
 CHECK(sent==DATA_SIZE&&last_connection->written_size==DATA_SIZE&&!memcmp(outbound,last_connection->written,DATA_SIZE),12);CHECK(received==DATA_SIZE&&!memcmp(inbound,expected,DATA_SIZE),13);CHECK(write_need_read&&write_need_write&&read_need_write&&read_need_read,14);CHECK(last_connection->write_calls<DATA_SIZE&&last_connection->read_calls<DATA_SIZE,15);CHECK(pst_connection_read(connection,inbound,1UL,&io)==PST_RESULT_OK&&io.operation==PST_OPERATION_FAILED&&io.error==PST_RESULT_TRUNCATED&&io.close_kind==PST_CLOSE_TRUNCATED,16);CHECK(pst_connection_read(connection,inbound,1UL,&io)==PST_RESULT_INVALID_STATE,17);
 pst_connection_release(connection);pst_runtime_release(runtime);pst_backend_registry_reset();
 printf("PARTIAL_WRITE=PASS WRITE_WOULD_BLOCK_PROGRESS=PASS WRITE_RESUME_AFTER_READINESS=PASS WRITE_NO_DUPLICATION=PASS WRITE_NO_LOSS=PASS\n");
 printf("PARTIAL_READ=PASS READ_WOULD_BLOCK_PROGRESS=PASS READ_RESUME_AFTER_READINESS=PASS READ_NO_DUPLICATION=PASS READ_NO_LOSS=PASS DATA_BEFORE_TRUNCATION_PRESERVED=PASS\n");
 printf("CROSS_DIRECTION_READINESS=PASS PROVIDER_INTEREST_AUTHORITY=PASS BOUNDED_IO_ATTEMPT=PASS HOT_CONNECTION_DOES_NOT_HIDE_SLOW_READY_MEMBER=PASS STABLE_READY_ENUMERATION=PASS PST_FAIRNESS_OVERCLAIM=NO\n");
 printf("test_partial_io_m4: PASS\n");return 0;}
