/* SPDX-License-Identifier: MPL-2.0 */
#include "papinho_secure_transport.h"
#include "papinho_secure_transport_win32.h"
#include "backends/schannel/pst_backend_schannel.h"
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#include <winsock2.h>
#include <windows.h>
#include <ncrypt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

typedef struct case_spec {const char*name,*address,*hostname,*root,*cert,*key;pst_u16 port;int fail,echo;} case_spec;
static int creates,destroys,setups,cleanups;
static unsigned char*load(const char*p,pst_size*n){FILE*f;long z;unsigned char*b;*n=0;f=fopen(p,"rb");if(!f)return NULL;if(fseek(f,0,SEEK_END)||(z=ftell(f))<0||fseek(f,0,SEEK_SET)){fclose(f);return NULL;}b=(unsigned char*)malloc((size_t)z);if(!b){fclose(f);return NULL;}if(z&&fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);*n=(pst_size)z;return b;}
static int connect4(const char*a,pst_u16 p,SOCKET*out){SOCKET s;struct sockaddr_in x;memset(&x,0,sizeof(x));x.sin_family=AF_INET;x.sin_port=htons(p);x.sin_addr.s_addr=inet_addr(a);s=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(s==INVALID_SOCKET)return 0;if(connect(s,(struct sockaddr*)&x,sizeof(x))==SOCKET_ERROR){closesocket(s);return 0;}*out=s;return 1;}
static int waitone(pst_connection*c){PST_WAIT_RESULT w;memset(&w,0,sizeof(w));return pst_connection_wait(c,1000,&w)==PST_RESULT_OK&&!w.timed_out&&w.ready_interest;}
static int keys(void){NCRYPT_PROV_HANDLE p=0;NCryptKeyName*k=NULL;PVOID state=NULL;SECURITY_STATUS s;int n=0;if(NCryptOpenStorageProvider(&p,MS_KEY_STORAGE_PROVIDER,0)!=ERROR_SUCCESS)return -1;for(;;){s=NCryptEnumKeys(p,NULL,&k,&state,0);if(s==NTE_NO_MORE_ITEMS)break;if(s!=ERROR_SUCCESS){n=-1;break;}if(k&&k->pszName&&!wcsncmp(k->pszName,L"PST-8F-",7))n++;NCryptFreeBuffer(k);k=NULL;}if(k)NCryptFreeBuffer(k);if(state)NCryptFreeBuffer(state);NCryptFreeObject(p);return n;}
static int run(pst_runtime*rt,const case_spec*s,PST_DIAGNOSTIC_INFO*snap){PST_TRUST_SOURCE ts;PST_CREDENTIAL_SOURCE cs;PST_IDENTITY_CONFIG id;PST_TLS_POLICY po;PST_ALPN_PROTOCOL ap;PST_IO_RESULT io;PST_DIAGNOSTIC_INFO d;PST_PEER_INFO_SUMMARY sm;pst_trust*t=NULL;pst_credentials*cr=NULL;pst_config*cfg=NULL;pst_connection*cn=NULL;pst_transport*tr=NULL;pst_peer_info*pi=NULL;unsigned char*rd=NULL,*cd=NULL,*kd=NULL;pst_size rn=0,cn_=0,kn=0,n,off;pst_u32 accepted,op;PST_RESULT r,e;SOCKET sk=INVALID_SOCKET;char buf[25];const char msg[]="pst-phase5-public-runtime";int i,ok=0,identity=s->cert!=NULL;
printf("%s_BEGIN TRUST=%s CLIENT_CREDENTIAL=%d HOSTNAME=%s ALPN=%s\n",s->name,s->root?"CUSTOM":"SYSTEM",identity,s->hostname,s->echo?"fixture/1":"NONE");
if(s->root){rd=load(s->root,&rn);if(!rd)goto out;}if(identity){cd=load(s->cert,&cn_);kd=load(s->key,&kn);if(!cd||!kd)goto out;setups++;}
memset(&ts,0,sizeof(ts));ts.struct_size=sizeof(ts);ts.api_version=PST_API_VERSION;ts.kind=s->root?PST_TRUST_SOURCE_CUSTOM_CA_DER:PST_TRUST_SOURCE_SYSTEM;ts.data=rd;ts.data_size=rn;if(pst_trust_create(&ts,&t)!=PST_RESULT_OK)goto out;
if(identity){memset(&cs,0,sizeof(cs));cs.struct_size=sizeof(cs);cs.api_version=PST_API_VERSION;cs.kind=PST_CREDENTIAL_SOURCE_CERT_DER_PKCS8_DER;cs.certificate_der=cd;cs.certificate_der_size=cn_;cs.private_key_der=kd;cs.private_key_der_size=kn;if(pst_credentials_create(&cs,&cr)!=PST_RESULT_OK)goto out;}
if(pst_config_create(&cfg)!=PST_RESULT_OK)goto out;memset(&id,0,sizeof(id));id.struct_size=sizeof(id);id.api_version=PST_API_VERSION;id.credentials=cr;id.trust=t;id.expected_hostname=s->hostname;id.expected_hostname_size=strlen(s->hostname);id.require_peer_authentication=1;id.require_client_authentication=identity?1:0;if(pst_config_set_identity(cfg,&id)!=PST_RESULT_OK)goto out;
memset(&po,0,sizeof(po));po.struct_size=sizeof(po);po.api_version=PST_API_VERSION;po.minimum_version=PST_TLS_VERSION_1_2;po.maximum_version=PST_TLS_VERSION_1_2;po.early_data=PST_FEATURE_DISABLED;if(s->echo){ap.data=(const pst_u8*)"fixture/1";ap.size=9;po.alpn_protocols=&ap;po.alpn_protocol_count=1;po.alpn_requirement=PST_FEATURE_REQUIRED;}else po.alpn_requirement=PST_FEATURE_DISABLED;if(pst_config_set_tls_policy(cfg,&po)!=PST_RESULT_OK||pst_config_freeze(cfg)!=PST_RESULT_OK)goto out;
if(pst_connection_create(rt,cfg,&cn)!=PST_RESULT_OK)goto out;creates++;pst_config_release(cfg);cfg=NULL;if(!connect4(s->address,s->port,&sk)||pst_win32_socket_transport_create((pst_size)sk,&tr)!=PST_RESULT_OK)goto out;accepted=0;if(pst_connection_attach(cn,tr,PST_OWNERSHIP_TRANSFERRED,&accepted)!=PST_RESULT_OK||!accepted)goto out;tr=NULL;sk=INVALID_SOCKET;
for(i=0;i<30;i++){r=pst_connection_handshake(cn,&op,&e);if(r!=PST_RESULT_OK)goto out;if(op==PST_OPERATION_FAILED){memset(&d,0,sizeof(d));d.struct_size=sizeof(d);d.api_version=PST_API_VERSION;if(!s->fail||e!=PST_RESULT_AUTH_FAILURE||pst_connection_copy_diagnostic(cn,&d)!=PST_RESULT_OK||!d.valid||d.normalized_result!=PST_RESULT_AUTH_FAILURE||strcmp(d.backend_id,"schannel"))goto out;if(pst_connection_handshake(cn,&op,&e)!=PST_RESULT_INVALID_STATE||pst_connection_read(cn,buf,1,&io)!=PST_RESULT_INVALID_STATE||pst_connection_write(cn,msg,1,&io)!=PST_RESULT_INVALID_STATE)goto out;*snap=d;printf("C_AUTH_FAILURE DIAG_VALID=1 DIAG_RESULT=AUTH_FAILURE DIAG_BACKEND=schannel NO_RESURRECTION=1\n");ok=1;goto out;}if(op==PST_OPERATION_COMPLETE)break;if(!waitone(cn))goto out;}if(i==30||s->fail)goto out;
memset(&d,0,sizeof(d));d.struct_size=sizeof(d);d.api_version=PST_API_VERSION;if(pst_connection_copy_diagnostic(cn,&d)!=PST_RESULT_OK||d.valid)goto out;
if(s->echo){off=0;while(off<sizeof(msg)-1){memset(&io,0,sizeof(io));if(pst_connection_write(cn,msg+off,sizeof(msg)-1-off,&io)!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED)goto out;off+=io.bytes_transferred;if(off<sizeof(msg)-1&&!waitone(cn))goto out;}n=0;while(n<sizeof(msg)-1){memset(&io,0,sizeof(io));if(pst_connection_read(cn,buf+n,sizeof(msg)-1-n,&io)!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED||io.operation==PST_OPERATION_CLOSED)goto out;n+=io.bytes_transferred;if(n<sizeof(msg)-1&&!waitone(cn))goto out;}if(n!=sizeof(msg)-1||memcmp(buf,msg,n))goto out;}
if(pst_connection_get_peer_info(cn,&pi)!=PST_RESULT_OK)goto out;memset(&sm,0,sizeof(sm));sm.struct_size=sizeof(sm);sm.api_version=PST_API_VERSION;if(pst_peer_info_get_summary(pi,&sm)!=PST_RESULT_OK||sm.chain_validated!=PST_KNOWN_TRUE||sm.hostname_validated!=PST_KNOWN_TRUE||sm.peer_authenticated!=PST_KNOWN_TRUE)goto out;for(i=0;i<20;i++){if(pst_connection_shutdown(cn,&op,&e)!=PST_RESULT_OK||op==PST_OPERATION_FAILED)goto out;if(op==PST_OPERATION_COMPLETE)break;if(!waitone(cn))goto out;}if(i==20)goto out;printf("%s_PASS AUTH=1 WRITE=%d READ=%d CONTENT_MATCH=%d DIAG_VALID=0 CLIENT_CREDENTIAL=%d SHUTDOWN=COMPLETE\n",s->name,s->echo?25:0,s->echo?25:0,s->echo?1:0,identity);ok=1;
out:if(pi)pst_peer_info_release(pi);if(cn){pst_connection_release(cn);destroys++;if(identity)cleanups++;}if(tr)pst_transport_release(tr);if(sk!=INVALID_SOCKET)closesocket(sk);if(cfg)pst_config_release(cfg);if(cr)pst_credentials_release(cr);if(t)pst_trust_release(t);free(rd);free(cd);free(kd);printf("%s_END PASS=%d PST_MTLS_KEY_REMAINS=%d\n",s->name,ok,keys());return ok&&keys()==0;}
int main(int ac,char**av){WSADATA w;PST_RUNTIME_OPTIONS o;PST_LOG_CONFIG l;PST_RUNTIME_INFO inf;PST_DIAGNOSTIC_INFO snap,copy;pst_runtime*rt=NULL;case_spec s[4];int i,ok=0;if(ac!=13){fprintf(stderr,"usage: local b1 c b2 system system-port system-host root valid-cert valid-key wrong-cert wrong-key\n");return 2;}if(WSAStartup(MAKEWORD(2,2),&w)!=0)return 3;if(pst_backend_schannel_register()!=PST_RESULT_OK)goto done;memset(&o,0,sizeof(o));o.struct_size=sizeof(o);o.api_version=PST_API_VERSION;o.selection=PST_BACKEND_SELECTION_EXACT;o.exact_backend_id="schannel";o.required_capabilities=PST_CAP_TLS_1_2|PST_CAP_SYSTEM_TRUST|PST_CAP_CUSTOM_TRUST|PST_CAP_HOSTNAME_VERIFY|PST_CAP_ALPN|PST_CAP_CLIENT_AUTH|PST_CAP_PEER_INFO;if(pst_log_config_init(&l)!=PST_RESULT_OK)goto done;l.level=PST_LOG_LEVEL_OFF;if(pst_runtime_create_with_logging(&o,&l,&rt,NULL)!=PST_RESULT_OK)goto done;printf("ISOLATION_BEGIN PROCESS_ID=%lu RUNTIME_INSTANCE_SEQ=1 RUNTIME_CREATE_COUNT=1\n",(unsigned long)GetCurrentProcessId());
s[0].name="B1";s[0].address=av[1];s[0].port=(pst_u16)atoi(av[2]);s[0].hostname="localhost";s[0].root=av[8];s[0].cert=av[9];s[0].key=av[10];s[0].fail=0;s[0].echo=1;s[1]=s[0];s[1].name="C";s[1].port=(pst_u16)atoi(av[3]);s[1].cert=av[11];s[1].key=av[12];s[1].fail=1;s[1].echo=1;s[2]=s[0];s[2].name="A";s[2].address=av[5];s[2].port=(pst_u16)atoi(av[6]);s[2].hostname=av[7];s[2].root=NULL;s[2].cert=NULL;s[2].key=NULL;s[2].fail=0;s[2].echo=0;s[3]=s[0];s[3].name="B2";s[3].port=(pst_u16)atoi(av[4]);memset(&snap,0,sizeof(snap));for(i=0;i<4;i++)if(!run(rt,&s[i],&snap))goto done;copy=snap;if(!copy.valid||copy.normalized_result!=PST_RESULT_AUTH_FAILURE||strcmp(copy.backend_id,"schannel"))goto done;memset(&inf,0,sizeof(inf));inf.struct_size=sizeof(inf);inf.api_version=PST_API_VERSION;if(pst_runtime_get_info(rt,&inf)!=PST_RESULT_OK||inf.capabilities!=0x00000e7dUL)goto done;ok=creates==4&&destroys==4&&setups==3&&cleanups==3&&keys()==0;printf("ISOLATION_CLEANUP CONNECTION_CREATE=%d CONNECTION_DESTROY=%d IDENTITY_SETUP=%d IDENTITY_CLEANUP=%d C_SNAPSHOT_IMMUTABLE=1 PST_MTLS_KEY_REMAINS=%d CAPABILITIES=0x%08lx\n",creates,destroys,setups,cleanups,keys(),(unsigned long)inf.capabilities);
done:if(rt){pst_runtime_release(rt);printf("RUNTIME_RELEASE_COUNT=1\n");}pst_backend_registry_reset();WSACleanup();printf("ISOLATION_END PASS=%d\n",ok);return ok?0:20;}