/* SPDX-License-Identifier: MPL-2.0 */
#include "papinho_secure_transport.h"
#include "papinho_secure_transport_win32.h"
#include "backends/openssl/pst_backend_openssl.h"
#include <winsock2.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static unsigned char *load(const char *path,pst_size *size)
{FILE*f;long n;unsigned char*p;*size=0;f=fopen(path,"rb");if(!f)return NULL;if(fseek(f,0,SEEK_END)||(n=ftell(f))<0||fseek(f,0,SEEK_SET)){fclose(f);return NULL;}p=(unsigned char*)malloc((size_t)n);if(!p){fclose(f);return NULL;}if(n&&fread(p,1,(size_t)n,f)!=(size_t)n){free(p);fclose(f);return NULL;}fclose(f);*size=(pst_size)n;return p;}
static int wait_for(pst_connection*c)
{pst_u32 interest;PST_WAIT_RESULT w;if(pst_connection_get_interest(c,&interest)!=PST_RESULT_OK||!interest)return 0;memset(&w,0,sizeof(w));return pst_connection_wait(c,2000,&w)==PST_RESULT_OK&&!w.timed_out&&w.ready_interest;}
static int drive_handshake(pst_connection*c,pst_u32*steps,pst_u32*waits,PST_RESULT*final)
{pst_u32 op;PST_RESULT e;for(*steps=1;*steps<=200;(*steps)++){if(pst_connection_handshake(c,&op,&e)!=PST_RESULT_OK)return 0;if(op==PST_OPERATION_COMPLETE){*final=PST_RESULT_OK;return 1;}if(op==PST_OPERATION_FAILED){*final=e;return 0;}if(!wait_for(c))return 0;(*waits)++;}return 0;}
static int drive_shutdown(pst_connection*c,pst_u32*steps)
{pst_u32 op;PST_RESULT e;for(*steps=1;*steps<=40;(*steps)++){if(pst_connection_shutdown(c,&op,&e)!=PST_RESULT_OK||op==PST_OPERATION_FAILED)return 0;if(op==PST_OPERATION_COMPLETE)return 1;if(!wait_for(c))return 0;}return 0;}
static int split_alpn(char*text,PST_ALPN_PROTOCOL*items,pst_size*count)
{char*p,*comma;p=text;*count=0;if(!strcmp(text,"-"))return 1;while(*p&&*count<4){comma=strchr(p,',');if(comma)*comma='\0';items[*count].data=(const pst_u8*)p;items[*count].size=strlen(p);if(!items[*count].size||items[*count].size>255)return 0;(*count)++;if(!comma)return 1;p=comma+1;}return *p=='\0';}
typedef struct log_capture {pst_u32 events,server_events,error_events,secret_hits,bad_events;} log_capture;
static void PST_CALL capture_log(void*context,const PST_LOG_EVENT*event)
{log_capture*s=(log_capture*)context;if(!s||!event)return;s->events++;if(event->role==PST_CONNECTION_ROLE_SERVER)s->server_events++;if(event->level==PST_LOG_LEVEL_ERROR)s->error_events++;if(event->struct_size!=sizeof(*event)||event->api_version!=PST_API_VERSION)s->bad_events++;if(event->backend_id[0]&&(strcmp(event->backend_id,"openssl")||event->role!=PST_CONNECTION_ROLE_SERVER))s->bad_events++;if(event->normalized_result!=PST_RESULT_OK&&event->level!=PST_LOG_LEVEL_ERROR)s->bad_events++;if(strstr(event->backend_id,"PRIVATE")||strstr(event->backend_id,"pst-phase5-public-runtime")||strstr(event->backend_id,"BEGIN"))s->secret_hits++;}
int main(int ac,char**av)
{
 WSADATA wd;SOCKET listener=INVALID_SOCKET,accepted_socket=INVALID_SOCKET;struct sockaddr_in a;pst_runtime*rt=NULL;pst_connection*c=NULL;pst_transport*t=NULL;pst_credentials*credentials=NULL;pst_trust*trust=NULL;pst_peer_info*peer=NULL;PST_RUNTIME_OPTIONS ro;PST_LOG_CONFIG lc;log_capture logs={0};PST_CONNECTION_CONFIG cc;PST_CREDENTIAL_SOURCE cs;PST_TRUST_SOURCE ts;PST_DER_ITEM chain[2],anchor;PST_ALPN_PROTOCOL protocols[4];PST_PEER_INFO_SUMMARY summary;PST_PROVIDER_INFO provider_info;PST_DIAGNOSTIC_INFO diagnostic;PST_IO_RESULT io;unsigned char *leaf=NULL,*intermediate=NULL,*key=NULL,*ca=NULL,buffer[64],alpn[255];pst_size leaf_n,intermediate_n,key_n,ca_n,alpn_n=0,protocol_count=0,total;int tls,mode,ok=0,truncate_mode=0;pst_u32 ownership=0,steps=0,waits=0,shutdown_steps=0;PST_RESULT final=PST_RESULT_BACKEND_FAILURE;const char*selection="exact",*scenario="echo",*trust_mode="custom";const char*order[2]={"schannel","openssl"};char alpn_text[512];
 if(ac!=8&&ac!=11&&ac!=12){fprintf(stderr,"usage: port tls peer-mode server.der intermediate.der server.pk8 client-ca.der [exact|ordered|automatic alpn-list|- echo|truncate [custom|system]]\n");return 2;}if(ac>=11){selection=av[8];scenario=av[10];}if(ac==12)trust_mode=av[11];strcpy(alpn_text,ac>=11?av[9]:"fixture/1");if(strcmp(trust_mode,"custom")&&strcmp(trust_mode,"system"))return 2;if(!split_alpn(alpn_text,protocols,&protocol_count))return 2;truncate_mode=!strcmp(scenario,"truncate");if(strcmp(scenario,"echo")&&strcmp(scenario,"truncate"))return 2;tls=atoi(av[2]);mode=atoi(av[3]);leaf=load(av[4],&leaf_n);intermediate=load(av[5],&intermediate_n);key=load(av[6],&key_n);ca=load(av[7],&ca_n);if(!leaf||!intermediate||!key||!ca)return 3;if(WSAStartup(MAKEWORD(2,2),&wd))return 3;
 memset(&cs,0,sizeof(cs));cs.struct_size=sizeof(cs);cs.api_version=PST_API_VERSION;cs.kind=PST_CREDENTIAL_SOURCE_CERT_CHAIN_DER_PKCS8_DER;chain[0].data=leaf;chain[0].size=leaf_n;chain[1].data=intermediate;chain[1].size=intermediate_n;cs.certificate_chain=chain;cs.certificate_count=2;cs.private_key_der=key;cs.private_key_der_size=key_n;if(pst_credentials_create(&cs,&credentials)!=PST_RESULT_OK)goto done;
 if(mode!=PST_PEER_CERTIFICATE_DISABLED){memset(&ts,0,sizeof(ts));ts.struct_size=sizeof(ts);ts.api_version=PST_API_VERSION;ts.kind=!strcmp(trust_mode,"system")?PST_TRUST_SOURCE_SYSTEM:PST_TRUST_SOURCE_CUSTOM_CA_DER;if(ts.kind==PST_TRUST_SOURCE_CUSTOM_CA_DER){anchor.data=ca;anchor.size=ca_n;ts.anchors=&anchor;ts.anchor_count=1;}if(pst_trust_create(&ts,&trust)!=PST_RESULT_OK)goto done;}
 pst_backend_registry_reset();if(pst_win32_register_builtin_providers()!=PST_RESULT_OK)goto done;memset(&ro,0,sizeof(ro));ro.struct_size=sizeof(ro);ro.api_version=PST_API_VERSION;memset(&logs,0,sizeof(logs));if(pst_log_config_init(&lc)!=PST_RESULT_OK)goto done;lc.level=PST_LOG_LEVEL_TRACE;lc.callback=capture_log;lc.user_context=&logs;if(pst_runtime_create_with_logging(&ro,&lc,&rt,NULL)!=PST_RESULT_OK)goto done;
 memset(&cc,0,sizeof(cc));cc.struct_size=sizeof(cc);cc.api_version=PST_API_VERSION;cc.role=PST_CONNECTION_ROLE_SERVER;cc.provider_selection.struct_size=sizeof(cc.provider_selection);cc.provider_selection.api_version=PST_API_VERSION;if(!strcmp(selection,"exact")){cc.provider_selection.mode=PST_BACKEND_SELECTION_EXACT;cc.provider_selection.exact_provider_id="openssl";}else if(!strcmp(selection,"ordered")){cc.provider_selection.mode=PST_BACKEND_SELECTION_ORDERED;cc.provider_selection.ordered_provider_ids=order;cc.provider_selection.ordered_provider_count=2;}else if(!strcmp(selection,"automatic")){cc.provider_selection.mode=PST_BACKEND_SELECTION_AUTOMATIC;}else goto done;cc.local_identity.struct_size=sizeof(cc.local_identity);cc.local_identity.api_version=PST_API_VERSION;cc.local_identity.credentials=credentials;cc.peer_authentication.struct_size=sizeof(cc.peer_authentication);cc.peer_authentication.api_version=PST_API_VERSION;cc.peer_authentication.certificate_mode=(pst_u32)mode;cc.peer_authentication.trust=trust;cc.tls.struct_size=sizeof(cc.tls);cc.tls.api_version=PST_API_VERSION;cc.tls.minimum_version=tls==12?PST_TLS_VERSION_1_2:PST_TLS_VERSION_1_3;cc.tls.maximum_version=cc.tls.minimum_version;cc.alpn.struct_size=sizeof(cc.alpn);cc.alpn.api_version=PST_API_VERSION;cc.alpn.mode=protocol_count?PST_FEATURE_REQUIRED:PST_FEATURE_DISABLED;cc.alpn.protocols=protocol_count?protocols:NULL;cc.alpn.protocol_count=protocol_count;if(pst_connection_create(rt,&cc,&c)!=PST_RESULT_OK)goto done;memset(&provider_info,0,sizeof(provider_info));provider_info.struct_size=sizeof(provider_info);provider_info.api_version=PST_API_VERSION;if(pst_connection_get_provider_info(c,&provider_info)!=PST_RESULT_OK)goto done;printf("BOUND_PROVIDER=%s SELECTION=%s ROLE=SERVER\n",provider_info.provider_id,selection);
 listener=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(listener==INVALID_SOCKET)goto done;memset(&a,0,sizeof(a));a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);a.sin_port=htons((u_short)atoi(av[1]));if(bind(listener,(struct sockaddr*)&a,sizeof(a))||listen(listener,1))goto done;printf("READY PORT=%s TLS=%d PEER_MODE=%d\n",av[1],tls,mode);fflush(stdout);accepted_socket=accept(listener,NULL,NULL);if(accepted_socket==INVALID_SOCKET)goto done;if(pst_win32_socket_transport_create((pst_size)accepted_socket,&t)!=PST_RESULT_OK)goto done;if(pst_connection_attach(c,t,PST_OWNERSHIP_TRANSFERRED,&ownership)!=PST_RESULT_OK||!ownership)goto done;t=NULL;accepted_socket=INVALID_SOCKET;if(!drive_handshake(c,&steps,&waits,&final))goto done;
 total=0;while(total<25){if(pst_connection_read(c,buffer+total,25-total,&io)!=PST_RESULT_OK||io.operation==PST_OPERATION_FAILED||io.operation==PST_OPERATION_CLOSED)goto done;total+=io.bytes_transferred;if(total<25&&io.operation!=PST_OPERATION_COMPLETE&&!wait_for(c))goto done;}if(truncate_mode){for(steps=0;steps<40;steps++){if(pst_connection_read(c,buffer,1,&io)!=PST_RESULT_OK)goto done;if(io.operation==PST_OPERATION_FAILED)break;if(io.operation==PST_OPERATION_CLOSED)goto done;if(!wait_for(c))goto done;}if(io.operation!=PST_OPERATION_FAILED||io.error!=PST_RESULT_TRUNCATED||io.close_kind!=PST_CLOSE_TRUNCATED)goto done;printf("SERVER_TRUNCATION=PASS READ=25 CONTENT_MATCH=1 RESULT=TRUNCATED CLOSE_KIND=TRUNCATED\n");ok=1;goto done;}if(pst_connection_write(c,buffer,25,&io)!=PST_RESULT_OK||io.bytes_transferred!=25)goto done;if(protocol_count){if(pst_connection_get_negotiated_alpn(c,alpn,sizeof(alpn),&alpn_n)!=PST_RESULT_OK)goto done;}else if(pst_connection_get_negotiated_alpn(c,alpn,sizeof(alpn),&alpn_n)!=PST_RESULT_UNAVAILABLE)goto done;memset(&summary,0,sizeof(summary));summary.struct_size=sizeof(summary);summary.api_version=PST_API_VERSION;if(pst_connection_get_peer_info(c,&peer)==PST_RESULT_OK){if(pst_peer_info_get_summary(peer,&summary)!=PST_RESULT_OK||summary.local_role!=PST_CONNECTION_ROLE_SERVER||summary.peer_name_validated!=PST_KNOWN_NOT_APPLICABLE)goto done;}if(!drive_shutdown(c,&shutdown_steps))goto done;printf("SERVER_HANDSHAKE=PASS PROVIDER=openssl SELECTION=%s TLS=0x%04x STEPS=%lu WAITS=%lu READ=25 WRITE=25 CONTENT_MATCH=1 ALPN=%.*s CERT_PRESENT=%lu AUTH=%lu SHUTDOWN_STEPS=%lu PASS=1\n",selection,tls==12?0x0303:0x0304,(unsigned long)steps,(unsigned long)waits,(int)alpn_n,alpn,(unsigned long)summary.certificate_present,(unsigned long)summary.peer_authenticated,(unsigned long)shutdown_steps);ok=1;
done:if(!ok){memset(&diagnostic,0,sizeof(diagnostic));diagnostic.struct_size=sizeof(diagnostic);diagnostic.api_version=PST_API_VERSION;if(c)pst_connection_copy_diagnostic(c,&diagnostic);fprintf(stderr,"SERVER_FAIL RESULT=%ld STEPS=%lu WAITS=%lu DIAG_VALID=%lu DIAG_RESULT=%ld DIAG_OPERATION=%lu DIAG_REASON=%lu BACKEND=%s\n",(long)final,(unsigned long)steps,(unsigned long)waits,(unsigned long)diagnostic.valid,(long)diagnostic.normalized_result,(unsigned long)diagnostic.operation,(unsigned long)diagnostic.reason,diagnostic.backend_id);}printf("SERVER_LOGGING=%s LOG_EVENTS=%lu SERVER_EVENTS=%lu ERROR_EVENTS=%lu LOG_SECRET_HITS=%lu\n",logs.bad_events||logs.secret_hits?"FAIL":"PASS",(unsigned long)logs.events,(unsigned long)logs.server_events,(unsigned long)logs.error_events,(unsigned long)logs.secret_hits);if(logs.bad_events||logs.secret_hits)ok=0;pst_peer_info_release(peer);pst_connection_release(c);pst_runtime_release(rt);pst_trust_release(trust);pst_credentials_release(credentials);pst_transport_release(t);if(accepted_socket!=INVALID_SOCKET)closesocket(accepted_socket);if(listener!=INVALID_SOCKET)closesocket(listener);pst_backend_registry_reset();WSACleanup();free(leaf);free(intermediate);free(key);free(ca);return ok?0:20;
}
