#include "papinho_secure_transport.h"
#include "papinho_secure_transport_win32.h"
#include "backends/schannel/pst_backend_schannel.h"
#include "pst_transport_internal.h"
#include <winsock2.h>
#include <stdio.h>
#include <string.h>
#define CHECK(x,n) if(!(x)){printf("test_backend_schannel: FAIL %d\n",n);return n;}
static int pair(SOCKET *client,SOCKET *server){SOCKET l;struct sockaddr_in a;int z;*client=*server=INVALID_SOCKET;l=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(l==INVALID_SOCKET)return 0;memset(&a,0,sizeof(a));a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(bind(l,(struct sockaddr*)&a,sizeof(a))||listen(l,1)){closesocket(l);return 0;}z=sizeof(a);if(getsockname(l,(struct sockaddr*)&a,&z)){closesocket(l);return 0;}*client=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(*client==INVALID_SOCKET||connect(*client,(struct sockaddr*)&a,sizeof(a))){closesocket(l);return 0;}*server=accept(l,NULL,NULL);closesocket(l);return *server!=INVALID_SOCKET;}
int main(void){const PST_BACKEND_DESCRIPTOR*d;void*s;int i;WSADATA wd;PST_RUNTIME_OPTIONS o;PST_RUNTIME_INFO ri;pst_runtime*r;pst_config*cfg;pst_connection*c;pst_transport*t;SOCKET client,server;PST_NATIVE_TRANSPORT bad;pst_transport badwrap;pst_u32 accepted,op;PST_RESULT e;d=pst_backend_schannel_descriptor();CHECK(d&&!strcmp(d->id,"schannel"),1);CHECK(d->spi_version==PST_BACKEND_SPI_VERSION&&d->metadata&&d->metadata->implementation.major==1UL,2);CHECK(d->capabilities==PST_BACKEND_CAP_NONBLOCKING,3);for(i=0;i<100;i++){s=NULL;CHECK(d->vtable->initialize(&s)==PST_RESULT_OK&&s,4);d->vtable->shutdown(s);}pst_backend_registry_reset();CHECK(pst_backend_schannel_register()==PST_RESULT_OK,5);memset(&o,0,sizeof(o));o.struct_size=sizeof(o);o.api_version=PST_API_VERSION;o.selection=PST_BACKEND_SELECTION_EXACT;o.exact_backend_id="missing";r=NULL;CHECK(pst_runtime_create(&o,&r)==PST_RESULT_UNSUPPORTED&&!r,6);o.exact_backend_id="schannel";CHECK(pst_runtime_create(&o,&r)==PST_RESULT_OK,7);memset(&ri,0,sizeof(ri));ri.struct_size=sizeof(ri);ri.api_version=PST_API_VERSION;CHECK(pst_runtime_get_info(r,&ri)==PST_RESULT_OK&&!strcmp(ri.backend_id,"schannel"),8);CHECK(pst_config_create(&cfg)==PST_RESULT_OK&&pst_config_freeze(cfg)==PST_RESULT_OK,9);CHECK(pst_connection_create(r,cfg,&c)==PST_RESULT_OK,10);memset(&bad,0,sizeof(bad));bad.struct_size=sizeof(bad);bad.version=PST_NATIVE_TRANSPORT_VERSION;bad.kind=999;memset(&badwrap,0,sizeof(badwrap));badwrap.native=&bad;accepted=9;CHECK(pst_connection_attach(c,&badwrap,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_INVALID_ARGUMENT&&!accepted,11);pst_connection_release(c);pst_runtime_release(r);pst_config_release(cfg);pst_backend_registry_reset();CHECK(pst_backend_schannel_register()==PST_RESULT_OK,12);memset(&o,0,sizeof(o));o.struct_size=sizeof(o);o.api_version=PST_API_VERSION;o.selection=PST_BACKEND_SELECTION_AUTOMATIC;CHECK(pst_runtime_create(&o,&r)==PST_RESULT_OK,13);CHECK(pst_config_create(&cfg)==PST_RESULT_OK&&pst_config_freeze(cfg)==PST_RESULT_OK,14);CHECK(WSAStartup(MAKEWORD(2,2),&wd)==0&&pair(&client,&server),15);CHECK(pst_connection_create(r,cfg,&c)==PST_RESULT_OK&&pst_win32_socket_transport_create((pst_size)client,&t)==PST_RESULT_OK,16);accepted=0;CHECK(pst_connection_attach(c,t,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_OK&&accepted,17);t=NULL;CHECK(pst_connection_handshake(c,&op,&e)==PST_RESULT_OK&&op==PST_OPERATION_FAILED&&e==PST_RESULT_UNSUPPORTED,18);pst_connection_release(c);CHECK(closesocket(client)==SOCKET_ERROR&&WSAGetLastError()==WSAENOTSOCK,19);closesocket(server);WSACleanup();pst_config_release(cfg);pst_runtime_release(r);pst_backend_registry_reset();printf("SCHANNEL_SKELETON=PASS TLS_CAPABILITIES=NONE INIT_CYCLES=100 OWNERSHIP=PASS\n");printf("test_backend_schannel: PASS\n");return 0;}