/* SPDX-License-Identifier: MPL-2.0 */
#include "pst_backend.h"
#include "pst_identity_internal.h"
#include "pst_internal.h"
#include "pst_transport_internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define BASE_CAPS (PST_CAP_NONBLOCKING|PST_CAP_BACKEND_WAIT)
#define CHECK(v,n) if(!(v)){printf("test_tls_policy: FAIL %d\n",(n));return(n);}
typedef struct policy_backend{pst_u32 capabilities;}policy_backend;
typedef struct policy_runtime{policy_backend *backend;}policy_runtime;
typedef struct policy_connection{policy_backend *backend;pst_u32 min_version,max_version,alpn_requirement;pst_u8 alpn[32];pst_size alpn_size;pst_internal_diagnostic diagnostic;}policy_connection;
typedef struct log_capture{pst_u32 total,errors;}log_capture;
static policy_backend g_a={BASE_CAPS|PST_CAP_TLS_1_2};
static policy_backend g_b={BASE_CAPS|PST_CAP_TLS_1_2|PST_CAP_TLS_1_3|PST_CAP_ALPN|PST_CAP_CUSTOM_TRUST|PST_CAP_HOSTNAME_VERIFY|PST_CAP_CLIENT_AUTH};
static policy_backend g_c={BASE_CAPS|PST_CAP_TLS_1_3};
static const pst_u8 *g_selected_alpn;static pst_size g_selected_alpn_size;static int g_transport_destroyed;
static PST_RESULT initialize_a(void **out){*out=&g_a;return PST_RESULT_OK;}
static PST_RESULT initialize_b(void **out){*out=&g_b;return PST_RESULT_OK;}
static PST_RESULT initialize_c(void **out){*out=&g_c;return PST_RESULT_OK;}
static void mock_shutdown(void *state){(void)state;}
static PST_RESULT mock_runtime_create(void *state,void **out){policy_runtime *r=(policy_runtime*)malloc(sizeof(*r));if(!r)return PST_RESULT_OUT_OF_MEMORY;r->backend=(policy_backend*)state;*out=r;return PST_RESULT_OK;}
static void mock_runtime_destroy(void *state){free(state);}
static PST_RESULT mock_query(void *state,pst_u32 *caps){if(!state||!caps)return PST_RESULT_INVALID_ARGUMENT;*caps=((policy_backend*)state)->capabilities;return PST_RESULT_OK;}
static PST_RESULT mock_validate(void *state,pst_u32 required){policy_runtime *r=(policy_runtime*)state;if(!r)return PST_RESULT_INVALID_ARGUMENT;return(required&~r->backend->capabilities)?PST_RESULT_UNSUPPORTED:PST_RESULT_OK;}
static PST_RESULT mock_connection_create(void *state,void **out){policy_connection *c;policy_runtime *r=(policy_runtime*)state;if(!r||!out)return PST_RESULT_INVALID_ARGUMENT;c=(policy_connection*)calloc(1,sizeof(*c));if(!c)return PST_RESULT_OUT_OF_MEMORY;c->backend=r->backend;pst_diagnostic_initialize(&c->diagnostic);*out=c;return PST_RESULT_OK;}
static void mock_connection_destroy(void *state){free(state);}
static PST_RESULT mock_attach(void *state,void *transport,pst_u32 ownership,pst_u32 *accepted){(void)state;if(!transport||!accepted||ownership!=PST_BACKEND_OWNERSHIP_TRANSFERRED)return PST_RESULT_INVALID_ARGUMENT;*accepted=1UL;return PST_RESULT_OK;}
static int offered(const policy_connection *c,const pst_u8 *value,pst_size size){pst_size at=0,n;while(at<c->alpn_size){n=c->alpn[at++];if(at+n>c->alpn_size)return 0;if(n==size&&!memcmp(c->alpn+at,value,size))return 1;at+=n;}return 0;}
static PST_RESULT mock_handshake(void *state,pst_u32 *operation,PST_RESULT *error){policy_connection *c=(policy_connection*)state;if(!c||!operation||!error)return PST_RESULT_INVALID_ARGUMENT;if(c->alpn_requirement==PST_FEATURE_REQUIRED&&(!g_selected_alpn||!offered(c,g_selected_alpn,g_selected_alpn_size))){*operation=PST_OPERATION_FAILED;*error=PST_RESULT_POLICY_VIOLATION;pst_diagnostic_capture(&c->diagnostic,PST_RESULT_POLICY_VIOLATION,PST_DIAGNOSTIC_PHASE_ALPN,"policy-b",PST_DIAGNOSTIC_DOMAIN_NONE,0,0,0);return PST_RESULT_OK;}*operation=PST_OPERATION_COMPLETE;*error=PST_RESULT_OK;pst_diagnostic_clear(&c->diagnostic);return PST_RESULT_OK;}
static PST_RESULT mock_interest(void *state,pst_u32 *interest){if(!state||!interest)return PST_RESULT_INVALID_ARGUMENT;*interest=PST_INTEREST_READ;return PST_RESULT_OK;}
static PST_RESULT mock_wait(void *state,pst_u32 interest,pst_u32 timeout,PST_BACKEND_WAIT_RESULT *out){(void)interest;(void)timeout;if(!state||!out)return PST_RESULT_INVALID_ARGUMENT;out->ready_interest=PST_INTEREST_READ;out->timed_out=0;return PST_RESULT_OK;}
static PST_RESULT mock_read(void *state,void *buffer,pst_size size,PST_BACKEND_IO_RESULT *out){(void)buffer;(void)size;if(!state||!out)return PST_RESULT_INVALID_ARGUMENT;memset(out,0,sizeof(*out));out->operation=PST_OPERATION_COMPLETE;out->error=PST_RESULT_OK;return PST_RESULT_OK;}
static PST_RESULT mock_write(void *state,const void *buffer,pst_size size,PST_BACKEND_IO_RESULT *out){(void)buffer;if(!state||!out)return PST_RESULT_INVALID_ARGUMENT;memset(out,0,sizeof(*out));out->bytes_transferred=size;out->operation=PST_OPERATION_COMPLETE;out->error=PST_RESULT_OK;return PST_RESULT_OK;}
static PST_RESULT mock_shutdown_step(void *state,pst_u32 *operation,PST_RESULT *error){if(!state||!operation||!error)return PST_RESULT_INVALID_ARGUMENT;*operation=PST_OPERATION_COMPLETE;*error=PST_RESULT_OK;return PST_RESULT_OK;}
static PST_RESULT mock_configure(void *state,const pst_config *config){policy_connection *c=(policy_connection*)state;const pst_u8 *wire;pst_size size;if(!c||!config)return PST_RESULT_INVALID_ARGUMENT;c->min_version=pst_config_minimum_version(config);c->max_version=pst_config_maximum_version(config);c->alpn_requirement=pst_config_alpn_requirement(config);wire=pst_config_alpn_wire(config,&size);if(size>sizeof(c->alpn))return PST_RESULT_INVALID_ARGUMENT;if(size)memcpy(c->alpn,wire,size);c->alpn_size=size;return PST_RESULT_OK;}
static PST_RESULT mock_get_alpn(void *state,pst_u8 *buffer,pst_size capacity,pst_size *size){(void)state;if(!size)return PST_RESULT_INVALID_ARGUMENT;*size=g_selected_alpn_size;if(!g_selected_alpn)return PST_RESULT_UNAVAILABLE;if(capacity<g_selected_alpn_size)return PST_RESULT_TRUNCATED;if(g_selected_alpn_size&&!buffer)return PST_RESULT_INVALID_ARGUMENT;memcpy(buffer,g_selected_alpn,g_selected_alpn_size);return PST_RESULT_OK;}
static void mock_diagnostic(const void *state,pst_internal_diagnostic *out){const policy_connection *c=(const policy_connection*)state;if(!out)return;if(c&&c->backend)pst_diagnostic_copy(out,&c->diagnostic);else pst_diagnostic_initialize(out);}
static void transport_destroy(pst_transport *transport,int consumed){(void)transport;(void)consumed;++g_transport_destroyed;}
static void PST_CALL capture_log(void *context,const PST_LOG_EVENT *event){log_capture *c=(log_capture*)context;if(!c||!event)return;++c->total;if(event->level==PST_LOG_LEVEL_ERROR)++c->errors;}
#define VTABLE(init) {sizeof(PST_BACKEND_VTABLE),PST_BACKEND_SPI_VERSION,init,mock_shutdown,mock_runtime_create,mock_runtime_destroy,mock_query,mock_validate,mock_connection_create,mock_connection_destroy,mock_attach,mock_handshake,mock_interest,mock_wait,mock_read,mock_write,mock_shutdown_step,NULL,NULL,mock_configure,mock_get_alpn,mock_diagnostic}
static const PST_BACKEND_VTABLE g_va=VTABLE(initialize_a);static const PST_BACKEND_VTABLE g_vb=VTABLE(initialize_b);static const PST_BACKEND_VTABLE g_vc=VTABLE(initialize_c);
static const PST_BACKEND_DESCRIPTOR g_da={sizeof(PST_BACKEND_DESCRIPTOR),PST_BACKEND_SPI_VERSION,"policy-a","TLS 1.2",BASE_CAPS|PST_CAP_TLS_1_2,&g_va};
static const PST_BACKEND_DESCRIPTOR g_db={sizeof(PST_BACKEND_DESCRIPTOR),PST_BACKEND_SPI_VERSION,"policy-b","TLS 1.2/1.3 ALPN",BASE_CAPS|PST_CAP_TLS_1_2|PST_CAP_TLS_1_3|PST_CAP_ALPN|PST_CAP_CUSTOM_TRUST|PST_CAP_HOSTNAME_VERIFY|PST_CAP_CLIENT_AUTH,&g_vb};
static const PST_BACKEND_DESCRIPTOR g_dc={sizeof(PST_BACKEND_DESCRIPTOR),PST_BACKEND_SPI_VERSION,"policy-c","TLS 1.3",BASE_CAPS|PST_CAP_TLS_1_3,&g_vc};
static void init_policy(PST_TLS_POLICY *p,pst_u32 min,pst_u32 max){memset(p,0,sizeof(*p));p->struct_size=sizeof(*p);p->api_version=PST_API_VERSION;p->minimum_version=min;p->maximum_version=max;p->early_data=PST_FEATURE_DISABLED;}
static void init_options(PST_RUNTIME_OPTIONS *o,pst_u32 selection){memset(o,0,sizeof(*o));o->struct_size=sizeof(*o);o->api_version=PST_API_VERSION;o->selection=selection;}
static PST_RESULT make_connection(const char *id,pst_config *cfg,const PST_LOG_CONFIG *logging,pst_runtime **rt,pst_connection **cn){PST_RUNTIME_OPTIONS o;PST_RESULT r;init_options(&o,PST_BACKEND_SELECTION_EXACT);o.exact_backend_id=id;r=logging?pst_runtime_create_with_logging(&o,logging,rt,NULL):pst_runtime_create(&o,rt);if(r!=PST_RESULT_OK)return r;return pst_connection_create(*rt,cfg,cn);}
int main(void){
 pst_config *cfg,*cfg2;PST_TLS_POLICY p;PST_ALPN_PROTOCOL protocols[3];PST_IDENTITY_CONFIG identity;PST_TRUST_SOURCE trust_source;PST_CREDENTIAL_SOURCE credential_source;pst_trust *trust;pst_credentials *credential;const pst_u8 *wire;pst_size wire_size;pst_u8 a[]={'a'},bb[]={'b','b'},ccc[]={'c','c','c'},large[256],cert[]={1,2},key[]={3,4},ca[]={5,6};PST_RUNTIME_OPTIONS options;PST_RUNTIME_INFO info;const char *ordered[2];pst_runtime *runtime;pst_connection *connection;PST_DIAGNOSTIC_INFO diagnostic;PST_LOG_CONFIG logging;log_capture logs;pst_transport transport;pst_u32 accepted,operation;PST_RESULT error;PST_IO_RESULT io;PST_WAIT_RESULT wait_result;char byte='x';
 cfg=cfg2=NULL;trust=NULL;credential=NULL;runtime=NULL;connection=NULL;memset(large,'x',sizeof(large));
 CHECK(pst_config_create(&cfg)==PST_RESULT_OK,1);CHECK(pst_config_minimum_version(cfg)==12&&pst_config_maximum_version(cfg)==13,2);
 init_policy(&p,12,12);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK,3);init_policy(&p,13,13);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK,4);init_policy(&p,12,13);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK,5);
 init_policy(&p,13,12);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,6);CHECK(pst_config_minimum_version(cfg)==12&&pst_config_maximum_version(cfg)==13,7);init_policy(&p,99,13);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,8);init_policy(&p,12,99);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,9);init_policy(&p,0,0);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,10);init_policy(&p,14,14);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,11);
 protocols[0].data=a;protocols[0].size=1;protocols[1].data=bb;protocols[1].size=2;protocols[2].data=ccc;protocols[2].size=3;init_policy(&p,12,13);p.alpn_protocols=protocols;p.alpn_protocol_count=3;p.alpn_requirement=PST_FEATURE_REQUIRED;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK,12);a[0]='z';bb[0]='z';ccc[0]='z';wire=pst_config_alpn_wire(cfg,&wire_size);CHECK(wire_size==9&&wire[0]==1&&wire[1]=='a'&&wire[2]==2&&wire[3]=='b'&&wire[4]=='b'&&wire[5]==3&&wire[6]=='c'&&wire[7]=='c'&&wire[8]=='c',13);
 protocols[0].size=0;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,14);CHECK(pst_config_alpn_wire(cfg,&wire_size)==wire&&wire_size==9,15);protocols[0].data=large;protocols[0].size=256;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,16);protocols[0].data=NULL;protocols[0].size=1;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,17);init_policy(&p,12,13);p.alpn_protocols=protocols;p.alpn_protocol_count=0;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,18);init_policy(&p,12,13);p.alpn_requirement=3;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,19);protocols[0].data=large;protocols[0].size=255;init_policy(&p,12,13);p.alpn_protocols=protocols;p.alpn_protocol_count=1;p.alpn_requirement=PST_FEATURE_OPTIONAL;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK,20);CHECK((pst_config_required_capabilities(cfg)&PST_CAP_ALPN)!=0,21);protocols[0].data=large;protocols[0].size=1;init_policy(&p,12,13);p.alpn_protocols=protocols;p.alpn_protocol_count=(pst_size)-1;p.alpn_requirement=PST_FEATURE_REQUIRED;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_ARGUMENT,82);CHECK(pst_config_alpn_requirement(cfg)==PST_FEATURE_OPTIONAL,83);
 init_policy(&p,13,13);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK,22);CHECK((pst_config_required_capabilities(cfg)&PST_CAP_TLS_1_3)!=0&&(pst_config_required_capabilities(cfg)&PST_CAP_TLS_1_2)==0,23);CHECK(pst_config_freeze(cfg)==PST_RESULT_OK,24);init_policy(&p,12,12);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_INVALID_STATE,25);memset(&identity,0,sizeof(identity));identity.struct_size=sizeof(identity);identity.api_version=PST_API_VERSION;CHECK(pst_config_set_identity(cfg,&identity)==PST_RESULT_INVALID_STATE,26);pst_config_release(cfg);cfg=NULL; memset(&trust_source,0,sizeof(trust_source));trust_source.struct_size=sizeof(trust_source);trust_source.api_version=PST_API_VERSION;trust_source.kind=PST_TRUST_SOURCE_CUSTOM_CA_DER;CHECK(pst_trust_create(&trust_source,&trust)==PST_RESULT_INVALID_ARGUMENT,27);trust_source.data=ca;trust_source.data_size=sizeof(ca);CHECK(pst_trust_create(&trust_source,&trust)==PST_RESULT_OK,28);memset(&credential_source,0,sizeof(credential_source));credential_source.struct_size=sizeof(credential_source);credential_source.api_version=PST_API_VERSION;credential_source.kind=PST_CREDENTIAL_SOURCE_CERT_DER_PKCS8_DER;credential_source.certificate_der=cert;credential_source.certificate_der_size=sizeof(cert);CHECK(pst_credentials_create(&credential_source,&credential)==PST_RESULT_INVALID_ARGUMENT,29);credential_source.private_key_der=key;credential_source.private_key_der_size=sizeof(key);CHECK(pst_credentials_create(&credential_source,&credential)==PST_RESULT_OK,30);
 CHECK(pst_config_create(&cfg)==PST_RESULT_OK,31);memset(&identity,0,sizeof(identity));identity.struct_size=sizeof(identity);identity.api_version=PST_API_VERSION;identity.require_peer_authentication=1;CHECK(pst_config_set_identity(cfg,&identity)==PST_RESULT_OK&&pst_config_freeze(cfg)==PST_RESULT_POLICY_VIOLATION,32);identity.expected_hostname="";identity.expected_hostname_size=0;CHECK(pst_config_set_identity(cfg,&identity)==PST_RESULT_INVALID_ARGUMENT,65);identity.expected_hostname=(const char*)large;large[0]='a';large[1]=0;large[2]='b';identity.expected_hostname_size=3;CHECK(pst_config_set_identity(cfg,&identity)==PST_RESULT_INVALID_ARGUMENT,66);identity.expected_hostname="localhost";identity.expected_hostname_size=9;identity.trust=trust;CHECK(pst_config_set_identity(cfg,&identity)==PST_RESULT_OK&&pst_config_freeze(cfg)==PST_RESULT_OK,33);pst_config_release(cfg);cfg=NULL;CHECK(pst_config_create(&cfg)==PST_RESULT_OK,67);memset(&identity,0,sizeof(identity));identity.struct_size=sizeof(identity);identity.api_version=PST_API_VERSION;identity.require_client_authentication=1;CHECK(pst_config_set_identity(cfg,&identity)==PST_RESULT_OK&&pst_config_freeze(cfg)==PST_RESULT_POLICY_VIOLATION,68);pst_config_release(cfg);cfg=NULL;
 pst_backend_registry_reset();CHECK(pst_backend_register(&g_da)==PST_RESULT_OK&&pst_backend_register(&g_db)==PST_RESULT_OK&&pst_backend_register(&g_dc)==PST_RESULT_OK,34);ordered[0]="policy-a";ordered[1]="policy-b";init_options(&options,PST_BACKEND_SELECTION_ORDERED);options.preferred_backend_ids=ordered;options.preferred_backend_count=2;options.required_capabilities=PST_CAP_TLS_1_3;memset(&logs,0,sizeof(logs));CHECK(pst_log_config_init(&logging)==PST_RESULT_OK,35);logging.level=PST_LOG_LEVEL_ERROR;logging.callback=capture_log;logging.user_context=&logs;memset(&diagnostic,0,sizeof(diagnostic));diagnostic.struct_size=sizeof(diagnostic);diagnostic.api_version=PST_API_VERSION;CHECK(pst_runtime_create_with_logging(&options,&logging,&runtime,&diagnostic)==PST_RESULT_OK&&!diagnostic.valid,36);memset(&info,0,sizeof(info));info.struct_size=sizeof(info);info.api_version=PST_API_VERSION;CHECK(pst_runtime_get_info(runtime,&info)==PST_RESULT_OK&&!strcmp(info.backend_id,"policy-b")&&logs.errors==0,37);pst_runtime_release(runtime);runtime=NULL;
 options.required_capabilities=PST_CAP_SYSTEM_TRUST;memset(&diagnostic,0,sizeof(diagnostic));diagnostic.struct_size=sizeof(diagnostic);diagnostic.api_version=PST_API_VERSION;memset(&logs,0,sizeof(logs));CHECK(pst_runtime_create_with_logging(&options,&logging,&runtime,&diagnostic)==PST_RESULT_UNSUPPORTED&&runtime==NULL&&diagnostic.valid&&diagnostic.normalized_result==PST_RESULT_UNSUPPORTED&&logs.errors==1,38);init_options(&options,PST_BACKEND_SELECTION_EXACT);options.exact_backend_id="policy-a";options.required_capabilities=PST_CAP_TLS_1_3;CHECK(pst_runtime_create(&options,&runtime)==PST_RESULT_UNSUPPORTED,39);
 CHECK(pst_config_create(&cfg)==PST_RESULT_OK,40);init_policy(&p,13,13);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK&&pst_config_freeze(cfg)==PST_RESULT_OK,41);init_options(&options,PST_BACKEND_SELECTION_EXACT);options.exact_backend_id="policy-a";CHECK(pst_runtime_create(&options,&runtime)==PST_RESULT_OK,42);memset(&diagnostic,0,sizeof(diagnostic));diagnostic.struct_size=sizeof(diagnostic);diagnostic.api_version=PST_API_VERSION;CHECK(pst_connection_create_ex(runtime,cfg,&connection,&diagnostic)==PST_RESULT_UNSUPPORTED&&connection==NULL&&diagnostic.valid&&diagnostic.normalized_result==PST_RESULT_UNSUPPORTED,43);pst_runtime_release(runtime);runtime=NULL;pst_config_release(cfg);cfg=NULL;
 CHECK(pst_config_create(&cfg)==PST_RESULT_OK,44);init_policy(&p,12,12);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK&&pst_config_freeze(cfg)==PST_RESULT_OK,45);init_options(&options,PST_BACKEND_SELECTION_EXACT);options.exact_backend_id="policy-c";CHECK(pst_runtime_create(&options,&runtime)==PST_RESULT_OK,46);CHECK(pst_connection_create(runtime,cfg,&connection)==PST_RESULT_UNSUPPORTED&&connection==NULL,47);pst_runtime_release(runtime);runtime=NULL;pst_config_release(cfg);cfg=NULL;
 CHECK(pst_config_create(&cfg)==PST_RESULT_OK&&pst_config_create(&cfg2)==PST_RESULT_OK,48);init_policy(&p,12,12);CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK,49);protocols[0].data=(const pst_u8*)"one";protocols[0].size=3;init_policy(&p,13,13);p.alpn_protocols=protocols;p.alpn_protocol_count=1;p.alpn_requirement=PST_FEATURE_REQUIRED;CHECK(pst_config_set_tls_policy(cfg2,&p)==PST_RESULT_OK,50);CHECK(pst_config_minimum_version(cfg)==12&&pst_config_minimum_version(cfg2)==13&&pst_config_alpn_wire(cfg,&wire_size)==NULL&&wire_size==0,51);CHECK(pst_config_freeze(cfg)==PST_RESULT_OK&&pst_config_freeze(cfg2)==PST_RESULT_OK,52);pst_config_release(cfg);cfg=NULL;
 memset(&logs,0,sizeof(logs));logging.level=PST_LOG_LEVEL_ERROR;logging.user_context=&logs;g_selected_alpn=NULL;g_selected_alpn_size=0;CHECK(make_connection("policy-b",cfg2,&logging,&runtime,&connection)==PST_RESULT_OK,53);memset(&transport,0,sizeof(transport));transport.backend_id="policy-b";transport.native=&byte;transport.destroy=transport_destroy;accepted=0;CHECK(pst_connection_attach(connection,&transport,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_OK&&accepted,54);CHECK(pst_connection_handshake(connection,&operation,&error)==PST_RESULT_OK&&operation==PST_OPERATION_FAILED&&error==PST_RESULT_POLICY_VIOLATION&&logs.errors==1,55);memset(&diagnostic,0,sizeof(diagnostic));diagnostic.struct_size=sizeof(diagnostic);diagnostic.api_version=PST_API_VERSION;CHECK(pst_connection_copy_diagnostic(connection,&diagnostic)==PST_RESULT_OK&&diagnostic.valid&&diagnostic.normalized_result==PST_RESULT_POLICY_VIOLATION&&diagnostic.operation==PST_DIAGNOSTIC_OPERATION_CONFIGURATION,56);CHECK(pst_connection_handshake(connection,&operation,&error)==PST_RESULT_INVALID_STATE,57);CHECK(pst_connection_read(connection,&byte,1,&io)==PST_RESULT_INVALID_STATE,58);CHECK(pst_connection_write(connection,&byte,1,&io)==PST_RESULT_INVALID_STATE,59);CHECK(pst_connection_wait(connection,1,&wait_result)==PST_RESULT_INVALID_STATE,60);pst_connection_release(connection);connection=NULL;pst_runtime_release(runtime);runtime=NULL;
 g_selected_alpn=(const pst_u8*)"one";g_selected_alpn_size=3;CHECK(make_connection("policy-b",cfg2,NULL,&runtime,&connection)==PST_RESULT_OK,61);memset(&transport,0,sizeof(transport));transport.backend_id="policy-b";transport.native=&byte;transport.destroy=transport_destroy;accepted=0;CHECK(pst_connection_attach(connection,&transport,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_OK,62);CHECK(pst_connection_handshake(connection,&operation,&error)==PST_RESULT_OK&&operation==PST_OPERATION_COMPLETE,63);pst_connection_release(connection);pst_runtime_release(runtime);
 g_selected_alpn=(const pst_u8*)"other";g_selected_alpn_size=5;memset(&logs,0,sizeof(logs));logging.level=PST_LOG_LEVEL_TRACE;logging.user_context=&logs;CHECK(make_connection("policy-b",cfg2,&logging,&runtime,&connection)==PST_RESULT_OK,69);memset(&transport,0,sizeof(transport));transport.backend_id="policy-b";transport.native=&byte;transport.destroy=transport_destroy;accepted=0;CHECK(pst_connection_attach(connection,&transport,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_OK,70);CHECK(pst_connection_handshake(connection,&operation,&error)==PST_RESULT_OK&&operation==PST_OPERATION_FAILED&&error==PST_RESULT_POLICY_VIOLATION&&logs.errors==1,71);pst_connection_release(connection);pst_runtime_release(runtime);runtime=NULL;connection=NULL;
 init_options(&options,PST_BACKEND_SELECTION_EXACT);options.exact_backend_id="policy-a";CHECK(pst_runtime_create(&options,&runtime)==PST_RESULT_OK,72);CHECK(pst_connection_create(runtime,cfg2,&connection)==PST_RESULT_UNSUPPORTED&&connection==NULL,73);pst_runtime_release(runtime);runtime=NULL;pst_config_release(cfg2);
 CHECK(pst_config_create(&cfg)==PST_RESULT_OK,74);protocols[0].data=(const pst_u8*)"one";protocols[0].size=3;init_policy(&p,12,13);p.alpn_protocols=protocols;p.alpn_protocol_count=1;p.alpn_requirement=PST_FEATURE_OPTIONAL;CHECK(pst_config_set_tls_policy(cfg,&p)==PST_RESULT_OK&&pst_config_freeze(cfg)==PST_RESULT_OK,75);g_selected_alpn=NULL;g_selected_alpn_size=0;memset(&logs,0,sizeof(logs));logging.level=PST_LOG_LEVEL_OFF;logging.user_context=&logs;CHECK(make_connection("policy-b",cfg,&logging,&runtime,&connection)==PST_RESULT_OK,76);memset(&transport,0,sizeof(transport));transport.backend_id="policy-b";transport.native=&byte;transport.destroy=transport_destroy;accepted=0;CHECK(pst_connection_attach(connection,&transport,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_OK,77);CHECK(pst_connection_handshake(connection,&operation,&error)==PST_RESULT_OK&&operation==PST_OPERATION_COMPLETE&&logs.total==0,78);wire_size=99;CHECK(pst_connection_get_negotiated_alpn(connection,NULL,0,&wire_size)==PST_RESULT_UNAVAILABLE&&wire_size==0,79);pst_connection_release(connection);pst_runtime_release(runtime);runtime=NULL;connection=NULL;g_selected_alpn=(const pst_u8*)"one";g_selected_alpn_size=3;CHECK(make_connection("policy-b",cfg,NULL,&runtime,&connection)==PST_RESULT_OK,84);memset(&transport,0,sizeof(transport));transport.backend_id="policy-b";transport.native=&byte;transport.destroy=transport_destroy;accepted=0;CHECK(pst_connection_attach(connection,&transport,PST_OWNERSHIP_TRANSFERRED,&accepted)==PST_RESULT_OK,85);CHECK(pst_connection_handshake(connection,&operation,&error)==PST_RESULT_OK&&operation==PST_OPERATION_COMPLETE,86);wire_size=0;CHECK(pst_connection_get_negotiated_alpn(connection,large,sizeof(large),&wire_size)==PST_RESULT_OK&&wire_size==3&&!memcmp(large,"one",3),87);pst_connection_release(connection);pst_runtime_release(runtime);runtime=NULL;connection=NULL;init_options(&options,PST_BACKEND_SELECTION_EXACT);options.exact_backend_id="policy-a";CHECK(pst_runtime_create(&options,&runtime)==PST_RESULT_OK,80);CHECK(pst_connection_create(runtime,cfg,&connection)==PST_RESULT_UNSUPPORTED&&connection==NULL,81);pst_runtime_release(runtime);pst_config_release(cfg);cfg=NULL;
 pst_credentials_release(credential);pst_trust_release(trust);pst_backend_registry_reset();CHECK(g_transport_destroyed==5,64);printf("test_tls_policy: PASS\n");return 0;
}