#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <winsock2.h>
#include <openssl/crypto.h>
#include <openssl/err.h>
#include <openssl/provider.h>
#include <openssl/ssl.h>
#include <openssl/sslerr.h>
#include <openssl/x509.h>
#include "backends/openssl/pst_backend_openssl.h"
#include "pst_identity_internal.h"
#include "pst_transport_internal.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>

typedef struct ossl_base { pst_internal_diagnostic diagnostic; } ossl_base;
typedef struct ossl_backend { pst_internal_diagnostic diagnostic; } ossl_backend;
typedef struct ossl_runtime { pst_internal_diagnostic diagnostic; OSSL_LIB_CTX *library_context; OSSL_PROVIDER *default_provider; } ossl_runtime;
typedef struct ossl_connection {
    pst_internal_diagnostic diagnostic;
    ossl_runtime *runtime;
    SSL_CTX *ssl_context;
    SSL *ssl;
    SOCKET socket_value;
    int owns_socket;
    int configured;
    int established;
    int failed;
    int shutdown_started;
    pst_u32 interest;
    pst_u32 negotiated_version;
    pst_u32 cipher_suite;
    unsigned long private_errors[4];
    pst_u32 private_error_count;
} ossl_connection;

static void ossl_clear_errors(void){while(ERR_get_error()!=0UL){} }
static void ossl_collect_errors(ossl_connection *c,int *unexpected_eof){unsigned long code;c->private_error_count=0;if(unexpected_eof)*unexpected_eof=0;while((code=ERR_get_error())!=0UL){if(c->private_error_count<4UL)c->private_errors[c->private_error_count++]=code;
#ifdef SSL_R_UNEXPECTED_EOF_WHILE_READING
if(unexpected_eof&&ERR_GET_LIB(code)==ERR_LIB_SSL&&ERR_GET_REASON(code)==SSL_R_UNEXPECTED_EOF_WHILE_READING)*unexpected_eof=1;
#endif
}}
static void ossl_capture(ossl_base *s,PST_RESULT result,pst_u32 phase){pst_diagnostic_capture(&s->diagnostic,result,phase,"openssl",PST_DIAGNOSTIC_DOMAIN_NONE,0,0,0);}
static PST_RESULT ossl_initialize(void **out){ossl_backend *s;if(!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;ossl_clear_errors();if(OPENSSL_version_major()!=3||OPENSSL_version_minor()!=5||OPENSSL_version_patch()!=8)return PST_RESULT_INCOMPATIBLE_API;if(!OPENSSL_init_ssl(OPENSSL_INIT_NO_LOAD_CONFIG,NULL)){ossl_clear_errors();return PST_RESULT_BACKEND_FAILURE;}s=(ossl_backend*)calloc(1,sizeof(*s));if(!s){ossl_clear_errors();return PST_RESULT_OUT_OF_MEMORY;}pst_diagnostic_initialize(&s->diagnostic);ossl_clear_errors();*out=s;return PST_RESULT_OK;}
static void ossl_shutdown(void *v){ossl_clear_errors();free(v);}
static PST_RESULT ossl_runtime_create(void *backend,void **out){ossl_runtime *r;if(!backend||!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;ossl_clear_errors();r=(ossl_runtime*)calloc(1,sizeof(*r));if(!r)return PST_RESULT_OUT_OF_MEMORY;pst_diagnostic_initialize(&r->diagnostic);r->library_context=OSSL_LIB_CTX_new();if(!r->library_context){ossl_capture((ossl_base*)r,PST_RESULT_BACKEND_FAILURE,PST_DIAGNOSTIC_PHASE_RUNTIME_CREATE);ossl_clear_errors();free(r);return PST_RESULT_BACKEND_FAILURE;}r->default_provider=OSSL_PROVIDER_load(r->library_context,"default");if(!r->default_provider){ossl_capture((ossl_base*)r,PST_RESULT_BACKEND_FAILURE,PST_DIAGNOSTIC_PHASE_RUNTIME_CREATE);ossl_clear_errors();OSSL_LIB_CTX_free(r->library_context);free(r);return PST_RESULT_BACKEND_FAILURE;}ossl_clear_errors();*out=r;return PST_RESULT_OK;}
static void ossl_runtime_destroy(void *v){ossl_runtime *r=(ossl_runtime*)v;if(!r)return;ossl_clear_errors();if(r->default_provider)OSSL_PROVIDER_unload(r->default_provider);OSSL_LIB_CTX_free(r->library_context);ossl_clear_errors();free(r);}
static PST_RESULT ossl_query(void *v,pst_u32 *caps){if(!v||!caps)return PST_RESULT_INVALID_ARGUMENT;*caps=PST_BACKEND_CAP_TLS_1_2|PST_BACKEND_CAP_TLS_1_3|PST_BACKEND_CAP_NONBLOCKING|PST_BACKEND_CAP_BACKEND_WAIT;return PST_RESULT_OK;}
static PST_RESULT ossl_validate(void *v,pst_u32 required){pst_u32 caps=PST_BACKEND_CAP_TLS_1_2|PST_BACKEND_CAP_TLS_1_3|PST_BACKEND_CAP_NONBLOCKING|PST_BACKEND_CAP_BACKEND_WAIT;return v&&!(required&~caps)?PST_RESULT_OK:PST_RESULT_UNSUPPORTED;}
static PST_RESULT ossl_connection_create(void *v,void **out){ossl_connection *c;if(!v||!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;c=(ossl_connection*)calloc(1,sizeof(*c));if(!c)return PST_RESULT_OUT_OF_MEMORY;pst_diagnostic_initialize(&c->diagnostic);c->runtime=(ossl_runtime*)v;c->socket_value=INVALID_SOCKET;c->interest=PST_BACKEND_INTEREST_NONE;*out=c;return PST_RESULT_OK;}
static void ossl_connection_destroy(void *v){ossl_connection *c=(ossl_connection*)v;if(!c)return;ossl_clear_errors();if(c->ssl)SSL_free(c->ssl);if(c->ssl_context)SSL_CTX_free(c->ssl_context);if(c->owns_socket&&c->socket_value!=INVALID_SOCKET)closesocket(c->socket_value);ossl_clear_errors();memset(c->private_errors,0,sizeof(c->private_errors));free(c);}
static PST_RESULT ossl_configure(void *v,const pst_config *config){ossl_connection *c=(ossl_connection*)v;const pst_trust *trust;const pst_u8 *der;const unsigned char *cursor;pst_size der_size;pst_u32 minimum,maximum;int min_proto,max_proto;X509 *anchor;X509_STORE *store;if(!c||!config||c->configured)return PST_RESULT_INVALID_ARGUMENT;if(!pst_config_require_peer_authentication(config))return PST_RESULT_POLICY_VIOLATION;if(pst_config_require_client_authentication(config))return PST_RESULT_UNSUPPORTED;trust=pst_config_trust(config);if(!trust||pst_trust_kind(trust)!=PST_TRUST_SOURCE_CUSTOM_CA_DER)return PST_RESULT_UNSUPPORTED;der=pst_trust_data(trust,&der_size);if(!der||!der_size||der_size>(pst_size)LONG_MAX)return PST_RESULT_INVALID_ARGUMENT;minimum=pst_config_minimum_version(config);maximum=pst_config_maximum_version(config);if(minimum==PST_TLS_VERSION_1_2)min_proto=TLS1_2_VERSION;else if(minimum==PST_TLS_VERSION_1_3)min_proto=TLS1_3_VERSION;else return PST_RESULT_INVALID_ARGUMENT;if(maximum==PST_TLS_VERSION_1_2)max_proto=TLS1_2_VERSION;else if(maximum==PST_TLS_VERSION_1_3)max_proto=TLS1_3_VERSION;else return PST_RESULT_INVALID_ARGUMENT;if(maximum<minimum)return PST_RESULT_INVALID_ARGUMENT;ossl_clear_errors();c->ssl_context=SSL_CTX_new_ex(c->runtime->library_context,NULL,TLS_client_method());if(!c->ssl_context)goto backend_failure;if(!SSL_CTX_set_min_proto_version(c->ssl_context,min_proto)||!SSL_CTX_set_max_proto_version(c->ssl_context,max_proto))goto backend_failure;SSL_CTX_set_verify(c->ssl_context,SSL_VERIFY_PEER,NULL);SSL_CTX_clear_options(c->ssl_context,SSL_OP_IGNORE_UNEXPECTED_EOF);cursor=(const unsigned char*)der;anchor=d2i_X509(NULL,&cursor,(long)der_size);if(!anchor||cursor!=(const unsigned char*)der+der_size)goto policy_failure;store=SSL_CTX_get_cert_store(c->ssl_context);if(!store||X509_STORE_add_cert(store,anchor)!=1){X509_free(anchor);goto policy_failure;}X509_free(anchor);c->ssl=SSL_new(c->ssl_context);if(!c->ssl)goto backend_failure;SSL_clear_mode(c->ssl,SSL_MODE_AUTO_RETRY|SSL_MODE_ENABLE_PARTIAL_WRITE|SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER);SSL_set_connect_state(c->ssl);c->configured=1;ossl_clear_errors();return PST_RESULT_OK;
policy_failure:ossl_clear_errors();ossl_capture((ossl_base*)c,PST_RESULT_AUTH_FAILURE,PST_DIAGNOSTIC_PHASE_IDENTITY_SETUP);return PST_RESULT_AUTH_FAILURE;
backend_failure:ossl_clear_errors();ossl_capture((ossl_base*)c,PST_RESULT_BACKEND_FAILURE,PST_DIAGNOSTIC_PHASE_TLS_CONFIGURE);return PST_RESULT_BACKEND_FAILURE;}
static PST_RESULT ossl_attach(void *v,void *native,pst_u32 ownership,pst_u32 *accepted){ossl_connection *c=(ossl_connection*)v;PST_NATIVE_TRANSPORT *t=(PST_NATIVE_TRANSPORT*)native;u_long nonblocking=1UL;if(!accepted)return PST_RESULT_INVALID_ARGUMENT;*accepted=0;if(!c||!t||!c->configured||!c->ssl||c->owns_socket)return PST_RESULT_INVALID_ARGUMENT;if(ownership!=PST_BACKEND_OWNERSHIP_TRANSFERRED)return PST_RESULT_UNSUPPORTED;if(t->struct_size<PST_NATIVE_TRANSPORT_MIN_SIZE||t->version!=PST_NATIVE_TRANSPORT_VERSION||t->kind!=PST_NATIVE_TRANSPORT_KIND_WIN32_SOCKET)return PST_RESULT_INVALID_ARGUMENT;if(ioctlsocket((SOCKET)t->native_socket,FIONBIO,&nonblocking)!=0){ossl_capture((ossl_base*)c,PST_RESULT_TRANSPORT_FAILURE,PST_DIAGNOSTIC_PHASE_TRANSPORT_ATTACH);return PST_RESULT_TRANSPORT_FAILURE;}ossl_clear_errors();if(SSL_set_fd(c->ssl,(int)(SOCKET)t->native_socket)!=1){ossl_clear_errors();ossl_capture((ossl_base*)c,PST_RESULT_BACKEND_FAILURE,PST_DIAGNOSTIC_PHASE_TRANSPORT_ATTACH);return PST_RESULT_BACKEND_FAILURE;}ossl_clear_errors();c->socket_value=(SOCKET)t->native_socket;c->owns_socket=1;c->interest=PST_BACKEND_INTEREST_WRITE;*accepted=1;return PST_RESULT_OK;}
static PST_RESULT ossl_fail(ossl_connection *c,pst_u32 phase,PST_RESULT result,pst_u32 *operation,PST_RESULT *error){c->failed=1;c->interest=PST_BACKEND_INTEREST_NONE;*operation=PST_BACKEND_OPERATION_FAILED;*error=result;ossl_capture((ossl_base*)c,result,phase);return PST_RESULT_OK;}
static PST_RESULT ossl_want(ossl_connection *c,int ssl_error,pst_u32 *operation,PST_RESULT *error){*error=PST_RESULT_OK;if(ssl_error==SSL_ERROR_WANT_READ){c->interest=PST_BACKEND_INTEREST_READ;*operation=PST_BACKEND_OPERATION_NEED_READ;ossl_clear_errors();return PST_RESULT_OK;}if(ssl_error==SSL_ERROR_WANT_WRITE){c->interest=PST_BACKEND_INTEREST_WRITE;*operation=PST_BACKEND_OPERATION_NEED_WRITE;ossl_clear_errors();return PST_RESULT_OK;}return PST_RESULT_UNAVAILABLE;}
static PST_RESULT ossl_classify_failure(ossl_connection *c,int ssl_error,int ret,pst_u32 phase,pst_u32 *operation,PST_RESULT *error,pst_u32 *close_kind){int unexpected=0;PST_RESULT result;ossl_collect_errors(c,&unexpected);if(close_kind)*close_kind=PST_BACKEND_CLOSE_NONE;if(ssl_error==SSL_ERROR_ZERO_RETURN){if(close_kind)*close_kind=PST_BACKEND_CLOSE_CLEAN;c->interest=PST_BACKEND_INTEREST_NONE;*operation=PST_BACKEND_OPERATION_CLOSED;*error=PST_RESULT_OK;return PST_RESULT_OK;}if(unexpected||(ssl_error==SSL_ERROR_SYSCALL&&ret==0)){result=PST_RESULT_TRUNCATED;if(close_kind)*close_kind=PST_BACKEND_CLOSE_TRUNCATED;}else if(ssl_error==SSL_ERROR_SYSCALL)result=PST_RESULT_TRANSPORT_FAILURE;else if(ssl_error==SSL_ERROR_SSL&&SSL_get_verify_result(c->ssl)!=X509_V_OK)result=PST_RESULT_AUTH_FAILURE;else if(ssl_error==SSL_ERROR_SSL)result=PST_RESULT_PROTOCOL_FAILURE;else result=PST_RESULT_BACKEND_FAILURE;return ossl_fail(c,phase,result,operation,error);}
static PST_RESULT ossl_handshake(void *v,pst_u32 *operation,PST_RESULT *error){ossl_connection *c=(ossl_connection*)v;const SSL_CIPHER *cipher;int ret,ssl_error,protocol;PST_RESULT mapped;if(!c||!operation||!error||!c->configured||!c->owns_socket||c->failed)return PST_RESULT_INVALID_ARGUMENT;ossl_clear_errors();ret=SSL_do_handshake(c->ssl);if(ret!=1){ssl_error=SSL_get_error(c->ssl,ret);mapped=ossl_want(c,ssl_error,operation,error);if(mapped==PST_RESULT_OK)return PST_RESULT_OK;return ossl_classify_failure(c,ssl_error,ret,PST_DIAGNOSTIC_PHASE_HANDSHAKE,operation,error,NULL);}ossl_clear_errors();if(SSL_get_verify_result(c->ssl)!=X509_V_OK)return ossl_fail(c,PST_DIAGNOSTIC_PHASE_HANDSHAKE,PST_RESULT_AUTH_FAILURE,operation,error);protocol=SSL_version(c->ssl);if(protocol==TLS1_2_VERSION)c->negotiated_version=PST_TLS_VERSION_1_2;else if(protocol==TLS1_3_VERSION)c->negotiated_version=PST_TLS_VERSION_1_3;else return ossl_fail(c,PST_DIAGNOSTIC_PHASE_HANDSHAKE,PST_RESULT_PROTOCOL_FAILURE,operation,error);cipher=SSL_get_current_cipher(c->ssl);if(!cipher)return ossl_fail(c,PST_DIAGNOSTIC_PHASE_HANDSHAKE,PST_RESULT_PROTOCOL_FAILURE,operation,error);c->cipher_suite=(pst_u32)SSL_CIPHER_get_protocol_id(cipher);c->established=1;c->interest=PST_BACKEND_INTEREST_READ;*operation=PST_BACKEND_OPERATION_COMPLETE;*error=PST_RESULT_OK;return PST_RESULT_OK;}
static PST_RESULT ossl_interest(void *v,pst_u32 *interest){ossl_connection *c=(ossl_connection*)v;if(!c||!interest||!c->owns_socket||c->failed)return PST_RESULT_INVALID_ARGUMENT;if(c->established&&(SSL_pending(c->ssl)>0||SSL_has_pending(c->ssl)))c->interest|=PST_BACKEND_INTEREST_READ;*interest=c->interest;return PST_RESULT_OK;}
static PST_RESULT ossl_wait(void *v,pst_u32 interest,pst_u32 timeout_ms,PST_BACKEND_WAIT_RESULT *result){ossl_connection *c=(ossl_connection*)v;fd_set reads,writes,errors;struct timeval timeout;int ready;if(!c||!result||!c->owns_socket||c->failed)return PST_RESULT_INVALID_ARGUMENT;memset(result,0,sizeof(*result));if((interest&PST_BACKEND_INTEREST_READ)&&c->established&&(SSL_pending(c->ssl)>0||SSL_has_pending(c->ssl))){result->ready_interest=PST_BACKEND_INTEREST_READ;return PST_RESULT_OK;}FD_ZERO(&reads);FD_ZERO(&writes);FD_ZERO(&errors);if(interest&PST_BACKEND_INTEREST_READ)FD_SET(c->socket_value,&reads);if(interest&PST_BACKEND_INTEREST_WRITE)FD_SET(c->socket_value,&writes);FD_SET(c->socket_value,&errors);timeout.tv_sec=(long)(timeout_ms/1000UL);timeout.tv_usec=(long)((timeout_ms%1000UL)*1000UL);ready=select(0,&reads,&writes,&errors,&timeout);if(ready==SOCKET_ERROR||FD_ISSET(c->socket_value,&errors)){ossl_capture((ossl_base*)c,PST_RESULT_TRANSPORT_FAILURE,PST_DIAGNOSTIC_PHASE_WAIT);c->failed=1;c->interest=PST_BACKEND_INTEREST_NONE;return PST_RESULT_TRANSPORT_FAILURE;}if(ready==0){result->timed_out=1;return PST_RESULT_OK;}if(FD_ISSET(c->socket_value,&reads))result->ready_interest|=PST_BACKEND_INTEREST_READ;if(FD_ISSET(c->socket_value,&writes))result->ready_interest|=PST_BACKEND_INTEREST_WRITE;return PST_RESULT_OK;}
static void ossl_io_reset(PST_BACKEND_IO_RESULT *r){memset(r,0,sizeof(*r));r->operation=PST_BACKEND_OPERATION_FAILED;r->error=PST_RESULT_OK;}
static PST_RESULT ossl_read(void *v,void *buffer,pst_size capacity,PST_BACKEND_IO_RESULT *result){ossl_connection *c=(ossl_connection*)v;size_t read_size=0;int ret,ssl_error;PST_RESULT mapped,error;pst_u32 operation;if(!c||!result||(!buffer&&capacity))return PST_RESULT_INVALID_ARGUMENT;ossl_io_reset(result);if(!c->established||c->failed)return PST_RESULT_INVALID_STATE;if(capacity==0){result->operation=PST_BACKEND_OPERATION_COMPLETE;return PST_RESULT_OK;}ossl_clear_errors();ret=SSL_read_ex(c->ssl,buffer,(size_t)capacity,&read_size);if(ret==1){ossl_clear_errors();result->bytes_transferred=(pst_size)read_size;result->operation=PST_BACKEND_OPERATION_COMPLETE;c->interest=PST_BACKEND_INTEREST_READ;return PST_RESULT_OK;}ssl_error=SSL_get_error(c->ssl,ret);mapped=ossl_want(c,ssl_error,&operation,&error);if(mapped==PST_RESULT_OK){result->operation=operation;result->error=error;return PST_RESULT_OK;}ossl_classify_failure(c,ssl_error,ret,PST_DIAGNOSTIC_PHASE_READ,&operation,&error,&result->close_kind);result->operation=operation;result->error=error;return PST_RESULT_OK;}
static PST_RESULT ossl_write(void *v,const void *buffer,pst_size length,PST_BACKEND_IO_RESULT *result){ossl_connection *c=(ossl_connection*)v;size_t written=0;int ret,ssl_error;PST_RESULT mapped,error;pst_u32 operation;if(!c||!result||(!buffer&&length))return PST_RESULT_INVALID_ARGUMENT;ossl_io_reset(result);if(!c->established||c->failed)return PST_RESULT_INVALID_STATE;if(length==0){result->operation=PST_BACKEND_OPERATION_COMPLETE;return PST_RESULT_OK;}ossl_clear_errors();ret=SSL_write_ex(c->ssl,buffer,(size_t)length,&written);if(ret==1){ossl_clear_errors();result->bytes_transferred=(pst_size)written;result->operation=PST_BACKEND_OPERATION_COMPLETE;c->interest=PST_BACKEND_INTEREST_READ;return PST_RESULT_OK;}ssl_error=SSL_get_error(c->ssl,ret);mapped=ossl_want(c,ssl_error,&operation,&error);if(mapped==PST_RESULT_OK){result->operation=operation;result->error=error;return PST_RESULT_OK;}ossl_classify_failure(c,ssl_error,ret,PST_DIAGNOSTIC_PHASE_WRITE,&operation,&error,NULL);result->operation=operation;result->error=error;return PST_RESULT_OK;}
static PST_RESULT ossl_close(void *v,pst_u32 *operation,PST_RESULT *error){ossl_connection *c=(ossl_connection*)v;int ret,ssl_error;PST_RESULT mapped;if(!c||!operation||!error||!c->established||c->failed)return PST_RESULT_INVALID_ARGUMENT;ossl_clear_errors();ret=SSL_shutdown(c->ssl);if(ret==1){ossl_clear_errors();c->interest=PST_BACKEND_INTEREST_NONE;*operation=PST_BACKEND_OPERATION_COMPLETE;*error=PST_RESULT_OK;return PST_RESULT_OK;}if(ret==0){ossl_clear_errors();c->shutdown_started=1;c->interest=PST_BACKEND_INTEREST_READ;*operation=PST_BACKEND_OPERATION_NEED_READ;*error=PST_RESULT_OK;return PST_RESULT_OK;}ssl_error=SSL_get_error(c->ssl,ret);mapped=ossl_want(c,ssl_error,operation,error);if(mapped==PST_RESULT_OK)return PST_RESULT_OK;return ossl_classify_failure(c,ssl_error,ret,PST_DIAGNOSTIC_PHASE_SHUTDOWN,operation,error,NULL);}
static PST_RESULT ossl_peer(void *v,void **out){if(out)*out=NULL;return v&&out?PST_RESULT_UNSUPPORTED:PST_RESULT_INVALID_ARGUMENT;}
static void ossl_peer_destroy(void *v){(void)v;}
static PST_RESULT ossl_alpn(void *v,pst_u8 *buffer,pst_size capacity,pst_size *size){(void)buffer;(void)capacity;if(size)*size=0;return v&&size?PST_RESULT_UNSUPPORTED:PST_RESULT_INVALID_ARGUMENT;}
static void ossl_diagnostic(const void *v,pst_internal_diagnostic *out){if(!out)return;if(v)pst_diagnostic_copy(out,&((const ossl_base*)v)->diagnostic);else pst_diagnostic_initialize(out);}
static const PST_BACKEND_VTABLE ossl_vtable={sizeof(PST_BACKEND_VTABLE),PST_BACKEND_SPI_VERSION,ossl_initialize,ossl_shutdown,ossl_runtime_create,ossl_runtime_destroy,ossl_query,ossl_validate,ossl_connection_create,ossl_connection_destroy,ossl_attach,ossl_handshake,ossl_interest,ossl_wait,ossl_read,ossl_write,ossl_close,ossl_peer,ossl_peer_destroy,ossl_configure,ossl_alpn,ossl_diagnostic};
static const PST_BACKEND_METADATA ossl_metadata={sizeof(PST_BACKEND_METADATA),PST_BACKEND_METADATA_VERSION,{PST_BACKEND_VERSION_AVAILABLE,0UL,2UL,0UL,"pst-openssl","tls-io"},1UL,{{PST_BACKEND_VERSION_AVAILABLE,3UL,5UL,8UL,"OpenSSL","LTS"},{0}}};
static const PST_BACKEND_DESCRIPTOR ossl_descriptor={sizeof(PST_BACKEND_DESCRIPTOR),PST_BACKEND_SPI_VERSION,"openssl","OpenSSL 3.5.8",PST_BACKEND_CAP_TLS_1_2|PST_BACKEND_CAP_TLS_1_3|PST_BACKEND_CAP_NONBLOCKING|PST_BACKEND_CAP_BACKEND_WAIT,&ossl_vtable,&ossl_metadata};
PST_RESULT pst_backend_openssl_connection_info(void *v,pst_u32 *tls_version,pst_u32 *cipher_suite){ossl_connection *c=(ossl_connection*)v;if(!c||!tls_version||!cipher_suite)return PST_RESULT_INVALID_ARGUMENT;if(!c->established)return PST_RESULT_INVALID_STATE;*tls_version=c->negotiated_version;*cipher_suite=c->cipher_suite;return PST_RESULT_OK;}
const PST_BACKEND_DESCRIPTOR *pst_backend_openssl_descriptor(void){return &ossl_descriptor;}
PST_RESULT pst_backend_openssl_register(void){return pst_backend_register(&ossl_descriptor);}