/* SPDX-License-Identifier: MPL-2.0 */
#include "pst_internal.h"
#include <stdlib.h>
#include <string.h>
typedef struct pst_wait_member { pst_connection *connection; pst_external_source *source; pst_wait_token token; pst_u32 interests; } pst_wait_member;
struct pst_wait_set { pst_wait_member *members; pst_size count,capacity; };
static int fail_next_growth;
void pst_wait_set_test_fail_next_growth(void){fail_next_growth=1;}
PST_RESULT PST_CALL pst_wait_set_create(pst_wait_set **out){pst_wait_set*s;if(!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;s=(pst_wait_set*)calloc(1,sizeof(*s));if(!s)return PST_RESULT_OUT_OF_MEMORY;*out=s;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_destroy(pst_wait_set *s){if(!s)return PST_RESULT_INVALID_ARGUMENT;if(s->count)return PST_RESULT_INVALID_STATE;free(s->members);free(s);return PST_RESULT_OK;}
static PST_RESULT pst_wait_set_grow(pst_wait_set *s){pst_wait_member*m;pst_size n,limit=(pst_size)-1;if(s->count<s->capacity)return PST_RESULT_OK;if(fail_next_growth){fail_next_growth=0;return PST_RESULT_OUT_OF_MEMORY;}if(s->capacity>limit/2UL)return PST_RESULT_OUT_OF_MEMORY;n=s->capacity?s->capacity*2UL:4UL;if(n>limit/sizeof(*m))return PST_RESULT_OUT_OF_MEMORY;m=(pst_wait_member*)realloc(s->members,n*sizeof(*m));if(!m)return PST_RESULT_OUT_OF_MEMORY;s->members=m;s->capacity=n;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_add_connection(pst_wait_set *s,pst_connection *c,pst_wait_token token){pst_size i;PST_RESULT r;if(!s||!c)return PST_RESULT_INVALID_ARGUMENT;for(i=0;i<s->count;i++){if(s->members[i].connection==c)return PST_RESULT_ALREADY_REGISTERED;if(s->members[i].token==token)return PST_RESULT_ALREADY_REGISTERED;}r=pst_wait_set_grow(s);if(r!=PST_RESULT_OK)return r;if(pst_connection_wait_set_bind(c,s)!=PST_RESULT_OK)return PST_RESULT_ALREADY_REGISTERED;s->members[s->count].connection=c;s->members[s->count].source=NULL;s->members[s->count].token=token;s->members[s->count].interests=0UL;s->count++;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_remove_connection(pst_wait_set *s,pst_connection *c){pst_size i;if(!s||!c)return PST_RESULT_INVALID_ARGUMENT;for(i=0;i<s->count;i++)if(s->members[i].connection==c){pst_connection_wait_set_unbind(c,s);if(i+1UL<s->count)memmove(&s->members[i],&s->members[i+1],(s->count-i-1UL)*sizeof(s->members[0]));s->count--;return PST_RESULT_OK;}return PST_RESULT_NOT_REGISTERED;}
PST_RESULT PST_CALL pst_wait_set_add_external_source(pst_wait_set *s,pst_external_source *source,pst_u32 interests,pst_wait_token token){pst_size i;PST_RESULT r;if(!s||!source)return PST_RESULT_INVALID_ARGUMENT;if(!interests||(interests&~(PST_INTEREST_READ|PST_INTEREST_WRITE)))return PST_RESULT_INVALID_ARGUMENT;for(i=0;i<s->count;i++){if(s->members[i].source==source)return PST_RESULT_ALREADY_REGISTERED;if(s->members[i].token==token)return PST_RESULT_ALREADY_REGISTERED;}if(source->wait_set)return PST_RESULT_ALREADY_REGISTERED;r=pst_wait_set_grow(s);if(r!=PST_RESULT_OK)return r;s->members[s->count].connection=NULL;s->members[s->count].source=source;s->members[s->count].token=token;s->members[s->count].interests=interests;source->wait_set=s;s->count++;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_remove_external_source(pst_wait_set *s,pst_external_source *source){pst_size i;if(!s||!source)return PST_RESULT_INVALID_ARGUMENT;for(i=0;i<s->count;i++)if(s->members[i].source==source){source->wait_set=NULL;if(i+1UL<s->count)memmove(&s->members[i],&s->members[i+1],(s->count-i-1UL)*sizeof(s->members[0]));s->count--;return PST_RESULT_OK;}return PST_RESULT_NOT_REGISTERED;}
PST_RESULT PST_CALL pst_external_source_try_release(pst_external_source *source){if(!source)return PST_RESULT_INVALID_ARGUMENT;if(source->wait_set)return PST_RESULT_INVALID_STATE;source->destroy(source);return PST_RESULT_OK;}
void PST_CALL pst_external_source_release(pst_external_source *source){if(source&&!source->wait_set)source->destroy(source);}
PST_RESULT PST_CALL pst_wait_set_wait(pst_wait_set *s,pst_u32 timeout,PST_WAIT_EVENT *events,pst_size capacity,PST_WAIT_SET_RESULT *out){pst_size i,total=0,copied=0;pst_u32 interest;PST_RESULT r,terminal;PST_WAIT_RESULT wr;if(!out)return PST_RESULT_INVALID_ARGUMENT;memset(out,0,sizeof(*out));if(!s||(capacity&&!events))return PST_RESULT_INVALID_ARGUMENT;if(timeout!=0UL)return PST_RESULT_UNSUPPORTED;for(i=0;i<s->count;i++){PST_WAIT_EVENT e;memset(&e,0,sizeof(e));e.token=s->members[i].token;if(s->members[i].source){r=s->members[i].source->poll(s->members[i].source,s->members[i].interests,&e.ready_interest);if(r!=PST_RESULT_OK)return r;e.ready_interest&=s->members[i].interests;e.flags=PST_WAIT_READY_EXTERNAL;e.result=PST_RESULT_OK;if(!e.ready_interest)continue;}else if(pst_connection_is_terminal(s->members[i].connection,&terminal)){e.flags=PST_WAIT_READY_TERMINAL;e.result=terminal;}else{r=pst_connection_get_interest(s->members[i].connection,&interest);if(r!=PST_RESULT_OK)return r;memset(&wr,0,sizeof(wr));r=pst_connection_wait(s->members[i].connection,0UL,&wr);if(r!=PST_RESULT_OK){if(pst_connection_is_terminal(s->members[i].connection,&terminal)){e.flags=PST_WAIT_READY_TERMINAL;e.result=terminal;}else return r;}else{e.ready_interest=wr.ready_interest;e.result=PST_RESULT_OK;if(!e.ready_interest)continue;}}if(copied<capacity)events[copied++]=e;total++;}out->ready_count=total;out->event_count=copied;if(!total){out->timed_out=1UL;return PST_RESULT_WAIT_TIMEOUT;}return total>capacity?PST_RESULT_INSUFFICIENT_CAPACITY:PST_RESULT_OK;}
