#include "pst_backend.h"
#include "pst_identity_internal.h"
#include "pst_transport_internal.h"
#include <stdlib.h>
#include <string.h>
struct pst_runtime { const PST_BACKEND_DESCRIPTOR *backend;void *backend_state,*runtime_state;pst_u32 capabilities,connections; };
struct pst_connection { pst_runtime *runtime;pst_config *config;void *backend_state;pst_transport *transport;pst_u32 state,pending_io,pending_interest,last_wait_ready,suppressed_interest;int wait_observed; };
#define C_CREATED 1UL
#define C_ATTACHED 2UL
#define C_HANDSHAKING 3UL
#define C_ESTABLISHED 4UL
#define C_SHUTTING 5UL
#define C_CLOSED 6UL
#define C_FAILED 7UL
#define IO_NONE 0UL
#define IO_READ 1UL
#define IO_WRITE 2UL
static void progress_reset(pst_connection *c){c->pending_io=IO_NONE;c->pending_interest=0UL;c->last_wait_ready=0UL;c->suppressed_interest=0UL;c->wait_observed=0;}
static pst_u32 operation_interest(pst_u32 op){if(op==PST_OPERATION_NEED_READ)return PST_BACKEND_INTEREST_READ;if(op==PST_OPERATION_NEED_WRITE)return PST_BACKEND_INTEREST_WRITE;if(op==PST_OPERATION_NEED_READ_WRITE)return PST_BACKEND_INTEREST_READ|PST_BACKEND_INTEREST_WRITE;return PST_BACKEND_INTEREST_NONE;}
static void progress_after_io(pst_connection *c,pst_u32 kind,const PST_BACKEND_IO_RESULT *b,PST_RESULT result){pst_u32 interest,primary;if(result!=PST_RESULT_OK||b->bytes_transferred!=0||b->operation==PST_OPERATION_COMPLETE||b->operation==PST_OPERATION_CLOSED||b->operation==PST_OPERATION_FAILED){progress_reset(c);return;}interest=operation_interest(b->operation);primary=kind==IO_READ?PST_BACKEND_INTEREST_READ:PST_BACKEND_INTEREST_WRITE;c->suppressed_interest=0UL;if(c->pending_io==kind&&c->pending_interest==interest&&c->wait_observed&&(interest&primary)!=0UL&&(c->last_wait_ready&primary)==0UL)c->suppressed_interest=c->last_wait_ready&interest&~primary;c->pending_io=kind;c->pending_interest=interest;c->last_wait_ready=0UL;c->wait_observed=0;}
static int version_ok(pst_u32 v){return ((v>>16)&0xffffUL)==PST_API_VERSION_MAJOR;}
static const PST_BACKEND_DESCRIPTOR *select_backend(const PST_RUNTIME_OPTIONS *o,pst_size i){if(o->selection==PST_BACKEND_SELECTION_EXACT)return i?NULL:pst_backend_find(o->exact_backend_id);if(o->selection==PST_BACKEND_SELECTION_ORDERED)return i<o->preferred_backend_count?pst_backend_find(o->preferred_backend_ids[i]):NULL;return i<pst_backend_count()?pst_backend_find_by_index(i):NULL;}
PST_RESULT PST_CALL pst_runtime_create(const PST_RUNTIME_OPTIONS *o,pst_runtime **out){pst_runtime *r;const PST_BACKEND_DESCRIPTOR *d;PST_RESULT x;pst_size i,limit;if(!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;if(!o||o->struct_size<PST_RUNTIME_OPTIONS_MIN_SIZE)return PST_RESULT_INVALID_ARGUMENT;if(!version_ok(o->api_version))return PST_RESULT_INCOMPATIBLE_API;if(o->selection<1||o->selection>3)return PST_RESULT_INVALID_ARGUMENT;if(o->selection==PST_BACKEND_SELECTION_EXACT&&(!o->exact_backend_id||!o->exact_backend_id[0]))return PST_RESULT_INVALID_ARGUMENT;if(o->selection==PST_BACKEND_SELECTION_ORDERED&&(!o->preferred_backend_ids||!o->preferred_backend_count))return PST_RESULT_INVALID_ARGUMENT;limit=o->selection==PST_BACKEND_SELECTION_ORDERED?o->preferred_backend_count:(o->selection==PST_BACKEND_SELECTION_EXACT?1:pst_backend_count());for(i=0;i<limit;i++){d=select_backend(o,i);if(!d)continue;r=(pst_runtime*)calloc(1,sizeof(*r));if(!r)return PST_RESULT_OUT_OF_MEMORY;r->backend=d;x=d->vtable->initialize(&r->backend_state);if(x!=PST_RESULT_OK){free(r);continue;}x=d->vtable->query_capabilities(r->backend_state,&r->capabilities);if(x==PST_RESULT_OK&&(o->required_capabilities&~r->capabilities)==0){x=d->vtable->runtime_create(r->backend_state,&r->runtime_state);if(x==PST_RESULT_OK){*out=r;return PST_RESULT_OK;}}d->vtable->shutdown(r->backend_state);free(r);}return PST_RESULT_UNSUPPORTED;}
void PST_CALL pst_runtime_release(pst_runtime *r){if(!r)return;if(r->connections)return;r->backend->vtable->runtime_destroy(r->runtime_state);r->backend->vtable->shutdown(r->backend_state);free(r);}
PST_RESULT PST_CALL pst_runtime_get_info(const pst_runtime *r,PST_RUNTIME_INFO *i){if(!r||!i||i->struct_size<PST_RUNTIME_INFO_MIN_SIZE)return PST_RESULT_INVALID_ARGUMENT;if(!version_ok(i->api_version))return PST_RESULT_INCOMPATIBLE_API;i->backend_id=r->backend->id;i->capabilities=r->capabilities;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_connection_create(pst_runtime *r,pst_config *cfg,pst_connection **out){pst_connection *c;PST_RESULT x;pst_u32 req;if(!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;if(!r||!cfg||!pst_config_is_frozen(cfg))return PST_RESULT_INVALID_STATE;req=pst_config_required_capabilities(cfg);if(req&~r->capabilities)return PST_RESULT_UNSUPPORTED;x=r->backend->vtable->validate_requirements(r->runtime_state,req);if(x!=PST_RESULT_OK)return x;c=(pst_connection*)calloc(1,sizeof(*c));if(!c)return PST_RESULT_OUT_OF_MEMORY;x=r->backend->vtable->connection_create(r->runtime_state,&c->backend_state);if(x!=PST_RESULT_OK){free(c);return x;}x=r->backend->vtable->connection_configure_identity(c->backend_state,cfg);if(x!=PST_RESULT_OK){r->backend->vtable->connection_destroy(c->backend_state);free(c);return x;}c->runtime=r;c->config=cfg;c->state=C_CREATED;pst_config_retain(cfg);++r->connections;*out=c;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_connection_attach(pst_connection *c,pst_transport *t,pst_u32 own,pst_u32 *accepted){PST_RESULT x;if(!accepted)return PST_RESULT_INVALID_ARGUMENT;*accepted=0;if(!c||!t||c->state!=C_CREATED)return PST_RESULT_INVALID_STATE;if(own!=PST_OWNERSHIP_TRANSFERRED)return PST_RESULT_UNSUPPORTED;if(strcmp(t->backend_id,c->runtime->backend->id))return PST_RESULT_UNSUPPORTED;x=c->runtime->backend->vtable->attach_transport(c->backend_state,t->native,own,accepted);if(*accepted){c->transport=t;c->state=x==PST_RESULT_OK?C_ATTACHED:C_FAILED;}return x;}
PST_RESULT PST_CALL pst_connection_handshake(pst_connection *c,pst_u32 *op,PST_RESULT *error){PST_RESULT x;if(!c||!op||!error||(c->state!=C_ATTACHED&&c->state!=C_HANDSHAKING))return PST_RESULT_INVALID_STATE;progress_reset(c);c->state=C_HANDSHAKING;x=c->runtime->backend->vtable->handshake_step(c->backend_state,op,error);if(x!=PST_RESULT_OK||*op==PST_OPERATION_FAILED)c->state=C_FAILED;else if(*op==PST_OPERATION_COMPLETE)c->state=C_ESTABLISHED;return x;}
PST_RESULT PST_CALL pst_connection_get_interest(pst_connection *c,pst_u32 *i){if(!c||!i||(c->state!=C_HANDSHAKING&&c->state!=C_SHUTTING&&c->state!=C_ESTABLISHED))return PST_RESULT_INVALID_STATE;return c->runtime->backend->vtable->get_interest(c->backend_state,i);}
PST_RESULT PST_CALL pst_connection_wait(pst_connection *c,pst_u32 timeout,PST_WAIT_RESULT *out){PST_BACKEND_WAIT_RESULT b;pst_u32 i,requested;PST_RESULT x;if(!out)return PST_RESULT_INVALID_ARGUMENT;x=pst_connection_get_interest(c,&i);if(x!=PST_RESULT_OK)return x;requested=i&~c->suppressed_interest;if(requested==0UL)requested=i;x=c->runtime->backend->vtable->wait(c->backend_state,requested,timeout,&b);out->ready_interest=b.ready_interest;out->timed_out=b.timed_out;if(x==PST_RESULT_OK){if(b.timed_out){c->suppressed_interest=0UL;c->last_wait_ready=0UL;c->wait_observed=0;}else{c->last_wait_ready=b.ready_interest;c->wait_observed=b.ready_interest!=0UL;}}return x;}
static void copy_io(PST_IO_RESULT *o,const PST_BACKEND_IO_RESULT *b){o->bytes_transferred=b->bytes_transferred;o->operation=b->operation;o->close_kind=b->close_kind;o->error=b->error;}
PST_RESULT PST_CALL pst_connection_read(pst_connection *c,void *buf,pst_size n,PST_IO_RESULT *o){PST_BACKEND_IO_RESULT b;PST_RESULT x;if(!c||c->state!=C_ESTABLISHED)return PST_RESULT_INVALID_STATE;if(!o)return PST_RESULT_INVALID_ARGUMENT;x=c->runtime->backend->vtable->read(c->backend_state,buf,n,&b);copy_io(o,&b);progress_after_io(c,IO_READ,&b,x);if(b.operation==PST_OPERATION_CLOSED)c->state=C_CLOSED;else if(b.operation==PST_OPERATION_FAILED)c->state=C_FAILED;return x;}
PST_RESULT PST_CALL pst_connection_write(pst_connection *c,const void *buf,pst_size n,PST_IO_RESULT *o){PST_BACKEND_IO_RESULT b;PST_RESULT x;if(!c||c->state!=C_ESTABLISHED)return PST_RESULT_INVALID_STATE;if(!o)return PST_RESULT_INVALID_ARGUMENT;x=c->runtime->backend->vtable->write(c->backend_state,buf,n,&b);copy_io(o,&b);progress_after_io(c,IO_WRITE,&b,x);if(b.operation==PST_OPERATION_FAILED)c->state=C_FAILED;return x;}
PST_RESULT PST_CALL pst_connection_get_peer_info(pst_connection *c,pst_peer_info **out){if(!c||c->state!=C_ESTABLISHED)return PST_RESULT_INVALID_STATE;return c->runtime->backend->vtable->peer_info_create(c->backend_state,(void**)out);}
PST_RESULT PST_CALL pst_connection_get_negotiated_alpn(pst_connection *c,pst_u8 *b,pst_size cap,pst_size *n){if(!c||c->state!=C_ESTABLISHED)return PST_RESULT_INVALID_STATE;return c->runtime->backend->vtable->connection_get_alpn(c->backend_state,b,cap,n);}
PST_RESULT PST_CALL pst_connection_shutdown(pst_connection *c,pst_u32 *op,PST_RESULT *e){PST_RESULT x;if(!c||!op||!e||(c->state!=C_ESTABLISHED&&c->state!=C_SHUTTING))return PST_RESULT_INVALID_STATE;progress_reset(c);c->state=C_SHUTTING;x=c->runtime->backend->vtable->shutdown_step(c->backend_state,op,e);if(*op==PST_OPERATION_COMPLETE)c->state=C_CLOSED;else if(*op==PST_OPERATION_FAILED)c->state=C_FAILED;return x;}
void PST_CALL pst_connection_release(pst_connection *c){if(!c)return;c->runtime->backend->vtable->connection_destroy(c->backend_state);if(c->transport)c->transport->destroy(c->transport,1);pst_config_release(c->config);--c->runtime->connections;free(c);}
void PST_CALL pst_transport_release(pst_transport *t){if(t)t->destroy(t,0);}
