/* SPDX-License-Identifier: MPL-2.0 */
#include "pst_internal.h"
#include <stdlib.h>
#include <string.h>
typedef struct pst_wait_member { pst_connection *connection; pst_external_source *source; pst_wait_token token; pst_u32 interests; } pst_wait_member;
struct pst_wait_set { pst_wait_member *members; pst_size count,capacity; void *platform; };
static int fail_next_growth;
void pst_wait_set_test_fail_next_growth(void){fail_next_growth=1;}
PST_RESULT PST_CALL pst_wait_set_create(pst_wait_set **out){pst_wait_set*s;PST_RESULT r;if(!out)return PST_RESULT_INVALID_ARGUMENT;*out=NULL;s=(pst_wait_set*)calloc(1,sizeof(*s));if(!s)return PST_RESULT_OUT_OF_MEMORY;r=pst_platform_wait_set_create(&s->platform);if(r!=PST_RESULT_OK){free(s);return r;}*out=s;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_destroy(pst_wait_set *s){if(!s)return PST_RESULT_INVALID_ARGUMENT;if(!pst_platform_wait_set_is_owner(s->platform)||pst_platform_wait_set_is_active(s->platform))return PST_RESULT_CONCURRENT_OPERATION;if(s->count)return PST_RESULT_INVALID_STATE;pst_platform_wait_set_destroy(s->platform);free(s->members);free(s);return PST_RESULT_OK;}
static PST_RESULT pst_wait_set_grow(pst_wait_set *s){pst_wait_member*m;pst_size n,limit=(pst_size)-1;if(s->count<s->capacity)return PST_RESULT_OK;if(fail_next_growth){fail_next_growth=0;return PST_RESULT_OUT_OF_MEMORY;}if(s->capacity>limit/2UL)return PST_RESULT_OUT_OF_MEMORY;n=s->capacity?s->capacity*2UL:4UL;if(n>limit/sizeof(*m))return PST_RESULT_OUT_OF_MEMORY;m=(pst_wait_member*)realloc(s->members,n*sizeof(*m));if(!m)return PST_RESULT_OUT_OF_MEMORY;s->members=m;s->capacity=n;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_add_connection(pst_wait_set *s,pst_connection *c,pst_wait_token token){pst_size i;PST_RESULT r;if(!s||!c)return PST_RESULT_INVALID_ARGUMENT;if(!pst_platform_wait_set_is_owner(s->platform)||pst_platform_wait_set_is_active(s->platform))return PST_RESULT_CONCURRENT_OPERATION;for(i=0;i<s->count;i++){if(s->members[i].connection==c)return PST_RESULT_ALREADY_REGISTERED;if(s->members[i].token==token)return PST_RESULT_ALREADY_REGISTERED;}r=pst_wait_set_grow(s);if(r!=PST_RESULT_OK)return r;if(pst_connection_wait_set_bind(c,s)!=PST_RESULT_OK)return PST_RESULT_ALREADY_REGISTERED;s->members[s->count].connection=c;s->members[s->count].source=NULL;s->members[s->count].token=token;s->members[s->count].interests=0UL;s->count++;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_remove_connection(pst_wait_set *s,pst_connection *c){pst_size i;if(!s||!c)return PST_RESULT_INVALID_ARGUMENT;if(!pst_platform_wait_set_is_owner(s->platform)||pst_platform_wait_set_is_active(s->platform))return PST_RESULT_CONCURRENT_OPERATION;for(i=0;i<s->count;i++)if(s->members[i].connection==c){pst_connection_wait_set_unbind(c,s);if(i+1UL<s->count)memmove(&s->members[i],&s->members[i+1],(s->count-i-1UL)*sizeof(s->members[0]));s->count--;return PST_RESULT_OK;}return PST_RESULT_NOT_REGISTERED;}
PST_RESULT PST_CALL pst_wait_set_add_external_source(pst_wait_set *s,pst_external_source *source,pst_u32 interests,pst_wait_token token){pst_size i;PST_RESULT r;if(!s||!source)return PST_RESULT_INVALID_ARGUMENT;if(!pst_platform_wait_set_is_owner(s->platform)||pst_platform_wait_set_is_active(s->platform))return PST_RESULT_CONCURRENT_OPERATION;if(!interests||(interests&~(PST_INTEREST_READ|PST_INTEREST_WRITE)))return PST_RESULT_INVALID_ARGUMENT;for(i=0;i<s->count;i++){if(s->members[i].source==source)return PST_RESULT_ALREADY_REGISTERED;if(s->members[i].token==token)return PST_RESULT_ALREADY_REGISTERED;}if(source->wait_set)return PST_RESULT_ALREADY_REGISTERED;r=pst_wait_set_grow(s);if(r!=PST_RESULT_OK)return r;s->members[s->count].connection=NULL;s->members[s->count].source=source;s->members[s->count].token=token;s->members[s->count].interests=interests;source->wait_set=s;s->count++;return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_remove_external_source(pst_wait_set *s,pst_external_source *source){pst_size i;if(!s||!source)return PST_RESULT_INVALID_ARGUMENT;if(!pst_platform_wait_set_is_owner(s->platform)||pst_platform_wait_set_is_active(s->platform))return PST_RESULT_CONCURRENT_OPERATION;for(i=0;i<s->count;i++)if(s->members[i].source==source){source->wait_set=NULL;if(i+1UL<s->count)memmove(&s->members[i],&s->members[i+1],(s->count-i-1UL)*sizeof(s->members[0]));s->count--;return PST_RESULT_OK;}return PST_RESULT_NOT_REGISTERED;}
PST_RESULT PST_CALL pst_external_source_try_release(pst_external_source *source){if(!source)return PST_RESULT_INVALID_ARGUMENT;if(source->wait_set)return PST_RESULT_INVALID_STATE;source->destroy(source);return PST_RESULT_OK;}
void PST_CALL pst_external_source_release(pst_external_source *source){if(source&&!source->wait_set)source->destroy(source);}
static PST_RESULT pst_wait_set_enumerate(pst_wait_set *s,PST_WAIT_EVENT *events,pst_size capacity,PST_WAIT_SET_RESULT *out){pst_size i,total=0,copied=0;pst_u32 interest;PST_RESULT r,terminal;PST_WAIT_RESULT wr;for(i=0;i<s->count;i++){PST_WAIT_EVENT e;memset(&e,0,sizeof(e));e.token=s->members[i].token;if(s->members[i].source){r=s->members[i].source->poll(s->members[i].source,s->members[i].interests,&e.ready_interest);if(r!=PST_RESULT_OK)return r;e.ready_interest&=s->members[i].interests;e.flags=PST_WAIT_READY_EXTERNAL;e.result=PST_RESULT_OK;if(!e.ready_interest)continue;}else if(pst_connection_is_terminal(s->members[i].connection,&terminal)){e.flags=PST_WAIT_READY_TERMINAL;e.result=terminal;}else{r=pst_connection_get_interest(s->members[i].connection,&interest);if(r!=PST_RESULT_OK)return r;memset(&wr,0,sizeof(wr));r=pst_connection_wait(s->members[i].connection,0UL,&wr);if(r!=PST_RESULT_OK){if(pst_connection_is_terminal(s->members[i].connection,&terminal)){e.flags=PST_WAIT_READY_TERMINAL;e.result=terminal;}else return r;}else{e.ready_interest=wr.ready_interest;e.result=PST_RESULT_OK;if(!e.ready_interest)continue;}}if(copied<capacity)events[copied++]=e;total++;}out->ready_count=total;out->event_count=copied;if(!total)return PST_RESULT_WAIT_TIMEOUT;return total>capacity?PST_RESULT_INSUFFICIENT_CAPACITY:PST_RESULT_OK;}
static PST_RESULT pst_wait_set_native_entries(pst_wait_set *s,pst_platform_wait_entry *entries){pst_size i;PST_RESULT r;pst_u32 interest;for(i=0;i<s->count;i++){entries[i].ready_interest=0UL;if(s->members[i].source){if(!s->members[i].source->native_source)return PST_RESULT_UNSUPPORTED;r=s->members[i].source->native_source(s->members[i].source,&entries[i].native_source);entries[i].interests=s->members[i].interests;}else{interest=PST_INTEREST_NONE;r=pst_connection_native_wait_source(s->members[i].connection,&entries[i].native_source);if(r==PST_RESULT_OK)r=pst_connection_get_interest(s->members[i].connection,&interest);entries[i].interests=interest;}if(r!=PST_RESULT_OK)return r;}return PST_RESULT_OK;}
PST_RESULT PST_CALL pst_wait_set_wait(pst_wait_set *s,pst_u32 timeout,PST_WAIT_EVENT *events,pst_size capacity,PST_WAIT_SET_RESULT *out){pst_platform_wait_entry *entries=NULL;PST_RESULT r;PST_WAIT_SET_RESULT immediate;pst_u32 woken=0UL,start,elapsed,remaining;int suppressed;pst_size i;if(!out)return PST_RESULT_INVALID_ARGUMENT;memset(out,0,sizeof(*out));if(!s||(capacity&&!events))return PST_RESULT_INVALID_ARGUMENT;r=pst_platform_wait_set_begin(s->platform);if(r!=PST_RESULT_OK)return r;memset(&immediate,0,sizeof(immediate));r=pst_wait_set_enumerate(s,events,capacity,&immediate);if(r!=PST_RESULT_WAIT_TIMEOUT){*out=immediate;pst_platform_wait_set_end(s->platform);return r;}if(timeout==0UL){out->timed_out=1UL;pst_platform_wait_set_end(s->platform);return PST_RESULT_WAIT_TIMEOUT;}if(s->count){entries=(pst_platform_wait_entry*)calloc(s->count,sizeof(*entries));if(!entries){pst_platform_wait_set_end(s->platform);return PST_RESULT_OUT_OF_MEMORY;}r=pst_wait_set_native_entries(s,entries);if(r!=PST_RESULT_OK){free(entries);pst_platform_wait_set_end(s->platform);return r;}}start=pst_platform_monotonic_ms();remaining=timeout;for(;;){r=pst_platform_wait_set_wait(s->platform,entries,s->count,remaining,&woken);if(r==PST_RESULT_WAIT_TIMEOUT){out->timed_out=1UL;break;}if(r!=PST_RESULT_OK)break;r=pst_wait_set_enumerate(s,events,capacity,out);out->woken=woken;if(r!=PST_RESULT_WAIT_TIMEOUT||woken){if(r==PST_RESULT_WAIT_TIMEOUT)r=PST_RESULT_WAIT_WOKEN;break;}suppressed=0;for(i=0;i<s->count;i++)if(!s->members[i].source&&entries[i].ready_interest){entries[i].interests&=~entries[i].ready_interest;suppressed=1;}if(!suppressed){r=PST_RESULT_RESOURCE_FAILURE;break;}elapsed=pst_platform_monotonic_ms()-start;if(elapsed>=timeout){out->timed_out=1UL;r=PST_RESULT_WAIT_TIMEOUT;break;}remaining=timeout-elapsed;}free(entries);pst_platform_wait_set_end(s->platform);return r;}
PST_RESULT PST_CALL pst_wait_set_wake(pst_wait_set *s){return s?pst_platform_wait_set_wake(s->platform):PST_RESULT_INVALID_ARGUMENT;}
